import { chromium } from "playwright-core";
import { execFileSync } from "node:child_process";
const tag = process.argv[2] ?? "before";
const only = process.argv[3];
const b = await chromium.launch({ executablePath: process.env.HOME + "/.cache/ms-playwright/chromium-1148/chrome-linux/chrome", args: ["--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--no-sandbox"] });
const ctx = await b.newContext({ viewport: { width: 1280, height: 620 } });
const shots = [];
const shot = async (name, url, prep, wait = 2500) => {
  if (only && !only.split(",").includes(name)) return;
  const p = await ctx.newPage();
  p.on("pageerror", (e) => console.log(name, "PAGEERR", e.message));
  await p.goto("http://localhost:5199/" + url, { waitUntil: "commit" });
  await p.waitForFunction(() => window.grudge && !document.getElementById("boot"), null, { timeout: 90000 });
  if (prep) await p.evaluate(prep);
  await p.waitForTimeout(wait);
  const f = `/tmp/opencode/menus/${tag}_${name}.png`;
  await p.screenshot({ path: f });
  shots.push(f);
  await p.close();
};
execFileSync("mkdir", ["-p", "/tmp/opencode/menus"]);
await shot("title", "");
await shot("main", "?screen=menu");
for (const pg of ["network", "rules", "options", "records", "controls"]) await shot(pg, `?screen=menu&page=${pg}`);
await shot("select", "?screen=select&join=1");
await shot("select2v2", "?screen=select&join=2&mode=2v2");
await shot("map", "?screen=map");
await shot("hud", "?bots=1&map=crossing", () => { grudge.humanize(0); }, 5000);
await shot("pause", "?bots=1&map=crossing", () => { grudge.humanize(0); setTimeout(() => grudge.pause(), 1500); }, 3500);
await shot("results", "?bots=1&map=crossing&time=120", () => { setTimeout(() => grudge.endMatch(0), 500); }, 6000);
await b.close();
for (const f of shots) execFileSync("magick", [f, "-resize", "50%", f.replace(".png", ".jpg")]);
console.log(shots.length);
