import heroJson from "../../data/heroes.json";
import talentJson from "../../data/talents.json";
import unitJson from "../../data/units.json";
import structJson from "../../data/structures.json";
import matchJson from "../../data/match.json";

export type CodexArt =
  | { kind: "shot"; hero: string; slot: "a" | "b" | "r" | "z" }
  | { kind: "portrait"; hero: string }
  | { kind: "map"; index: number }
  | { kind: "seal"; glyph: string; color?: string }
  | { kind: "unit"; type: string };

export interface CodexPick {
  id: string;
  name: string;
  desc: string;
  combo?: string;
}

export interface CodexPage {
  title: string;
  text: string;
  art: CodexArt;
  tip?: string;
  picks?: CodexPick[];
}

export interface CodexEntry {
  cat: string;
  title: string;
  glyph: string;
  pages: CodexPage[];
}

type Ability = { kind: string; callout?: string; cooldown?: number };
type Hero = { name: string; health: string; speed: string; damage: string; abilities: Record<"a" | "b" | "r" | "z", Ability> };
type Talent = { id: string; name: string; desc: string; combo?: string };

const HEROES = (heroJson as unknown as { heroes: Record<string, Hero> }).heroes;
const TALENTS = (talentJson as unknown as { heroes: Record<string, Record<"r" | "b" | "a" | "z", Talent[]>> }).heroes;
const U = unitJson as unknown as { waves: { everySeconds: number; spawnCost: Record<string, number> }; types: Record<string, { hp: number; bounty: number }>; popCap: number };
const S = structJson as unknown as { types: Record<string, { name: string; cost: number; upgradeCost: number; mix?: Record<string, number> }>; buildSeconds: number; rubbleSeconds: number };
const M = matchJson as unknown as {
  economy: { start: number; income: number; loss: { heroDeath: number; tower: number }; rally: { seconds: number; damageMul: number; speedMul: number }; bounty: { hero: number; structure: number } };
  arena: {
    shop: { bomb: { cost: number; coreDamage: number }; ward: { cost: number; cooldown: number }; cannon: { cost: number; shots: number } };
    relic: { firstSeconds: number; enshrineSeconds: number; stealSeconds: number; incomeMul: number };
    ogre: { firstSeconds: number; hp: number; bounty: number; blessSeconds: number; respawnSeconds: number };
    cannon: { firstSeconds: number; everySeconds: number; damage: number; structureDamage: number };
    morph?: { holdSeconds: number; channelSeconds: number; revertCost: number };
  };
};
const pct = (m: number) => `${Math.round((m - 1) * 100)}%`;

interface HeroText {
  lore: string;
  role: string;
  a: [string, string];
  b: [string, string];
  r: [string, string];
  z: [string, string];
  picks: Record<string, string>;
  evo: Record<"r" | "b" | "a" | "z", string>;
  tactics: string;
  fear: string;
}

const TEXT: Record<string, HeroText> = {
  warlord: {
    lore: "BORN IN A TENT, RAISED BY A WAR DRUM, NAMED BY A GOAT. HE HAS NEVER LOST AN ARGUMENT, MOSTLY BECAUSE HE ANSWERS EVERY ONE BY HITTING THE FLOOR VERY HARD. HIS BRUTES LOVE HIM. NOBODY HAS ASKED WHY.",
    role: "THE HEAVY. SLOW TO START, MISERABLE TO STAND NEXT TO. HIS BRUTES COME OUT TOUGHER THAN ANYONE ELSE'S.",
    a: ["TWO BIG SWINGS. THE SECOND ONE SENDS PEOPLE BACKWARDS.", "THE FINISHER KNOCKS FOES OUT OF REACH. IF YOU WANT TO KEEP HITTING, WALK AFTER THEM."],
    b: ["GROUND SLAM. A RING OF PAIN THAT SLOWS AND COWS EVERYONE IN IT, SO THEY HIT SOFTER FOR A MOMENT.", "SLAM FIRST, QUAKE SECOND. EARTHQUAKE HITS SLOWED FOES HARDER."],
    r: ["WAR CRY. EVERY ALLY NEARBY HITS HARDER AND MOVES FASTER FOR A FEW SECONDS. TROOPS COUNT.", "SAVE IT FOR WHEN YOUR ARMY IS ALREADY SWINGING AT SOMETHING. A WAR CRY AT AN EMPTY FIELD IS JUST SHOUTING."],
    z: ["EARTHQUAKE. A HUGE STOMP THAT STUNS EVERYONE AROUND YOU AND HURTS BUILDINGS TOO.", "WAIT FOR THEM TO CLUMP UP OR COMMIT TO A FIGHT. A WHIFFED QUAKE IS A VERY LOUD APOLOGY."],
    picks: {
      bloodroar: "TAKE IT IF YOU FIGHT ALONGSIDE A BIG ARMY. EVERY TROOP BECOMES A LITTLE LEECH.",
      challenge: "TAKE IT IF YOU KEEP LOSING DUELS. YANKING A FAST HERO INTO YOUR LAP SOLVES MOST PROBLEMS.",
      magnitude: "PULLS EVERYONE INTO ONE SPOT. PERFECT SETUP FOR EARTHQUAKE. WITH CHALLENGE IT STUNS TOO.",
      shouldercharge: "TURNS YOUR SLAM INTO A GAP-CLOSER. GOOD AGAINST RUNNERS LIKE GRIM AND REMNIL.",
      earthsplitter: "GIVES YOU A RANGED STUN ON EVERY FINISHER. GREAT FOR CLEARING TROOPS IN A LINE.",
      berserker: "SELF-HEALING AND FASTER SWINGS. PICK IT IF YOU PLAN TO STAND IN THE MIDDLE OF EVERYTHING.",
      cataclysm: "MORE QUAKE. NOBODY HAS EVER COMPLAINED ABOUT MORE QUAKE.",
    },
    evo: {
      r: "THE BIG QUESTION: ARE YOU LEADING AN ARMY OR HUNTING HEROES?",
      b: "SLAM UPGRADES. LOOK AT YOUR WAR CRY PICK FIRST, EACH SLAM HAS A FAVOURITE.",
      a: "PICK BY WHAT YOU'RE HITTING MOST: A LINE OF TROOPS OR ONE ANNOYING HERO.",
      z: "THE QUAKE GETS BIGGER AND LEAVES LAVA. THAT'S IT. THAT'S THE PAGE.",
    },
    tactics: "WALK IN BEHIND YOUR BRUTES, SLAM WHEN THEY ENGAGE, WAR CRY WHEN EVERYONE IS SWINGING, QUAKE WHEN THEY TRY TO RUN. YOU ARE NOT FAST, SO DON'T CHASE FOR LONG. LET THEM COME TO YOU.",
    fear: "GETTING KITED. REMNIL AND STIG'S BALLISTA CAN HURT YOU FROM FAR AWAY WHILE YOU STOMP AT NOTHING.",
  },
  engineer: {
    lore: "STIG BUILT HIS FIRST TOWER AT AGE SIX OUT OF SPOONS. IT HELD FOR THREE WEEKS AND HURT A MAILMAN. HE HAS NEVER BEEN PROUDER OF ANYTHING. HE BUILDS CHEAPER BECAUSE HE ARGUES WITH EVERY MERCHANT FOR AN HOUR.",
    role: "THE BUILDER. HIS TOWERS AND UPGRADES COST LESS, HE REPAIRS THEM, AND HE CAN RAISE A RAMP AND PARK A BALLISTA ON IT.",
    a: ["A WRENCH COMBO. NOTHING FANCY. STANDING ON YOUR OWN RAMP, A INSTEAD THROWS THE WRENCH.", "STIG IS STURDY, SO YOU CAN TRADE HITS. JUST DON'T EXPECT TO WIN A DUEL WITH FRANCOIS ON WRENCH ALONE."],
    b: ["REPAIR. HEALS EVERY BUILDING AROUND YOU AND HITS NEARBY FOES WITH THE PULSE.", "A TOWER ABOUT TO FALL IS A TOWER THAT ISN'T. KEEP AN EYE ON YOUR HEALTH BARS."],
    r: ["SIEGE RAMP. RAISES A RAMP YOU CAN STAND ON. HIGH GROUND, BETTER SHOTS, ANGRY ENEMIES BELOW.", "BUILD IT NEXT TO AN ENEMY TOWER, THEN PUT THE BALLISTA ON TOP."],
    z: ["BALLISTA. PLANTS A BIG CROSSBOW THAT SHOOTS ON ITS OWN. ON A RAMP IT HITS HARDER. ONLY ONE AT A TIME.", "PLACE IT WHERE THEY HAVE TO WALK, NOT WHERE THEY ALREADY ARE."],
    picks: {
      teslatower: "YOUR RAMP BECOMES A LIGHTNING COIL. EXCELLENT AGAINST CROWDS OF TROOPS.",
      palisade: "YOUR RAMP BECOMES A SPIKED WALL THAT POPS UP UNDER PEOPLE. BLOCKS ROADS, STUNS, HURTS.",
      shockwrench: "REPAIR BECOMES A STUN BOMB. WITH TESLA TOWER IT ALSO MAKES YOUR TOWERS FIRE DOUBLE SPEED.",
      fortify: "REPAIRS HAND OUT SHIELDS TO EVERYONE. WITH PALISADE YOUR WALLS STAY UP LONGER.",
      riveter: "YOUR FINISHER SHOOTS HOT RIVETS. FINALLY, A REASON TO HIT THINGS.",
      overclock: "HITTING STUFF LOWERS YOUR REPAIR COOLDOWN AND STARTS ZAPPING. GOOD IF YOU BRAWL A LOT.",
      greatballista: "A BIGGER, MEANER, LONGER-LIVED BALLISTA. TAKE IT. YOU DON'T HAVE A CHOICE ANYWAY.",
    },
    evo: {
      r: "WHAT SHOULD YOUR RAMP BECOME? LIGHTNING FOR THE CROWDS, OR A WALL FOR THE ROADS.",
      b: "REPAIR UPGRADES. BOTH COMBOS ARE STRONG, SO MATCH THE ONE THAT GOES WITH YOUR RAMP.",
      a: "STIG DOESN'T LIVE ON HIS BASIC ATTACK, BUT THESE MAKE IT WORTH PRESSING.",
      z: "GREAT BALLISTA. PROBABLY THE MOST POLITE WAY TO DESTROY A KEEP.",
    },
    tactics: "BUILD EARLY, BUILD OFTEN. YOU GET TOWERS CHEAPER, SO SPEND THAT GOLD ON OUTPOSTS AND UPGRADES. PUSH WITH A RAMP AND BALLISTA COMBO AND LET THE MACHINES DO THE DAMAGE.",
    fear: "GRIM SNEAKING AROUND YOUR TOWERS AND BREAKING THEM WHILE YOU'RE BUSY BEING HANDY ELSEWHERE.",
  },
  raider: {
    lore: "GRIM WAS RAISED BY WOLVES, WHO LATER SUED. HE HAS NO HOUSE, NO BANNER AND NO TABLE MANNERS. HE DOES HAVE TWO VERY SHARP KNIVES AND AN ENORMOUS GRUDGE AGAINST EVERYONE TALLER THAN HIM, WHICH IS EVERYONE.",
    role: "THE GLASS CANNON. FASTEST HERO, LEAST HEALTH, MOST STAB. GETS IN, KILLS SOMEONE, GETS OUT. CAN CLIMB SLOPES OTHERS CAN'T.",
    a: ["A FLURRY OF NEAR-INSTANT STABS WITH A HEAVIER FINISHER. HITS FROM BEHIND DEAL MORE.", "STICK TO ONE TARGET. YOUR SWINGS ARE NARROW, SO SPINNING AROUND IN A CROWD WASTES THEM."],
    b: ["LEAP. JUMP UP TO 8M AND LAND ON SOMEONE. KILLS RESET THE COOLDOWN.", "USE IT TO GET IN, OR TO GET OUT. NOT BOTH, UNLESS YOU KILL SOMETHING."],
    r: ["SMOKE. GO INVISIBLE FOR A FEW SECONDS AND MOVE FASTER. YOUR FIRST HIT OUT OF SMOKE HURTS DOUBLE.", "WALK BEHIND THEM, THEN ATTACK. A STEALTHED STAB TO THE BACK IS THE WHOLE POINT OF YOU."],
    z: ["EXECUTE DASH. A LONG DASH THAT DEALS HUGE DAMAGE AND HITS EVEN HARDER ON WOUNDED FOES.", "DON'T OPEN WITH IT. FINISH WITH IT."],
    picks: {
      smokebomb: "YOUR SMOKE ALSO CHOKES AND SLOWS ANYONE STANDING IN IT. NOBODY ESCAPES.",
      shadowstep: "YOUR SMOKE BECOMES A SHORT TELEPORT. CROSS WALLS, CLIFFS AND BAD DECISIONS.",
      pounce: "LEAP MARKS ITS VICTIM, THEN THE MARK EXPLODES. WITH SMOKE BOMB MARKS HURT EVEN MORE.",
      doublejump: "LEAP TWICE. WITH SHADOW STEP, BLINKING GIVES YOU LEAP BACK. YOU WILL NEVER TOUCH THE GROUND.",
      serrated: "BLEED STACKS AND A BIG RIP ON THE FINISHER. YOU HEAL OFF BLEEDING FOES.",
      twinfangs: "YOUR FINISHER THROWS POISON DAGGERS THAT SLOW AND BOUNCE. GOOD FOR CHASING.",
      deathmark: "EXECUTE AT HALF HEALTH INSTEAD OF 40%, AND A KILL REFUNDS YOUR METER. CHAIN KILLS.",
    },
    evo: {
      r: "AMBUSHER OR ESCAPE ARTIST. SMOKE BOMB TRAPS, SHADOW STEP TELEPORTS.",
      b: "LEAP UPGRADES. EACH ONE IS BUILT FOR ONE OF YOUR SMOKE PICKS, SO MATCH THEM.",
      a: "BLEED THEM OUT OR SLOW THEM DOWN. BOTH SAY 'YOU'RE NOT LEAVING'.",
      z: "DEATH MARK TURNS ONE KILL INTO TWO. VERY RUDE.",
    },
    tactics: "PICK ON SOMEONE ALONE. GO INVISIBLE, WALK BEHIND THEM, LEAP OR STAB, EXECUTE WHEN THEY'RE LOW. IF IT GOES WRONG, LEAVE IMMEDIATELY. A DEAD GRIM LOSES YOUR TEAM GOLD.",
    fear: "LANE TOWERS AND THORN. YOU ARE MADE OF PAPER AND BOTH OF THEM ARE MADE OF NOT-PAPER.",
  },
  summoner: {
    lore: "REMNIL STUDIED NECROMANCY BECAUSE THE LIBRARY HAD RUN OUT OF BOOKS ON GARDENING. HE TALKS TO HIS SKELETONS, NAMES THEM, AND IS VISIBLY UPSET WHEN THEY GET SMASHED. THEY DO NOT TALK BACK. YET.",
    role: "THE RANGED MIXED ATTACKER. SHOOTS FROM FAR, HEXES GROUPS, RAISES THE DEAD TO FIGHT FOR HIM.",
    a: ["A VOLLEY OF THREE BOLTS. THE THIRD IS A BIG ORB THAT SPLASHES AND SLOWS.", "BOLTS NO LONGER STAGGER HEROES, BUT THE ORB DOES. TIME THE THIRD SHOT FOR WHEN THEY CHARGE."],
    b: ["HEX. A CURSE CIRCLE THAT HURTS AND SLOWS. ANYONE WHO DIES WHILE HEXED GETS BACK UP ON YOUR SIDE.", "HEX A CROWD OF ENEMY TROOPS RIGHT BEFORE THEY DIE AND GROW YOUR ARMY FOR FREE."],
    r: ["SUMMON. TWO GRUNTS CLIMB OUT OF THE GROUND AND FIGHT FOR A WHILE.", "USE IT TO BLOCK A MELEE HERO CHASING YOU. SKELETONS ARE EXCELLENT SPEED BUMPS."],
    z: ["RAISE AN ARMY. A WHOLE SQUAD OF THE DEAD SHOWS UP AT ONCE.", "DROP IT IN THE MIDDLE OF A PUSH. A SURPRISE ARMY TURNS A FAIR FIGHT INTO A VERY UNFAIR ONE."],
    picks: {
      bonegolem: "ONE BIG BONE BRUTE INSTEAD OF TWO GRUNTS. IT TANKS A LOT AND STAYS LONGER.",
      wraiths: "THREE SKELETON ARCHERS INSTEAD OF TWO GRUNTS. MORE DAMAGE, LESS STANDING IN THE WAY.",
      gravepull: "HEX DRAGS PEOPLE TOGETHER AND LEAVES SPIKES. WITH BONE GOLEM IT ALSO STUNS.",
      cascade: "HEX FALLS THREE TIMES IN A LINE. WITH WRAITH ARCHERS EVERY HEX RAISES A GRUNT.",
      soulsiphon: "YOUR BOLTS HEAL YOU AND BUILD A SHIELD. MAKES YOU MUCH HARDER TO JUMP ON.",
      arcbolts: "BOLTS JUMP BETWEEN TARGETS. IT TURNS YOU INTO A TROOP SHREDDER.",
      legion: "A BIGGER ARMY FOR LONGER, AND YOUR HEX REACHES FURTHER. MORE FRIENDS, ALL DEAD.",
    },
    evo: {
      r: "TANK OR DAMAGE. THE GOLEM BLOCKS, THE WRAITHS SHOOT.",
      b: "HEX UPGRADES. BOTH HAVE A STRONG COMBO WITH ONE SUMMON, SO PICK THE MATCHING ONE.",
      a: "SURVIVE (SIPHON) OR SHRED (ARC BOLTS). IF PEOPLE KEEP DIVING YOU, TAKE SIPHON.",
      z: "LEGION. YOUR ARMY OF THE DEAD BECOMES A SLIGHTLY LARGER ARMY OF THE DEAD.",
    },
    tactics: "STAY BEHIND YOUR TROOPS AND SHOOT. HEX CLUMPS OF ENEMY SOLDIERS TO STEAL THEM. WHEN SOMEONE DIVES YOU, SUMMON BETWEEN YOU AND THEM, DODGE AWAY, AND KEEP SHOOTING.",
    fear: "GRIM APPEARING BEHIND YOU WITH NO WARNING. KEEP YOUR SUMMON FOR WHEN HE SHOWS UP.",
  },
  duelist: {
    lore: "FRANCOIS HAS BEEN IN 312 DUELS AND HAS WON ALL OF THEM, ACCORDING TO FRANCOIS. HE FIGHTS WITH ONE HAND BEHIND HIS BACK. THE OTHER HAND IS HOLDING A BAGUETTE. NOBODY KNOWS WHERE THE BAGUETTE GOES DURING THE FIGHT.",
    role: "THE ALL-ROUNDER. DECENT AT EVERYTHING, GREAT AT ONE-ON-ONE. REWARDS GOOD TIMING MORE THAN ANYONE.",
    a: ["THREE QUICK THRUSTS WITH A LUNGING FINISHER. CRITS A LOT.", "THE THRUSTS ARE NARROW BUT REACH FAR. POKE FROM THE EDGE OF THEIR RANGE."],
    b: ["LUNGE. A FAST DASH THROUGH THE FIRST FOE IN LINE.", "GOOD FOR CHASING, BETTER FOR DODGING THROUGH SOMEONE WHO EXPECTED YOU TO RUN AWAY."],
    r: ["PARRY. A SHORT GUARD WINDOW. IF THEY HIT YOU INSIDE IT, YOU COUNTER, STUN THEM AND RESET LUNGE.", "PARRY WHEN THEY START SWINGING, NOT WHEN THEY'RE HALFWAY THROUGH. LISTEN FOR THE WIND-UP."],
    z: ["BLADE FLURRY. A STORM OF STABS THAT HITS STUNNED FOES MUCH HARDER.", "PARRY, THEN FLURRY. THE COUNTER STUNS THEM AND THE FLURRY DOES THE REST."],
    picks: {
      riposte: "A WIDER PARRY THAT GIVES A SHIELD AND A HARDER COUNTER. FOR PEOPLE WHO LIKE TO WAIT.",
      volte: "PARRY BECOMES A SIDESTEP, AND YOUR NEXT ATTACK HITS MUCH HARDER. FOR PEOPLE WHO DON'T.",
      blinkstep: "LUNGE TWICE, AND A GHOST OF YOU LUNGES AGAIN. WITH VOLTE, SIDESTEPPING GIVES LUNGE BACK.",
      marked: "LUNGE MARKS FOES: YOUR WHOLE TEAM HITS THEM HARDER. WITH RIPOSTE, PARRIED FOES ARE MARKED TOO.",
      fleche: "A STRONGER FINISHER THAT SENDS A SLASH THROUGH A LINE. GOOD AGAINST TROOPS.",
      momentum: "EVERY HIT STACKS DAMAGE AND SPEED AND CUTS YOUR PARRY COOLDOWN. LONG FIGHTS BECOME YOURS.",
      thousandcuts: "MORE FLURRY, AND EVEN MORE AGAINST THE STUNNED. RIPOSTE INTO THIS IS NASTY.",
    },
    evo: {
      r: "PATIENT (RIPOSTE) OR SLIPPERY (VOLTE). BOTH ARE GREAT. ONE OF THEM SUITS YOU.",
      b: "LUNGE UPGRADES. BLINK STEP WANTS VOLTE, MARKED WANTS RIPOSTE.",
      a: "FLECHE FOR CLEARING TROOPS, MOMENTUM FOR LONG HERO FIGHTS.",
      z: "THOUSAND CUTS. MORE CUTS THAN A THOUSAND? NO, EXACTLY A THOUSAND. WE COUNTED.",
    },
    tactics: "FIGHT THE OTHER HERO, NOT THEIR ARMY. WAIT FOR THEM TO SWING, PARRY, PUNISH WITH FLURRY OR A FULL COMBO. IF THEY STOP SWINGING AT YOU, LUNGE THROUGH THEM AND MAKE THEM.",
    fear: "BEING SWARMED. PARRY ONLY STOPS ONE HIT, AND TEN GRUNTS HAVE TEN SWORDS.",
  },
  warden: {
    lore: "THORN IS A TREE. NOT A MAN DRESSED AS A TREE, NOT A TREE-SHAPED MAN. A TREE. HE GOT INVOLVED IN THE GRUDGE BECAUSE SOMEONE CHOPPED HIS COUSIN INTO A PALISADE. STIG STILL WON'T SAY WHERE HE GOT THE WOOD.",
    role: "THE KEEPER. A TANKY AREA CONTROLLER. WALLS OFF ROADS, SLOWS PEOPLE DOWN, SPEEDS FRIENDS UP AND HITS BUILDINGS HARDER THAN MOST.",
    a: ["TWO WIDE SWEEPS OF BARK. HITS EVERYTHING IN FRONT OF YOU.", "GREAT FOR CLEARING CLUMPS OF TROOPS. AIM AT THE MIDDLE OF THE CROWD."],
    b: ["LONG ARM SLAP. A RANGED BRANCH SWING THAT KNOCKS BACK AND STUNS BRIEFLY.", "SLAP PEOPLE OFF CLIFFS. IT'S NOT IN THE TOOLTIP BUT IT SHOULD BE."],
    r: ["STONE WALL. RAISES A WALL WITH SNARES AT BOTH ENDS. BLOCKS ROADS AND CHOKEPOINTS.", "WALL A NARROW GAP BEHIND A FLEEING HERO. THE SNARES WILL GET THEM."],
    z: ["BRAMBLES. A BIG FIELD OF THORNS: FOES ARE SLOWED AND HURT, ALLIES INSIDE MOVE FASTER.", "THROW IT UNDER A FIGHT AND STAND IN IT. YOUR WHOLE TEAM BECOMES QUICKER AND THEIRS SLOWER."],
    picks: {
      rootcage: "THE WALL BECOMES A ROOT TRAP YOU AIM. HOLDS A HERO IN PLACE FOR A GOOD WHILE.",
      rampart: "A BIGGER WALL THAT HEALS ALLIES NEXT TO IT. MAKE A FORT ANYWHERE.",
      graspingvine: "YOUR SLAP PULLS PEOPLE TO YOU AND STUNS THEM. WITH ROOT CAGE, YANKING A ROOTED FOE HURTS MORE.",
      whiplash: "YOUR SLAP HITS A WHOLE LINE AND EXPLODES. WITH LIVING RAMPART IT STUNS TOO.",
      thornguard: "HITS GROW A BARK SHIELD. VERY HARD TO KILL WHILE YOU'RE SWINGING.",
      overgrowth: "YOUR FINISHER ROOTS PEOPLE AND LEAVES BRAMBLES. EVERY COMBO BECOMES A TRAP.",
      ancientgrove: "BIGGER, LONGER BRAMBLES THAT ALSO HEAL ALLIES. A WHOLE FOREST OF BAD NEWS.",
    },
    evo: {
      r: "TRAP (ROOT CAGE) OR FORT (RAMPART).",
      b: "SLAP UPGRADES. GRASPING VINE GOES WITH ROOT CAGE, WHIPLASH WITH RAMPART.",
      a: "SURVIVE (THORNGUARD) OR CONTROL (OVERGROWTH).",
      z: "ANCIENT GROVE. IT'S BRAMBLES BUT WITH HEALING. GRANDMA'S RECIPE.",
    },
    tactics: "STAND BETWEEN YOUR BASE AND THEIRS. WALL THE ROADS, SLAP INTRUDERS, DROP BRAMBLES UNDER BIG FIGHTS. YOU'RE STRONG AGAINST BUILDINGS, SO WHEN YOU PUSH, GO STRAIGHT FOR THE TOWERS.",
    fear: "REMNIL AND STIG'S BALLISTA POKING FROM RANGE. YOU'RE SLOW TO CLOSE THE GAP.",
  },
};

const STAT_WORD: Record<string, string> = { low: "LOW", mid: "AVERAGE", high: "HIGH", sturdy: "STURDY", swift: "VERY FAST" };

function heroEntry(id: string): CodexEntry {
  const h = HEROES[id];
  const t = TEXT[id];
  const name = h.name.toUpperCase();
  const tal = TALENTS[id];
  const abil = (slot: "a" | "b" | "r" | "z", label: string): CodexPage => {
    const [text, tip] = t[slot];
    const call = h.abilities[slot].callout?.split("·")[0].trim();
    const cd = h.abilities[slot].cooldown;
    return { title: `${label}${call ? ` · ${call}` : ""}`, text: text + (cd && cd > 1 ? `  COOLDOWN ${cd}S.` : ""), tip, art: { kind: "shot", hero: id, slot } };
  };
  const evo = (slot: "r" | "b" | "a" | "z", level: number, label: string): CodexPage => {
    const list = tal[slot] ?? [];
    return {
      title: `LEVEL ${level} · ${label}`,
      text: t.evo[slot],
      art: { kind: "shot", hero: id, slot },
      picks: list.map((p) => ({ id: p.id, name: p.name, desc: t.picks[p.id] ?? p.desc, combo: p.combo })),
    };
  };
  return {
    cat: "CHAMPIONS",
    title: name,
    glyph: id === "warlord" ? "slam" : id === "engineer" ? "ballista" : id === "raider" ? "dash" : id === "summoner" ? "summon" : id === "duelist" ? "parry" : "zone",
    pages: [
      { title: `${name} · THE LEGEND`, text: t.lore, tip: `HEALTH ${STAT_WORD[h.health] ?? h.health} · SPEED ${STAT_WORD[h.speed] ?? h.speed} · DAMAGE ${STAT_WORD[h.damage] ?? h.damage}`, art: { kind: "portrait", hero: id } },
      { title: `${name} · ROLE`, text: t.role, tip: `FEARS: ${t.fear}`, art: { kind: "portrait", hero: id } },
      abil("a", "A · ATTACK"),
      abil("b", "B · SECONDARY"),
      abil("r", "R · SPECIAL"),
      abil("z", "Z · SUPER"),
      evo("r", 2, "SPECIAL EVOLVES"),
      evo("b", 3, "SECONDARY EVOLVES"),
      evo("a", 4, "ATTACK EVOLVES"),
      evo("z", 5, "SUPER EVOLVES"),
      { title: `${name} · HOW TO WIN`, text: t.tactics, art: { kind: "shot", hero: id, slot: "z" } },
    ],
  };
}

const MAP_DATA = import.meta.glob("../../data/maps/*.json", { eager: true, import: "default" }) as Record<string, { name: string }>;

export function buildCodex(mapNames: string[]): CodexEntry[] {
  const sc = U.waves.spawnCost;
  const st = S.types;
  const e = M.economy;
  const sh = M.arena.shop;
  const rel = M.arena.relic;
  const og = M.arena.ogre;
  const can = M.arena.cannon;
  const entries: CodexEntry[] = [
    {
      cat: "BASICS",
      title: "HOW TO FIGHT",
      glyph: "combo",
      pages: [
        { title: "HITTING THINGS", text: "PRESS A TO SWING. KEEP PRESSING TO CHAIN A COMBO, THE LAST HIT IS ALWAYS THE BIG ONE. HOLD A TO CHARGE A HEAVY HIT. B, R AND Z ARE YOUR ABILITIES. Z ONLY WORKS WHEN THE METER IS FULL, AND IT FILLS AS YOU DEAL AND TAKE DAMAGE.", tip: "HITTING SOMEONE FROM BEHIND DEALS EXTRA DAMAGE. SO DOES HITTING THEM WHILE THEY'RE STUNNED.", art: { kind: "seal", glyph: "combo" } },
        { title: "NOT GETTING HIT", text: "HOLD L TO BLOCK: HITS FROM THE FRONT BARELY HURT, BUT YOU MOVE SLOWLY. L + X DODGES, A QUICK ROLL WHERE NOTHING CAN TOUCH YOU. IT HAS A SHORT COOLDOWN, SO DON'T SPAM IT. L + A SHOVES PEOPLE AWAY AND STUNS THEM FOR A MOMENT.", tip: "A BLOCKER IS VERY ANNOYING. SHOVE THEM, OR WALK AROUND AND HIT THEIR BACK.", art: { kind: "seal", glyph: "parry" } },
        { title: "DYING", text: `YOU COME BACK AT YOUR KEEP AFTER A FEW SECONDS. EVERY DEATH COSTS YOUR TEAM ${e.loss.heroDeath} GOLD AND GIVES THE ENEMY A ${e.bounty.hero} GOLD BOUNTY, SO TRY NOT TO DO IT.`, tip: "IF YOU'RE BEHIND, YOU RESPAWN FASTER AND LOSE LESS GOLD. COMEBACKS ARE REAL.", art: { kind: "seal", glyph: "none", color: "#4a3a2a" } },
        { title: "CLIFFS AND HIGH GROUND", text: "YOU CAN DROP OFF A CLIFF, BUT YOU CAN'T CLIMB ONE. FIND THE RAMP. TROOPS SHOOTING UPHILL MISS MORE OFTEN, SO HIGH GROUND IS WORTH HOLDING.", tip: "GRIM IGNORES MOST OF THIS. HE CLIMBS LIKE A GOAT.", art: { kind: "seal", glyph: "peak" } },
      ],
    },
    {
      cat: "BASICS",
      title: "LEVELLING UP",
      glyph: "rally",
      pages: [
        { title: "EXPERIENCE", text: "YOU EARN EXPERIENCE BY HURTING HEROES, KILLING TROOPS AND BREAKING BUILDINGS, PLUS A SLOW TRICKLE JUST FOR BEING ALIVE. EACH LEVEL ALSO GIVES YOU A BIT MORE HEALTH AND DAMAGE.", tip: "FIGHTING THE OTHER HERO IS THE FASTEST WAY TO LEVEL. ALSO THE FASTEST WAY TO DIE.", art: { kind: "seal", glyph: "rally" } },
        { title: "EVOLUTIONS", text: "AT LEVELS 2, 3, 4 AND 5 ONE OF YOUR ABILITIES EVOLVES: SPECIAL (R), THEN SECONDARY (B), THEN ATTACK (A), THEN SUPER (Z). FOR EACH ONE YOU PICK ONE OF TWO VERSIONS WITH LEFT OR RIGHT ON THE ORDERS STICK.", tip: "THE CHOICE IS PERMANENT FOR THE MATCH. READ BOTH.", art: { kind: "seal", glyph: "works" } },
        { title: "SYNERGIES", text: "YOUR SECONDARY EVOLUTION ALWAYS HAS A BONUS IF IT MATCHES A CERTAIN SPECIAL EVOLUTION. THE CHAMPION PAGES IN THIS BOOK LIST EVERY PAIR. IN SHORT: DECIDE YOUR PLAN AT LEVEL 2 AND STICK TO IT AT LEVEL 3.", tip: "MIXING AND MATCHING STILL WORKS, YOU JUST MISS THE BONUS.", art: { kind: "seal", glyph: "hex" } },
      ],
    },
    {
      cat: "ARMY",
      title: "YOUR TROOPS",
      glyph: "banner",
      pages: [
        { title: "THREE KINDS OF SOLDIER", text: `GRUNTS (${sc.grunt} GOLD): CHEAP, QUICK, GOOD AT HACKING BRUTES APART. ARCHERS (${sc.ranged} GOLD): SHOOT FROM RANGE, SHRED GRUNTS. BRUTES (${sc.heavy} GOLD): BIG, SLOW, SMASH ARCHERS AND BUILDINGS.`, tip: "GRUNTS BEAT BRUTES. ARCHERS BEAT GRUNTS. BRUTES BEAT ARCHERS. A MIXED ARMY BEATS ANY SINGLE KIND.", art: { kind: "unit", type: "grunt" } },
        { title: "VETERANS", text: "TROOPS THAT GET KILLS RANK UP: VETERAN, ELITE, THEN HEROIC. EACH RANK HITS HARDER, HAS MORE HEALTH AND HEALS A BIT. HEROIC TROOPS SLOWLY REGENERATE.", tip: `KEEPING TROOPS ALIVE MATTERS. THE ARMY CAP IS ${U.popCap}, SO DON'T THROW THEM AWAY.`, art: { kind: "unit", type: "heavy" } },
      ],
    },
    {
      cat: "ARMY",
      title: "GIVING ORDERS",
      glyph: "rally",
      pages: [
        { title: "THE FOUR ORDERS", text: "FLICK THE ORDERS STICK (C, OR THE ARROW KEYS). UP: ATTACK, MARCH ON THE ENEMY KEEP. LEFT: FOLLOW YOU AROUND. RIGHT: DEFEND, GO HOME AND GUARD EVERY GATE. DOWN: HOLD, STAY WHERE YOU ARE.", tip: "D-PAD LEFT AND RIGHT PICK WHO OBEYS: EVERYONE, OR JUST GRUNTS, ARCHERS OR BRUTES.", art: { kind: "seal", glyph: "rally" } },
        { title: "WHEN TO USE WHAT", text: "ATTACK WHEN YOU HAVE A BIG ARMY. FOLLOW WHEN YOU WANT TO PUSH TOGETHER WITH YOUR HERO. DEFEND WHEN SOMEONE IS BREAKING INTO YOUR BASE: YOUR TROOPS SPLIT ACROSS EVERY ENTRANCE AND HUNT ANYTHING THAT GETS INSIDE. HOLD WHEN YOU WANT A WALL OF BODIES SOMEWHERE SPECIFIC.", tip: "ARCHERS ON HOLD BEHIND GRUNTS ON ATTACK IS A CLASSIC FOR A REASON.", art: { kind: "seal", glyph: "wall" } },
      ],
    },
    {
      cat: "ARMY",
      title: "OUTPOSTS",
      glyph: "castle",
      pages: [
        { title: "WHERE TROOPS COME FROM", text: `TROOPS ONLY COME FROM OUTPOSTS. BUILD THEM ON PADS WITH X: A BARRACKS MAKES GRUNTS, A RANGE MAKES ARCHERS, A FOUNDRY MAKES BRUTES. EACH COSTS ${st.barracks.cost} GOLD. EVERY ${U.waves.everySeconds} SECONDS EACH OUTPOST SENDS ITS SOLDIER, AND YOU PAY FOR EACH ONE AS IT COMES OUT.`, tip: "NO GOLD, NO TROOPS. IF YOUR OUTPOSTS GO QUIET, CHECK YOUR PURSE.", art: { kind: "seal", glyph: "castle" } },
        { title: "MIXED OUTPOSTS", text: `SOME FIELDS ARE TOO CRAMPED FOR SPECIALISTS. THERE YOU CAN ONLY BUILD A PLAIN OUTPOST, ${st.outpost.cost} GOLD, AND EVERY SOLDIER IT SENDS IS PICKED AT RANDOM: ABOUT ${Math.round((st.outpost.mix?.grunt ?? 0) * 100)}% GRUNTS, ${Math.round((st.outpost.mix?.ranged ?? 0) * 100)}% ARCHERS AND ${Math.round((st.outpost.mix?.heavy ?? 0) * 100)}% BRUTES. RIGHT NOW THAT'S THE RUINS.`, tip: "YOU DON'T GET TO CHOOSE. NEITHER DO THEY. IT'S VERY DEMOCRATIC.", art: { kind: "seal", glyph: "castle" } },
        { title: "UPGRADES AND FORWARD OUTPOSTS", text: `UPGRADE AN OUTPOST (Y AT ITS PAD, ${st.barracks.upgradeCost} GOLD) TO SEND TWO SOLDIERS AT A TIME, WITH BETTER STATS. OUTPOSTS ON FORWARD OR NEUTRAL PADS MAKE TOUGHER SOLDIERS, AND STANDING NEAR ONE HEALS YOU LIKE YOUR OWN TURF.`, tip: "A FORWARD OUTPOST IS A SECOND HOME. LOSE IT AND YOU'LL FEEL IT.", art: { kind: "seal", glyph: "banner" } },
      ],
    },
    {
      cat: "ARMY",
      title: "GOLD",
      glyph: "repair",
      pages: [
        { title: "MAKING IT", text: `YOU EARN ${e.income} GOLD A SECOND JUST FOR EXISTING. KILLS PAY BOUNTIES: ${e.bounty.hero} FOR A HERO, ${e.bounty.structure} FOR A BUILDING, A FEW COINS PER SOLDIER.`, tip: "IF YOU'RE BEHIND, YOU EARN MORE AND THEY EARN LESS FROM KILLING YOU.", art: { kind: "seal", glyph: "repair" } },
        { title: "LOSING IT", text: `EVERY TIME YOUR HERO DIES YOUR TEAM LOSES ${e.loss.heroDeath} GOLD. EVERY TOWER YOU LOSE COSTS ${e.loss.tower}. AND WHEN THE ENEMY FELLS ONE OF YOUR TOWERS, THEIR WHOLE ARMY RALLIES: +${pct(e.rally.damageMul)} DAMAGE AND +${pct(e.rally.speedMul)} SPEED FOR ${e.rally.seconds} SECONDS.`, tip: "THE SAME GOES FOR YOU. KNOCK A TOWER DOWN AND CHARGE WHILE THE RALLY LASTS.", art: { kind: "seal", glyph: "quake" } },
      ],
    },
    {
      cat: "BASE",
      title: "TOWERS",
      glyph: "turret",
      pages: [
        { title: "THE THREE TOWERS", text: `BUILD WITH Y AT A PAD. DAMAGE TOWER: SHOOTS BOLTS. CONTROL TOWER: PULSES AROUND ITSELF, SLOWS AND SHOVES. SUPPORT TOWER: HEALS FRIENDS AND MAKES THEM HIT HARDER. EACH COSTS ${st.damage.cost}, UPGRADES ${st.damage.upgradeCost}.`, tip: "THERE'S NO LIMIT. IF YOU HAVE THE PADS AND THE GOLD, BUILD.", art: { kind: "seal", glyph: "turret" } },
        { title: "WHO TOWERS SHOOT", text: "TOWERS SHOOT YOUR TROOPS FIRST. THEY ONLY SWITCH TO YOU IF YOU WALK IN WITH NO TROOPS AROUND, OR IF YOU HIT SOMETHING OF THEIRS NEAR THE TOWER.", tip: "NEVER DIVE A TOWER ALONE. WALK IN BEHIND YOUR SOLDIERS AND LET THEM SOAK THE BOLTS.", art: { kind: "seal", glyph: "shoot" } },
        { title: "LANE TOWERS", text: "TOWERS ON FORWARD AND NEUTRAL PADS ARE MUCH TOUGHER, HIT MUCH HARDER AND SLOW HEROES THEY SHOOT. YOU CAN'T JUST JOG PAST THEM. TOWERS INSIDE YOUR BASE ARE NORMAL ONES.", tip: "TAKE THE LANE TOWER FIRST, THEN THE ROAD IS OPEN.", art: { kind: "seal", glyph: "wall" } },
        { title: "RUBBLE", text: `A DESTROYED BUILDING LEAVES RUBBLE FOR ${S.rubbleSeconds} SECONDS. THE OWNER CAN'T REBUILD THERE UNTIL IT CLEARS, BUT THE ENEMY CAN BUILD STRAIGHT ON IT.`, tip: "STEAL THEIR PAD THE MOMENT IT FALLS.", art: { kind: "seal", glyph: "quake", color: "#6a6058" } },
      ],
    },
    {
      cat: "BASE",
      title: "KEEP AND SHOP",
      glyph: "castle",
      pages: [
        { title: "THE KEEP", text: "YOUR KEEP IS YOUR LIFE. LOSE IT AND YOU LOSE. IF TIME RUNS OUT, WHOEVER DID MORE DAMAGE TO THE OTHER KEEP WINS. YOUR KEEP HAS A WARD THAT SOAKS DAMAGE AT FIRST.", tip: "EVERY HIT ON THEIR KEEP COUNTS. EVEN ONE BRUTE SMACKING IT ADDS UP.", art: { kind: "seal", glyph: "castle" } },
        { title: "THE SHOP", text: `PRESS Y AT YOUR KEEP. BOMB (${sh.bomb.cost}): THROW IT, OR STICK IT TO A BUILDING. IT FLATTENS A TOWER AND DOES ${sh.bomb.coreDamage} TO A KEEP. SHIELD (${sh.ward.cost}): RESTORES YOUR KEEP'S WARD. CANNON (${sh.cannon.cost}): AIM ${sh.cannon.shots} SHELLS ANYWHERE ON THE FIELD.`, tip: "A BOMB THROWN INTO A CLUMP OF TROOPS DELETES THEM. THEY DON'T LIKE THAT.", art: { kind: "seal", glyph: "trap" } },
        { title: "RECALL", text: "AWAY FROM YOUR KEEP, PRESS Y TO RECALL: STAND STILL FOR 6 SECONDS AND YOU'RE TELEPORTED HOME. MOVING, ATTACKING OR GETTING HIT CANCELS IT. ONCE PER LIFE.", tip: "RECALL THE MOMENT YOU SEE SOMEONE SNEAKING INTO YOUR BASE, NOT WHEN THE KEEP IS ON FIRE.", art: { kind: "seal", glyph: "leap" } },
      ],
    },
    {
      cat: "BASE",
      title: "BUILDING",
      glyph: "works",
      pages: [
        { title: "PADS", text: `EVERY BUILDING GOES ON A PAD. HOME PADS ARE IN YOUR BASE, FORWARD PADS ARE OUT IN YOUR HALF, NEUTRAL PADS ARE IN THE MIDDLE. BUILDING TAKES ABOUT ${S.buildSeconds} SECONDS, FASTER WITH TWO HEROES OR WITH TROOPS NEARBY.`, tip: "BUILT HALF A TOWER AND RAN? IT KEEPS BUILDING SLOWLY ON ITS OWN WHEN TROOPS ARE CLOSE.", art: { kind: "seal", glyph: "pad" } },
        { title: "WHAT TO BUILD FIRST", text: "ONE OUTPOST FOR TROOPS, THEN A TOWER ON YOUR FORWARD PAD, THEN A SECOND OUTPOST. AFTER THAT, UPGRADE WHAT YOU HAVE BEFORE BUILDING NEW STUFF IN THE MIDDLE.", tip: "STIG BUILDS EVERYTHING CHEAPER. IF YOU HAVE A STIG, LET HIM BUILD.", art: { kind: "seal", glyph: "works" } },
      ],
    },
    {
      cat: "ARENA",
      title: "THE GRUDGE",
      glyph: "hex",
      pages: [
        { title: "THE RELIC", text: `AFTER ${rel.firstSeconds} SECONDS THE GRUDGE APPEARS IN THE MIDDLE OF THE FIELD. PICK IT UP AND CARRY IT HOME. YOU'RE SLOWER WHILE CARRYING AND CAN'T ATTACK.`, tip: "SEND SOMEONE WITH ESCORTS. A LONE CARRIER IS A GIFT.", art: { kind: "seal", glyph: "hex" } },
        { title: "ENSHRINING IT", text: `STAND AT A TOWER, OUTPOST OR YOUR KEEP FOR ${rel.enshrineSeconds} SECONDS TO ENSHRINE IT. A TOWER SHRINE HITS HARDER AND FURTHER, AN OUTPOST SHRINE SENDS EXTRA, TOUGHER TROOPS, THE KEEP SHRINE REGROWS ITS WARD. ANY SHRINE GIVES ${pct(rel.incomeMul)} MORE GOLD.`, tip: `THE ENEMY CAN STEAL IT BACK BY STANDING ON IT FOR ${rel.stealSeconds} SECONDS. GUARD YOUR SHRINE.`, art: { kind: "seal", glyph: "castle", color: "#c8a020" } },
      ],
    },
    {
      cat: "ARENA",
      title: "THE OGRE",
      glyph: "slam",
      pages: [
        { title: "BIG, GREEN, NEUTRAL", text: `AFTER ${og.firstSeconds} SECONDS AN OGRE WAKES UP SOMEWHERE ON THE FIELD. ${og.hp} HEALTH AND AN ENORMOUS CLUB. HE HATES EVERYONE EQUALLY, WHICH IS VERY FAIR OF HIM.`, tip: "DON'T FIGHT HIM AT THE SAME TIME AS THE ENEMY. LET THEM WEAKEN HIM FIRST.", art: { kind: "unit", type: "ogre" } },
        { title: "THE BLESSING", text: `KILL HIM AND YOUR TEAM GETS ${og.bounty} GOLD AND A BLESSING FOR ${og.blessSeconds} SECONDS: MORE DAMAGE, MORE SPEED, A BIG CHUNK OF EXPERIENCE AND SOME HEALING. HE COMES BACK ${og.respawnSeconds} SECONDS LATER.`, tip: "A BLESSED PUSH RIGHT AFTER THE OGRE IS THE STRONGEST MOVE IN THE GAME.", art: { kind: "seal", glyph: "rally", color: "#2a7a20" } },
      ],
    },
    {
      cat: "ARENA",
      title: "THE CANNON",
      glyph: "ballista",
      pages: [
        { title: "INCOMING", text: `FROM ${can.firstSeconds} SECONDS ON, EVERY ${can.everySeconds} SECONDS OR SO, A WILD CANNON SHELLS THE FIELD. YOU GET A WARNING CIRCLE A MOMENT BEFORE EACH SHELL LANDS. ${can.damage} TO TROOPS AND HEROES, ${can.structureDamage} TO BUILDINGS, NEVER THE KEEP.`, tip: "WALK OUT OF THE CIRCLES. THIS IS ALL OF THE ADVICE.", art: { kind: "seal", glyph: "ballista" } },
      ],
    },
    {
      cat: "ARENA",
      title: "THE HERALD",
      glyph: "banner",
      pages: [
        { title: "THE COMMANDER", text: "IN 2V2 THE THIRD AND FOURTH SEATS CAN BE HERALDS: A SKINNY FELLOW WITH A BIG FLAG WHO RUNS THE ARMY. HE SEES THE WHOLE ARMY AT ONCE, D-PAD UP SENDS A GROUP TO SIEGE, D-PAD DOWN MAKES THEM HOLD, AND HIS ORDERS BEAT HIS PARTNER'S. B PLANTS A WAR BANNER TROOPS GATHER AT, R BLOWS A HORN THAT SPEEDS THEM UP, Z HEALS AND GUARDS EVERYONE NEARBY.", tip: "HE HAS NO TALENTS. HE HAS AN ARMY. THAT'S BETTER, PROBABLY.", art: { kind: "seal", glyph: "banner" } },
        { title: "FORMATIONS AND SUPPLY", text: "THE HERALD DOESN'T BLOCK, SO L CHANGES THE ARMY'S FORMATION: LOOSE, COLUMN (SINGLE FILE, FOR BRIDGES AND FORDS), LINE (TWO RANKS FACING THE ENEMY, BRUTES IN FRONT, ARCHERS BEHIND, STAY PUT) OR WEDGE (A V THAT CHARGES FURTHER). IT SHAPES TROOPS THAT HOLD OR FOLLOW. HIS RALLY ALSO HALVES HIS PARTNER'S B AND R COOLDOWNS, WHEREVER THEY ARE, AND INSIDE HIS WAR BANNER HIS HOUSE CAN USE THE SHOP AND BUILD ON ANY PAD IN THE BANNER'S REACH.", tip: "PLANT THE BANNER NEXT TO A FAR PAD. NOW YOUR PARTNER CAN BUY BOMBS IN THE MIDDLE OF THE MAP. THIS IS WHY YOU BROUGHT A FLAG.", art: { kind: "seal", glyph: "rally" } },
        { title: "TAKE UP THE BANNER", text: `IN A 2V2 WITH NO HERALDS, HOLD X AWAY FROM A PAD FOR ${M.arena.morph?.holdSeconds ?? 0.6} SECONDS AND YOUR CHAMPION BECOMES THE HERALD: PLAIN, NO LEVELS, NO TALENTS, BUT IN CHARGE OF THE ARMY. ONE HERALD PER HOUSE. YOU STAY THAT WAY UNTIL YOU DIE AND COME BACK AS YOURSELF, OR HOLD X AT YOUR KEEP TO TURN BACK FOR ${M.arena.morph?.revertCost ?? 50} GOLD.`, tip: "FOR WHEN THE ARMY NEEDS A BABYSITTER MORE THAN THE FIGHT NEEDS YOU.", art: { kind: "seal", glyph: "rally" } },
      ],
    },
    {
      cat: "ARENA",
      title: "FREE FOR ALL",
      glyph: "banner",
      pages: [
        { title: "FOUR HOUSES", text: `SOME FIELDS HAVE FOUR KEEPS: BLUE, RED, YELLOW AND GREEN. EVERY HOUSE GETS ONE CHAMPION, UP TO ${U.popCap} SOLDIERS AND ZERO FRIENDS. EVERY PAD OUTSIDE THE KEEPS IS NEUTRAL, SO WHOEVER BUILDS ON IT FIRST OWNS IT, UNTIL SOMEONE ELSE DISAGREES WITH A BRUTE.`, tip: `THE GRUDGE STILL WAKES IN THE MIDDLE AFTER ${rel.firstSeconds} SECONDS. ALL FOUR HOUSES CAN SEE IT. ALL FOUR WANT IT. THIS GOES ABOUT AS WELL AS YOU'D THINK.`, art: { kind: "seal", glyph: "banner", color: "#2a8a3a" } },
        { title: "LAST HOUSE STANDING", text: "LOSE YOUR KEEP AND YOUR HOUSE IS OUT. YOUR TOWERS CRUMBLE, YOUR SOLDIERS WANDER HOME AND YOUR CHAMPION STAYS DOWN, SULKING. THE LAST HOUSE WITH A KEEP WINS. IF THE BELL TOLLS FIRST, THE HOUSE STILL STANDING THAT DID THE MOST DAMAGE TO OTHER KEEPS TAKES IT.", tip: `TWO HOUSES FIGHTING IS GREAT NEWS FOR THE OTHER TWO. A FALLEN CHAMPION STILL PAYS ${e.bounty.hero} GOLD TO WHOEVER DID IT, SO EVERYONE IS ALWAYS LOOKING AT YOU.`, art: { kind: "seal", glyph: "castle", color: "#c89a14" } },
      ],
    },
  ];
  const md = (name: string) => Object.values(MAP_DATA).find((m) => m.name === name) as Record<string, any> | undefined;
  const cr = md("Grudgeholm Crossing")?.mist ?? {};
  const ru = md("Grudgekeep Ruins")?.lantern ?? {};
  const fc = md("Frostcross Summit")?.avalanche ?? {};
  const ga = md("Bellwick Gardens") ?? {};
  const gg = ga.gates ?? {};
  const gf = ga.fountain ?? {};
  const sh2 = md("Grudgetide Shoals")?.tide ?? {};
  const MAP_TEXT: Record<string, { glyph: string; text: string; tip: string; mech?: { title: string; text: string; tip: string } }> = {
    "Grudgeholm Crossing": {
      glyph: "river",
      text: "A LONG FIELD SPLIT BY TWO RIVER CHANNELS. THE MIDDLE ISLAND HOLDS THE NEUTRAL PADS AND THE FORDS ARE SLOW TO CROSS. EACH KEEP HAS A NORTH GATE, A SOUTH GATE AND A BRIDGE TO THE EAST.",
      tip: "THE FORDS ARE THE KILLING GROUND. FIGHT ON THE ISLAND, NOT IN THE WATER.",
      mech: {
        title: "RIVER MIST",
        text: `EVERY ${cr.everySeconds ?? 75} SECONDS OR SO A MIST ROLLS DOWN BOTH RIVERS, SITS THERE FOR ABOUT ${cr.holdSeconds ?? 16} SECONDS LOOKING MYSTERIOUS, THEN WANDERS OFF SOUTH. ANYTHING IN THE MIST IS HIDDEN, JUST LIKE TALL GRASS: TOWERS CAN'T SEE IN, AND WHOEVER SWINGS FIRST OUT OF IT GETS THE AMBUSH BONUS.`,
        tip: "THE FORDS ARE NOW ALSO THE HIDING GROUND. WALK INTO THE MIST CAREFULLY. SOMETHING IN THERE IS WAITING TO HIT YOU, AND IT MIGHT BE A TREE.",
      },
    },
    "Grudgekeep Ruins": {
      glyph: "castle",
      text: "A SQUARE OF OLD WALLS AND PITS, MIRRORED CORNER TO CORNER. EACH KEEP HAS A FRONT GATE TOWARD THE CENTRE AND A BACK GATE IN THE SIDE. THE OTHER TWO CORNERS ARE OLD GRAVEYARDS NOBODY VISITS. THERE'S SO LITTLE ROOM THAT EVERY OUTPOST HERE IS A MIXED ONE: YOU BUILD IT, IT DECIDES WHO TO SEND.",
      tip: "THE BACK GATE IS EASY TO FORGET. SO IS THE GRIM WALKING THROUGH IT.",
      mech: {
        title: "THE BONE LANTERN",
        text: `EVERY ${ru.everySeconds ?? 60} SECONDS SOMETHING IN THE PITS WAKES UP AND A BONE LANTERN FLOATS OUT, THEN DRIFTS OFF TO THE NEAREST EMPTY GRAVEYARD CORNER TO SULK FOR ${ru.restSeconds ?? 25} SECONDS. THE FIRST CHAMPION TO TOUCH IT IS HAUNTED FOR ${ru.hauntSeconds ?? 20} SECONDS: ${Math.round(((ru.damageMul ?? 1.3) - 1) * 100)}% MORE DAMAGE AND ${Math.round(((ru.speedMul ?? 1.15) - 1) * 100)}% MORE SPEED. THE DEAD DO NOT CHECK WHICH SIDE YOU ARE ON.`,
        tip: "YOU CAN GRAB IT WHILE IT'S STILL DRIFTING. IF YOU WAIT FOR IT IN THE CORNER, SO WILL THE OTHER CHAMPION, AND NOW THERE ARE TWO OF YOU IN A GRAVEYARD.",
      },
    },
    "Grudgetide Shoals": {
      glyph: "tide",
      text: "TWO ISLAND KEEPS ON A MUD FLAT. EACH HOUSE HAS ITS OWN DRY STONE CAUSEWAY ON ITS OWN FLANK. THE KEEPS ARE ON CLIFFS: YOU CAN DROP OFF THEM BUT NOT CLIMB BACK UP.",
      tip: "WEAR BOOTS. NOT THAT YOU CAN.",
      mech: {
        title: "THE TIDE",
        text: `EVERY ${(sh2.lowSeconds ?? 40) + (sh2.highSeconds ?? 30)} SECONDS THE TIDE COMES IN AND THE FLATS FLOOD FOR ${sh2.highSeconds ?? 30} SECONDS, SLOWING EVERYONE ON THEM. THEN IT GOES BACK OUT, AS TIDES DO.`,
        tip: "PUSH AT LOW TIDE. AT HIGH TIDE, STICK TO THE CAUSEWAYS AND ISLETS.",
      },
    },
    "Frostcross Summit": {
      glyph: "peak",
      text: "A FREE FOR ALL FIELD. FOUR KEEPS SIT AT THE FEET OF A FROZEN CROSS, WITH THE GRUDGE UP ON THE SUMMIT IN THE MIDDLE. BETWEEN THE ARMS ARE DEEP ICY BOWLS, CROSSED BY NARROW ROCK CAUSEWAYS THAT LINK EACH KEEP TO ITS NEIGHBOURS. THE OGRE LIVES ON THOSE.",
      tip: "YOUR NEIGHBOURS ARE CLOSER THAN THE HOUSE ACROSS THE PEAK. SO ARE YOU, TO THEM.",
      mech: {
        title: "AVALANCHE",
        text: `EVERY ${fc.everySeconds ?? 38} SECONDS ONE ARM RUMBLES FOR ${fc.warnSeconds ?? 6} SECONDS, THEN A WALL OF SNOW COMES DOWN IT FROM THE SUMMIT TOWARD THE KEEP. CHAMPIONS TAKE ${fc.heroDamage ?? 140} DAMAGE AND GET SHOVED; SOLDIERS LOSE ${Math.round((fc.unitDamage ?? 0.75) * 100)}% OF THEIR HEALTH. BUILDINGS ARE FINE. THE SNOW STAYS FOR ${fc.driftSeconds ?? 14} SECONDS AND SLOWS EVERYONE WADING THROUGH IT. IT GOES ROUND THE ARMS CLOCKWISE.`,
        tip: "WHEN THE SNOW RUMBLES, GET OUT OF THE LANE. IF YOU CAN COUNT, YOU KNOW WHICH LANE IS NEXT.",
      },
    },
    "Bellwick Gardens": {
      glyph: "bell",
      text: "A FREE FOR ALL FIELD. FOUR KEEPS IN THE CORNERS OF A VERY POSH WALLED GARDEN. A GRAVEL AVENUE RUNS FROM EACH KEEP PAST A ROUNDABOUT TOWER TO THE COURT IN THE MIDDLE. EVERYTHING ELSE IS HEDGES.",
      tip: "THE AVENUE NEVER CLOSES. THE HEDGES NEVER OPEN. EVERYTHING IN BETWEEN DEPENDS ON THE BELLS.",
      mech: {
        title: "BELLS AND THE FOUNTAIN",
        text: `EVERY ${gg.everySeconds ?? 40} SECONDS THE BELLS RING AND THE IRON GATES SWAP: EITHER THE OUTER GATES NEAR THE KEEPS ARE OPEN, OR THE GATES INTO THE COURT AND THE MIDDLE OF THE BORDERS. THE GRUDGE SITS IN A FOUNTAIN. CHAMPIONS WADING IN THE BASIN HEAL ${gf.heal ?? 32} HEALTH A SECOND.`,
        tip: "THE FOUNTAIN HEALS EVERYONE. THAT INCLUDES THE THREE PEOPLE TRYING TO DROWN YOU IN IT.",
      },
    },
  };
  mapNames.forEach((name, index) => {
    const m = MAP_TEXT[name] ?? { glyph: "river", text: "A FIELD OF BATTLE. IT HAS GRASS ON IT.", tip: "WIN." };
    const pages: CodexEntry["pages"] = [{ title: name.toUpperCase(), text: m.text, tip: m.tip, art: { kind: "map", index } }];
    if (m.mech) pages.push({ title: m.mech.title, text: m.mech.text, tip: m.mech.tip, art: { kind: "seal", glyph: m.glyph } });
    entries.push({ cat: "FIELDS", title: name.toUpperCase().replace(/^GRUDGE\w*\s*/, ""), glyph: m.glyph, pages });
  });
  const heroes = Object.keys(TEXT).filter((h) => HEROES[h]);
  return [...heroes.map(heroEntry), ...entries];
}
