// Codex content: builds the CODEX entries (champions with one page per ability and its evolutions, the Herald,
// army, buildings and towers, map events, maps, the Grudge relic, tips) from the game data JSON plus the
// hand-written text below. Pages carry their art: a portrait, unit, map or seal, or a live demo ("shot" = one
// hero ability, "scene" = a scripted situation) that app/demo.ts plays in the page's window.
import heroJson from "../../data/heroes.json";
import talentJson from "../../data/talents.json";
import unitJson from "../../data/units.json";
import structJson from "../../data/structures.json";
import matchJson from "../../data/match.json";

const COMBOS: Record<string, [string, string, string, "a" | "b" | "r" | "z"]> = {
  warlord: [
    "HEAVE",
    "NEXT TO A STUNNED FOE (HERO OR SOLDIER), PRESS L+A. THE WARLORD HOISTS THEM OVER HIS HEAD AND HURLS THEM TEN PACES THE WAY YOUR STICK POINTS. THEY CRASH DOWN FOR BIG DAMAGE, STAY STUNNED, AND SPLASH ANYONE THEY LAND ON.",
    "GROUND SLAM STUNS: SLAM, THEN HEAVE THEM INTO YOUR TOWERS, YOUR SOLDIERS, OR OFF A CLIFF.",
    "a",
  ],
  warden: [
    "ARM SHOVE",
    "WHILE YOUR LONG ARM SLAP IS STILL STRETCHED OUT, PRESS L+A. EVERYTHING ALONG THE ARM GETS SHOVED HARD AWAY FROM YOU AND STUNNED.",
    "PEEL A DIVER OFF YOUR BACK, OR SLAP SOMEONE OFF A BRIDGE AND SHOVE THEM INTO THE WATER.",
    "b",
  ],
  engineer: [
    "RAMP JUMP",
    "STANDING ON YOUR SIEGE RAMP, DODGE (L+X) TOWARD WHERE YOU WANT TO GO. STIG LAUNCHES OFF THE RAMP IN A LONG JUMP, CLEAR OVER WALLS.",
    "BUILD THE RAMP FACING THEIR KEEP WALL, THEN JUMP STRAIGHT INTO THEIR BASE. OR FACING HOME, AS AN ESCAPE HATCH.",
    "r",
  ],
  summoner: [
    "HEX SWAP",
    "WHILE AN ENEMY CHAMPION YOU'VE HEXED IS WITHIN 10M, DODGE (L+X) AND YOU SWAP PLACES WITH THEM. THEY'RE STUNNED FOR A MOMENT WHERE YOU WERE STANDING. HEXED SOLDIERS DON'T COUNT.",
    "WHEN SOMEONE DIVES YOU, HEX THEM, THEN SWAP: THEY'RE LEFT IN THE MIDDLE OF YOUR SKELETONS.",
    "b",
  ],
  duelist: [
    "RIPOSTE WHIRL",
    "RIGHT AFTER A SUCCESSFUL PARRY, PRESS A. FRANCOIS SPINS A FULL CIRCLE, HITTING EVERYTHING AROUND HIM, NOT JUST THE ATTACKER.",
    "YOUR ANSWER TO A MOB OF SOLDIERS: PARRY THE FIRST ONE, THEN SPIN.",
    "r",
  ],
  marksman: [
    "SKYSHOT",
    "WHILE PIP IS HANGING ON TO SOMEONE WITHIN 14M, DODGE (L+X). WREN BACKFLIPS 4M AWAY FROM THEM AND, BEFORE HER BOOTS TOUCH THE GRASS, PUTS A GUARANTEED CRITICAL ARROW INTO PIP'S PREY.",
    "THE ANSWER TO ANYONE WHO GETS CLOSE: SEND PIP, LET THEM COME, THEN FLIP AWAY AND SHOOT THEM IN THE FACE ON THE WAY.",
    "b",
  ],
  friar: [
    "KEG ROCKET",
    "STANDING IN YOUR OWN ALE PUDDLE, DODGE (L+X). MADDOCK HOPS ON A KEG AND ROLLS FLAT OUT ABOUT 10M, BOWLING FOES ASIDE AND LEAVING A SHORT TRAIL OF HEALING ALE. THE TRAIL DOESN'T COUNT AS A PUDDLE, SO NO ENCORES.",
    "THROW A HEALING KEG AT YOUR FEET AS A LAUNCH PAD. IT'S AN ESCAPE, A CHASE, AND A VERY UNDIGNIFIED ENTRANCE.",
    "b",
  ],
  harpooner: [
    "BELLY SLIDE",
    "TADWICK'S DODGE (L+X) IS A BELLY SLIDE: LONGER AND LOWER THAN A ROLL, AND IT LEAVES A PUDDLE WHERE HE TOOK OFF FOR 3S. A WET FOE WHO STEPS IN IT SLIPS AND IS STUNNED FOR A MOMENT.",
    "HARPOON THEM (NOW THEY'RE WET), THEN SLIDE AWAY ACROSS THEIR PATH. IF THEY CHASE YOU, THEY GO DOWN.",
    "a",
  ],
  scribe: [
    "PAGE GUST",
    "DODGE (L+X) AND HOLLIN READS A PAGE ALOUD: A GUST SHOVES EVERY FOE NEXT TO HER AWAY AND CARRIES HER A LONG WAY BACKWARDS (OR THE WAY YOUR STICK POINTS), STILL FACING THE FIGHT.",
    "GUST AWAY FROM A DIVER, THEN TURN AND PUT A CHARGED INK BOLT IN THEIR FACE. THEY HAVE TO WALK THROUGH YOUR PAPER STORM TO GET BACK TO YOU.",
    "r",
  ],
  wreckwitch: [
    "CHAIN SWING",
    "WITHIN 5.5M OF A BUILDING, TREE, ROCK, POST, STATUE OR WALL, HOLD DODGE (L+X). RINGS MARK WHAT YOU CAN HOOK: POINT THE STICK TO PICK ONE, AND THE ARC SHOWS WHERE YOU'LL LAND. LET GO AND MOTHER KELP HOOKS HER ANCHOR ROUND IT AND SWINGS TO ITS FAR SIDE, WHACKING ANYONE IN HER PATH. KEEP HOLDING AND SHE HOPS ON, PIVOT TO PIVOT TOWARD YOUR STICK, UP TO 5 SWINGS (THEN A 4S REST). SHE CAN'T BE HIT WHILE SHE SWINGS. A TAP IS STILL A PLAIN ROLL.",
    "FIGHT NEXT TO A TOWER OR A TREE. WHEN THEY CHASE YOU ROUND IT, SWING THE OTHER WAY AND COME BACK BEHIND THEM.",
    "b",
  ],
  architect: [
    "OWL HOP",
    "DODGE (L+X) AND HOOT FLAPS INSTEAD OF ROLLING: WITHIN 6M OF HIS LOOKOUT HE HOPS STRAIGHT BACK UP ONTO IT, NEXT TO A LEDGE A STEP HIGHER HE HOPS UP THE LEDGE, AND IN FRONT OF ONE OF HIS SNOW FORTS HE HOPS CLEAN OVER IT. HE NEVER TAKES FALL DAMAGE EITHER: HE'S AN OWL.",
    "GOT KNOCKED OFF THE PERCH? HOP RIGHT BACK. CHASED? PUT A FORT BETWEEN YOU AND HOP OVER IT.",
    "r",
  ],
  vintner: [
    "ANVIL CURL",
    "DODGE (L+X): INSTEAD OF A ROLL, HOGSHEAD DROPS INTO A SHORT LOW CROUCH AND CURLS UP BEHIND THE ANVIL ON HIS BACK, ENDING WITH HIS BACK TO THE NEAREST ENEMY CHAMPION. FOR ABOUT A SECOND AFTER, ANYTHING THAT HITS HIM FROM BEHIND BOUNCES OFF THE ANVIL FOR NEXT TO NOTHING.",
    "CURL WHEN WREN DRAWS OR REMNIL CASTS. THE ARROW MEETS IRON, NOT BOAR. IT'S SHORTER THAN A ROLL, SO IT'S A SHELL, NOT AN ESCAPE.",
    "b",
  ],
  rider: [
    "BUZZ STRAFE",
    "BRAMBLE DOESN'T ROLL. HER DODGE (L+X) IS MEAD BUZZING SIDEWAYS, A LITTLE FURTHER THAN A ROLL, WHILE BRAMBLE KEEPS FACING THE WAY SHE WAS. NOTHING TOUCHES HER WHILE SHE BUZZES.",
    "BUZZ AROUND A SWING AND HIT BACK STRAIGHT AWAY, OR STRAFE WHILE HOLDING A HONEY FLING SO IT STAYS POINTED AT THEM.",
    "a",
  ],
  herald: [
    "BANNER VAULT",
    "DODGE (L+X) TOWARD YOUR PLANTED BANNER WHEN IT'S 3 TO 13M AWAY AND THE HERALD VAULTS STRAIGHT TO IT.",
    "PLANT THE BANNER SOMEWHERE SAFE BEFORE THINGS GO WRONG. IT'S YOUR WAY OUT.",
    "b",
  ],
};

const SPEC_TIPS: Record<string, string> = {
  ballista: "PUT IT WHERE THEY COME AT YOU IN A LINE: A BRIDGE, A RAMP, A ROAD.",
  firepot: "SOLDIERS STANDING IN THE FIRE KEEP BURNING. GREAT WHERE THEY BUNCH UP.",
  volley: "THE ANSWER TO GRIM. HE CAN'T SNEAK PAST SOMETHING THAT SEES HIM.",
  frost: "FROZEN SOLDIERS DON'T HIT BACK. YOUR TROOPS GET FREE SWINGS.",
  storm: "THE STUN HITS CHAMPIONS TOO. FIGHT UNDER IT AND THEY CAN'T ESCAPE.",
  well: "PAIR IT WITH A FIREPOT OR A BALLISTA NEARBY. EVERYTHING ENDS UP IN ONE PILE.",
};

export type CodexArt =
  | { kind: "shot"; hero: string; slot: "a" | "b" | "r" | "z" }
  | { kind: "portrait"; hero: string }
  | { kind: "map"; index: number }
  | { kind: "seal"; glyph: string; color?: string }
  | { kind: "unit"; type: string }
  | { kind: "scene"; scene: string };

export interface CodexPick {
  id: string;
  name: string;
  desc: string;
  combo?: string;
}

export interface CodexPage {
  title: string;
  text: string;
  art: CodexArt;
  tip?: string;
  picks?: CodexPick[];
}

export interface CodexEntry {
  cat: string;
  title: string;
  glyph: string;
  pages: CodexPage[];
}

type Ability = { kind: string; callout?: string; cooldown?: number };
type Hero = {
  name: string;
  health: string;
  speed: string;
  damage: string;
  abilities: Record<"a" | "b" | "r" | "z", Ability>;
};
type Talent = { id: string; name: string; desc: string; combo?: string };

const HEROES = (heroJson as unknown as { heroes: Record<string, Hero> }).heroes;
const TALENTS = (talentJson as unknown as { heroes: Record<string, Record<"r" | "b" | "a" | "z", Talent[]>> }).heroes;
const U = unitJson as unknown as {
  waves: { everySeconds: number; spawnCost: Record<string, number> };
  types: Record<string, { hp: number; bounty: number }>;
  popCap: number;
};
const S = structJson as unknown as {
  types: Record<
    string,
    {
      name: string;
      cost: number;
      upgradeCost: number;
      mix?: Record<string, number>;
      cadence?: number;
      specCost?: number;
      specs?: { id: string; name: string; blurb: string }[];
    }
  >;
  buildSeconds: number;
  rubbleSeconds: number;
};
const M = matchJson as unknown as {
  rout?: { keepFrac: number; from?: number };
  economy: {
    start: number;
    income: number;
    grain?: { base: number; perLevel: number[]; surplus?: number };
    padIncome?: Record<string, number>;
    loss: { heroDeath: number; tower: number };
    rally: { seconds: number; damageMul: number; speedMul: number };
    bounty: { hero: number; structure: number };
  };
  arena: {
    shop: {
      bomb: { cost: number; coreDamage: number };
      ward: { cost: number; cooldown: number };
      cannon: { cost: number; shots: number };
    };
    relic: { firstSeconds: number; enshrineSeconds: number; stealSeconds: number; incomeMul: number };
    ogre: { firstSeconds: number; hp: number; bounty: number; blessSeconds: number; respawnSeconds: number };
    cannon: { firstSeconds: number; everySeconds: number; damage: number; structureDamage: number };
    morph?: { holdSeconds: number; channelSeconds: number; revertCost: number };
  };
};
const pct = (m: number) => `${Math.round((m - 1) * 100)}%`;

interface HeroText {
  lore: string;
  role: string;
  a: [string, string];
  b: [string, string];
  r: [string, string];
  z: [string, string];
  picks: Record<string, string>;
  evo: Record<"r" | "b" | "a" | "z", string>;
  tactics: string;
  fear: string;
}

const TEXT: Record<string, HeroText> = {
  warlord: {
    lore: "BORN IN A TENT, RAISED BY A WAR DRUM, NAMED BY A GOAT. HE HAS NEVER LOST AN ARGUMENT, MOSTLY BECAUSE HE ANSWERS EVERY ONE BY HITTING THE FLOOR VERY HARD. HIS BRUTES LOVE HIM. NOBODY HAS ASKED WHY.",
    role: "THE HEAVY. SLOW TO START, MISERABLE TO STAND NEXT TO. HIS BRUTES COME OUT TOUGHER THAN ANYONE ELSE'S. OUT OF A FIGHT FOR A FEW SECONDS HE MARCHES A THIRD FASTER. UNBREAKABLE: WITH TWO ENEMY CHAMPIONS ON HIM HE TAKES 40% LESS FROM THEM.",
    a: [
      "TWO BIG SWINGS. THE SECOND IS A HUGE SWEEPING SWIPE THAT HITS EVERYONE AROUND HIS FRONT AND SENDS THEM BACKWARDS.",
      "THE FINISHER KNOCKS FOES OUT OF REACH. IF YOU WANT TO KEEP HITTING, WALK AFTER THEM.",
    ],
    b: [
      "GROUND SLAM. A RING OF PAIN THAT SLOWS AND COWS EVERYONE IN IT, SO THEY HIT SOFTER FOR A MOMENT.",
      "SLAM FIRST, QUAKE SECOND. EARTHQUAKE HITS SLOWED FOES HARDER.",
    ],
    r: [
      "WAR CRY. YOU AND EVERY ALLY NEARBY HIT HARDER AND MOVE FASTER FOR 6S (TROOPS COUNT). IN DEATHMATCH THE ROAR ALSO GIVES YOU A SHIELD WORTH 10% OF YOUR HEALTH AND MAKES FOES WITHIN 5M COWER: SLOWED, AND DEALING LESS DAMAGE FOR 2.5S.",
      "SAVE IT FOR WHEN YOUR ARMY IS ALREADY SWINGING AT SOMETHING. IN DEATHMATCH, ROAR AS YOU WADE IN: THE SLOW KEEPS THEM IN SLAM RANGE AND THE SHIELD EATS THEIR ANSWER.",
    ],
    z: [
      "EARTHQUAKE. A HUGE STOMP THAT STUNS EVERYONE AROUND YOU AND HURTS BUILDINGS TOO.",
      "WAIT FOR THEM TO CLUMP UP OR COMMIT TO A FIGHT. A WHIFFED QUAKE IS A VERY LOUD APOLOGY.",
    ],
    picks: {
      bloodroar: "TAKE IT IF YOU FIGHT ALONGSIDE A BIG ARMY. EVERY TROOP BECOMES A LITTLE LEECH.",
      challenge: "TAKE IT IF YOU KEEP LOSING DUELS. YANKING A FAST HERO INTO YOUR LAP SOLVES MOST PROBLEMS.",
      magnitude: "PULLS EVERYONE INTO ONE SPOT. PERFECT SETUP FOR EARTHQUAKE. WITH CHALLENGE IT STUNS TOO.",
      shouldercharge: "TURNS YOUR SLAM INTO A GAP-CLOSER. GOOD AGAINST RUNNERS LIKE GRIM AND REMNIL.",
      earthsplitter: "GIVES YOU A RANGED STUN ON EVERY FINISHER. GREAT FOR CLEARING TROOPS IN A LINE.",
      berserker: "SELF-HEALING AND FASTER SWINGS. PICK IT IF YOU PLAN TO STAND IN THE MIDDLE OF EVERYTHING.",
      cataclysm: "MORE QUAKE. NOBODY HAS EVER COMPLAINED ABOUT MORE QUAKE.",
    },
    evo: {
      r: "THE BIG QUESTION: ARE YOU LEADING AN ARMY OR HUNTING HEROES?",
      b: "SLAM UPGRADES. LOOK AT YOUR WAR CRY PICK FIRST, EACH SLAM HAS A FAVOURITE.",
      a: "PICK BY WHAT YOU'RE HITTING MOST: A LINE OF TROOPS OR ONE ANNOYING HERO.",
      z: "THE QUAKE GETS BIGGER AND LEAVES LAVA. THAT'S IT. THAT'S THE PAGE.",
    },
    tactics:
      "WALK IN BEHIND YOUR BRUTES, SLAM WHEN THEY ENGAGE, WAR CRY WHEN EVERYONE IS SWINGING, QUAKE WHEN THEY TRY TO RUN. YOU ARE NOT FAST, SO DON'T CHASE FOR LONG. LET THEM COME TO YOU.",
    fear: "GETTING KITED. REMNIL AND STIG'S BALLISTA CAN HURT YOU FROM FAR AWAY WHILE YOU STOMP AT NOTHING.",
  },
  engineer: {
    lore: "STIG BUILT HIS FIRST TOWER AT AGE SIX OUT OF SPOONS. IT HELD FOR THREE WEEKS AND HURT A MAILMAN. HE HAS NEVER BEEN PROUDER OF ANYTHING. HE BUILDS CHEAPER BECAUSE HE ARGUES WITH EVERY MERCHANT FOR AN HOUR.",
    role: "THE BUILDER. HIS TOWERS AND UPGRADES COST LESS (A LITTLE LESS SO IN FREE FOR ALL), HE REPAIRS THEM, AND HE CAN RAISE A RAMP AND PARK A BALLISTA ON IT. HIS REPAIR PULSE ALSO PATCHES UP SOLDIERS AND HIS PARTNER. BASTION: A MARKSMAN, CASTER OR SUPPORT PARTNER FIGHTING WITHIN 7M OF YOUR BUILDINGS TAKES 12-15% LESS. FIELD WORKSHOP: ANY PARTNER WITHIN 7M OF YOUR BUILDINGS MENDS 2% OF THEIR HEALTH A SECOND AND MOVES 10% FASTER. FIGHT AT YOUR TOWERS.",
    a: [
      "A WRENCH COMBO. NOTHING FANCY. STANDING ON YOUR OWN RAMP, A INSTEAD THROWS THE WRENCH.",
      "STIG IS STURDY, SO YOU CAN TRADE HITS. JUST DON'T EXPECT TO WIN A DUEL WITH FRANCOIS ON WRENCH ALONE.",
    ],
    b: [
      "REPAIR. HEALS EVERY BUILDING AROUND YOU AND HITS NEARBY FOES WITH THE PULSE.",
      "A TOWER ABOUT TO FALL IS A TOWER THAT ISN'T. KEEP AN EYE ON YOUR HEALTH BARS.",
    ],
    r: [
      "SIEGE RAMP. RAISES A RAMP YOU CAN STAND ON. HIGH GROUND, BETTER SHOTS, ANGRY ENEMIES BELOW.",
      "BUILD IT NEXT TO AN ENEMY TOWER, THEN PUT THE BALLISTA ON TOP.",
    ],
    z: [
      "BALLISTA. PLANTS A BIG CROSSBOW THAT SHOOTS ON ITS OWN. ON A RAMP IT HITS HARDER. ONLY ONE AT A TIME.",
      "PLACE IT WHERE THEY HAVE TO WALK, NOT WHERE THEY ALREADY ARE.",
    ],
    picks: {
      teslatower: "YOUR RAMP KEEPS ITS RAMP AND GETS A LIGHTNING COIL ON TOP. EXCELLENT AGAINST CROWDS OF TROOPS.",
      palisade: "YOUR RAMP BECOMES A SPIKED WALL THAT POPS UP UNDER PEOPLE. BLOCKS ROADS, STUNS, HURTS.",
      shockwrench: "REPAIR BECOMES A STUN BOMB. WITH TESLA TOWER IT ALSO MAKES YOUR TOWERS FIRE DOUBLE SPEED.",
      fortify: "REPAIRS HAND OUT SHIELDS TO EVERYONE. WITH PALISADE YOUR WALLS STAY UP LONGER.",
      riveter: "YOUR FINISHER SHOOTS HOT RIVETS. FINALLY, A REASON TO HIT THINGS.",
      overclock: "HITTING STUFF LOWERS YOUR REPAIR COOLDOWN AND STARTS ZAPPING. GOOD IF YOU BRAWL A LOT.",
      greatballista: "A BIGGER, MEANER, LONGER-LIVED BALLISTA. TAKE IT. YOU DON'T HAVE A CHOICE ANYWAY.",
    },
    evo: {
      r: "WHAT SHOULD YOUR RAMP BECOME? LIGHTNING FOR THE CROWDS, OR A WALL FOR THE ROADS.",
      b: "REPAIR UPGRADES. BOTH COMBOS ARE STRONG, SO MATCH THE ONE THAT GOES WITH YOUR RAMP.",
      a: "STIG DOESN'T LIVE ON HIS BASIC ATTACK, BUT THESE MAKE IT WORTH PRESSING.",
      z: "GREAT BALLISTA. PROBABLY THE MOST POLITE WAY TO DESTROY A KEEP.",
    },
    tactics:
      "BUILD EARLY, BUILD OFTEN. YOU GET TOWERS CHEAPER, SO SPEND THAT GOLD ON OUTPOSTS AND UPGRADES. PUSH WITH A RAMP AND BALLISTA COMBO AND LET THE MACHINES DO THE DAMAGE.",
    fear: "GRIM SNEAKING AROUND YOUR TOWERS AND BREAKING THEM WHILE YOU'RE BUSY BEING HANDY ELSEWHERE.",
  },
  raider: {
    lore: "GRIM WAS RAISED BY WOLVES, WHO LATER SUED. HE HAS NO HOUSE, NO BANNER AND NO TABLE MANNERS. HE DOES HAVE TWO VERY SHARP KNIVES AND AN ENORMOUS GRUDGE AGAINST EVERYONE TALLER THAN HIM, WHICH IS EVERYONE.",
    role: "THE GLASS CANNON. FASTEST HERO, LEAST HEALTH, MOST STAB. GETS IN, KILLS SOMEONE, GETS OUT. CAN CLIMB SLOPES OTHERS CAN'T. BLOODTHIRST: HE HEALS FOR 20% OF THE DAMAGE HE DEALS TO CHAMPIONS. VANISH: A CHAMPION KILL HEALS HIM 30% AND READIES LEAP AND SMOKE, SO HE CAN GET OUT. SOLDIERS HIT HIM 10% HARDER, SO DON'T WADE THROUGH A WAVE.",
    a: [
      "A FLURRY OF NEAR-INSTANT STABS WITH A HEAVIER FINISHER. HITS FROM BEHIND DEAL MORE. THE STABS DON'T MAKE FOES FLINCH, SO THEY CAN WALK AWAY.",
      "STICK TO ONE TARGET. YOUR SWINGS ARE NARROW, SO SPINNING AROUND IN A CROWD WASTES THEM.",
    ],
    b: [
      "LEAP. JUMP UP TO 8M AND LAND ON SOMEONE. KILLS RESET THE COOLDOWN.",
      "USE IT TO GET IN, OR TO GET OUT. NOT BOTH, UNLESS YOU KILL SOMETHING.",
    ],
    r: [
      "SMOKE. GO INVISIBLE FOR A FEW SECONDS AND MOVE FASTER. YOUR FIRST HIT OUT OF SMOKE HURTS 60% MORE. TWO CHARGES: ONE TO GET IN, ONE TO GET OUT.",
      "WALK BEHIND THEM, THEN ATTACK. A STEALTHED STAB TO THE BACK IS THE WHOLE POINT OF YOU.",
    ],
    z: [
      "EXECUTE DASH. A LONG DASH THAT DEALS HUGE DAMAGE AND HITS EVEN HARDER ON FOES BELOW 40%. IT TAKES NO BACKSTAB OR SMOKE BONUS: OPEN WITH A STAB, FINISH WITH THE DASH.",
      "DON'T OPEN WITH IT. FINISH WITH IT.",
    ],
    picks: {
      smokebomb: "YOUR SMOKE ALSO CHOKES AND SLOWS ANYONE STANDING IN IT. NOBODY ESCAPES.",
      shadowstep: "YOUR SMOKE BECOMES A SHORT TELEPORT. CROSS WALLS, CLIFFS AND BAD DECISIONS.",
      pounce: "LEAP MARKS ITS VICTIM, THEN THE MARK EXPLODES. WITH SMOKE BOMB MARKS HURT EVEN MORE.",
      doublejump: "LEAP TWICE. WITH SHADOW STEP, BLINKING GIVES YOU LEAP BACK. YOU WILL NEVER TOUCH THE GROUND.",
      serrated: "BLEED STACKS AND A BIG RIP ON THE FINISHER. YOU HEAL OFF BLEEDING FOES.",
      twinfangs: "YOUR FINISHER THROWS POISON DAGGERS THAT SLOW AND BOUNCE. GOOD FOR CHASING.",
      deathmark: "EXECUTE AT HALF HEALTH INSTEAD OF 40%, AND A KILL REFUNDS YOUR METER. CHAIN KILLS.",
    },
    evo: {
      r: "AMBUSHER OR ESCAPE ARTIST. SMOKE BOMB TRAPS, SHADOW STEP TELEPORTS.",
      b: "LEAP UPGRADES. EACH ONE IS BUILT FOR ONE OF YOUR SMOKE PICKS, SO MATCH THEM.",
      a: "BLEED THEM OUT OR SLOW THEM DOWN. BOTH SAY 'YOU'RE NOT LEAVING'.",
      z: "DEATH MARK TURNS ONE KILL INTO TWO. VERY RUDE.",
    },
    tactics:
      "PICK ON SOMEONE ALONE. GO INVISIBLE, WALK BEHIND THEM, LEAP OR STAB, EXECUTE WHEN THEY'RE LOW. IF IT GOES WRONG, LEAVE IMMEDIATELY. A DEAD GRIM LOSES YOUR TEAM GOLD.",
    fear: "LANE TOWERS AND THORN. YOU ARE MADE OF PAPER AND BOTH OF THEM ARE MADE OF NOT-PAPER.",
  },
  summoner: {
    lore: "REMNIL STUDIED NECROMANCY BECAUSE THE LIBRARY HAD RUN OUT OF BOOKS ON GARDENING. HE TALKS TO HIS SKELETONS, NAMES THEM, AND IS VISIBLY UPSET WHEN THEY GET SMASHED. THEY DO NOT TALK BACK. YET.",
    role: "THE RANGED MIXED ATTACKER. SHOOTS FROM FAR, HEXES GROUPS, RAISES THE DEAD TO FIGHT FOR HIM AND WALKS THROUGH THE GRAVE TO ANY OF HIS BUILDINGS.",
    a: [
      "A VOLLEY OF THREE BOLTS. THE THIRD IS A BIG ORB THAT SPLASHES AND SLOWS.",
      "BOLTS NO LONGER STAGGER HEROES, BUT THE ORB DOES. TIME THE THIRD SHOT FOR WHEN THEY CHARGE.",
    ],
    b: [
      "HEX. A CURSE CIRCLE THAT SNAPS SHUT HALF A SECOND LATER: IT HURTS, ROOTS FOES IN PLACE FOR A MOMENT, THEN SLOWS THEM. ANYONE WHO DIES WHILE HEXED GETS BACK UP ON YOUR SIDE.",
      "HEX A CROWD OF ENEMY TROOPS RIGHT BEFORE THEY DIE AND GROW YOUR ARMY FOR FREE.",
    ],
    r: [
      "GRAVEWALK. HOLD R: EVERY BUILDING YOU CAN WALK TO LIGHTS UP. STEER THE MARKER WITH THE STICK TO PICK ONE, LET GO, AND AFTER A 1S CHANNEL YOU STEP OUT OF A GRAVE BESIDE IT. TAP R TO GO STRAIGHT HOME. YOU EMPOWER IT RIGHT AWAY FOR AS LONG AS YOU STAY WITHIN 6M: AN OUTPOST TRAINS 40% FASTER, A TOWER ATTACKS 50% FASTER.",
      "A STUN BREAKS THE CHANNEL. WHILE THE GATES ARE SHUT YOU CAN ONLY WALK TO BUILDINGS INSIDE YOUR OWN WALLS.",
    ],
    z: [
      "RAISE AN ARMY. THE DEAD BURST OUT OF THE GROUND AROUND YOU: FOES WITHIN 7M ARE KNOCKED UP AND STUNNED, AND A WHOLE SQUAD OF SKELETONS STAYS TO FIGHT.",
      "DROP IT IN THE MIDDLE OF A PUSH. A SURPRISE ARMY TURNS A FAIR FIGHT INTO A VERY UNFAIR ONE.",
    ],
    picks: {
      risenranks:
        "SOLDIERS FROM AN OUTPOST YOU'RE EMPOWERING COME OUT AS VETERANS. BUILD AN ARMY THAT'S ALREADY RANKED.",
      wraithgate:
        "A FASTER CHANNEL AND YOU ARRIVE SWINGING: FOES NEAR YOUR LANDING ARE HURT, HEXED AND SLOWED, AND YOU GET A SHIELD. FOR JUMPING INTO A FIGHT AT YOUR TOWER.",
      gravepull: "HEX DRAGS PEOPLE TOGETHER AND LEAVES SPIKES. WITH WRAITH GATE IT ALSO STUNS.",
      cascade: "HEX FALLS THREE TIMES IN A LINE. WITH RISEN RANKS EVERY HEX RAISES A GRUNT.",
      soulsiphon: "YOUR BOLTS HEAL YOU AND BUILD A SHIELD. MAKES YOU MUCH HARDER TO JUMP ON.",
      arcbolts: "BOLTS JUMP BETWEEN TARGETS. IT TURNS YOU INTO A TROOP SHREDDER.",
      legion: "A BIGGER ARMY FOR LONGER, AND YOUR HEX REACHES FURTHER. MORE FRIENDS, ALL DEAD.",
    },
    evo: {
      r: "ARMY OR AMBUSH. RISEN RANKS GROWS VETERANS AT HOME, WRAITH GATE TURNS THE WALK INTO AN ATTACK.",
      b: "HEX UPGRADES. EACH HAS A STRONG COMBO WITH ONE GRAVEWALK EVOLUTION, SO PICK THE MATCHING ONE.",
      a: "SURVIVE (SIPHON) OR SHRED (ARC BOLTS). IF PEOPLE KEEP DIVING YOU, TAKE SIPHON.",
      z: "LEGION. YOUR ARMY OF THE DEAD BECOMES A SLIGHTLY LARGER ARMY OF THE DEAD.",
    },
    tactics:
      "STAY BEHIND YOUR TROOPS AND SHOOT. HEX CLUMPS OF ENEMY SOLDIERS TO STEAL THEM. WHEN SOMEONE DIVES YOU, HEX THEM AND SWAP AWAY. WHEN A TOWER IS UNDER SIEGE, GRAVEWALK TO IT AND STAND YOUR GROUND BESIDE IT.",
    fear: "GRIM APPEARING BEHIND YOU WITH NO WARNING. KEEP GRAVEWALK READY AS YOUR WAY HOME, AND CHANNEL IT OUT OF HIS SIGHT.",
  },
  duelist: {
    lore: "FRANCOIS HAS BEEN IN 312 DUELS AND HAS WON ALL OF THEM, ACCORDING TO FRANCOIS. HE FIGHTS WITH ONE HAND BEHIND HIS BACK. THE OTHER HAND IS HOLDING A BAGUETTE. NOBODY KNOWS WHERE THE BAGUETTE GOES DURING THE FIGHT.",
    role: "THE ALL-ROUNDER. DECENT AT EVERYTHING, GREAT AT ONE-ON-ONE, BUT NO SIEGE ENGINE: HE DEALS 45% LESS TO BUILDINGS. REWARDS GOOD TIMING MORE THAN ANYONE. A DUELLIST, NOT A MOWER: EACH SWING, LUNGE OR FLURRY BEAT HITS AT MOST TWO SOLDIERS (CHAMPIONS ALWAYS COUNT).",
    a: [
      "THREE QUICK THRUSTS WITH A LUNGING FINISHER. CRITS A LOT.",
      "THE THRUSTS ARE NARROW BUT REACH FAR. POKE FROM THE EDGE OF THEIR RANGE.",
    ],
    b: [
      "LUNGE. A FAST DASH THROUGH THE FIRST FOE IN LINE.",
      "GOOD FOR CHASING, BETTER FOR DODGING THROUGH SOMEONE WHO EXPECTED YOU TO RUN AWAY.",
    ],
    r: [
      "PARRY. A SHORT GUARD WINDOW. IF THEY HIT YOU INSIDE IT, YOU COUNTER, STUN THEM AND RESET LUNGE.",
      "PARRY WHEN THEY START SWINGING, NOT WHEN THEY'RE HALFWAY THROUGH. LISTEN FOR THE WIND-UP.",
    ],
    z: [
      "BLADE FLURRY. A STORM OF STABS THAT HITS STUNNED FOES MUCH HARDER.",
      "PARRY, THEN FLURRY. THE COUNTER STUNS THEM AND THE FLURRY DOES THE REST.",
    ],
    picks: {
      riposte: "A WIDER PARRY THAT GIVES A SHIELD AND A HARDER COUNTER. FOR PEOPLE WHO LIKE TO WAIT.",
      volte: "PARRY BECOMES A SIDESTEP, AND YOUR NEXT ATTACK HITS MUCH HARDER. FOR PEOPLE WHO DON'T.",
      blinkstep: "LUNGE TWICE, AND A GHOST OF YOU LUNGES AGAIN. WITH VOLTE, SIDESTEPPING GIVES LUNGE BACK.",
      marked: "LUNGE MARKS FOES: YOUR WHOLE TEAM HITS THEM HARDER. WITH RIPOSTE, PARRIED FOES ARE MARKED TOO.",
      fleche: "A STRONGER FINISHER THAT SENDS A SLASH THROUGH A LINE. GOOD AGAINST TROOPS.",
      momentum: "EVERY HIT STACKS DAMAGE AND SPEED AND CUTS YOUR PARRY COOLDOWN. LONG FIGHTS BECOME YOURS.",
      thousandcuts: "MORE FLURRY, AND EVEN MORE AGAINST THE STUNNED. RIPOSTE INTO THIS IS NASTY.",
    },
    evo: {
      r: "PATIENT (RIPOSTE) OR SLIPPERY (VOLTE). BOTH ARE GREAT. ONE OF THEM SUITS YOU.",
      b: "LUNGE UPGRADES. BLINK STEP WANTS VOLTE, MARKED WANTS RIPOSTE.",
      a: "FLECHE FOR CLEARING TROOPS, MOMENTUM FOR LONG HERO FIGHTS.",
      z: "THOUSAND CUTS. MORE CUTS THAN A THOUSAND? NO, EXACTLY A THOUSAND. WE COUNTED.",
    },
    tactics:
      "FIGHT THE OTHER HERO, NOT THEIR ARMY. WAIT FOR THEM TO SWING, PARRY, PUNISH WITH FLURRY OR A FULL COMBO. IF THEY STOP SWINGING AT YOU, LUNGE THROUGH THEM AND MAKE THEM.",
    fear: "BEING SWARMED. PARRY ONLY STOPS ONE HIT, AND TEN GRUNTS HAVE TEN SWORDS.",
  },
  warden: {
    lore: "THORN IS A TREE. NOT A MAN DRESSED AS A TREE, NOT A TREE-SHAPED MAN. A TREE. HE GOT INVOLVED IN THE GRUDGE BECAUSE SOMEONE CHOPPED HIS COUSIN INTO A PALISADE. STIG STILL WON'T SAY WHERE HE GOT THE WOOD.",
    role: "THE KEEPER. A TANKY AREA CONTROLLER. WALLS OFF ROADS, SLOWS PEOPLE DOWN, SPEEDS FRIENDS UP AND HITS BUILDINGS HARDER THAN MOST.",
    a: [
      "TWO WIDE SWEEPS OF BARK. HITS EVERYTHING IN FRONT OF YOU.",
      "GREAT FOR CLEARING CLUMPS OF TROOPS. AIM AT THE MIDDLE OF THE CROWD.",
    ],
    b: [
      "LONG ARM SLAP. A RANGED BRANCH SWING THAT KNOCKS BACK AND STUNS BRIEFLY.",
      "SLAP PEOPLE OFF CLIFFS. IT'S NOT IN THE TOOLTIP BUT IT SHOULD BE.",
    ],
    r: [
      "STONE WALL. RAISES A WALL WITH SNARES AT BOTH ENDS. BLOCKS ROADS AND CHOKEPOINTS.",
      "WALL A NARROW GAP BEHIND A FLEEING HERO. THE SNARES WILL GET THEM.",
    ],
    z: [
      "BRAMBLES. A BIG FIELD OF THORNS: FOES ARE SLOWED AND HURT, ALLIES INSIDE MOVE FASTER.",
      "THROW IT UNDER A FIGHT AND STAND IN IT. YOUR WHOLE TEAM BECOMES QUICKER AND THEIRS SLOWER.",
    ],
    picks: {
      rootcage: "THE WALL BECOMES A ROOT TRAP YOU AIM. HOLDS A HERO IN PLACE FOR A GOOD WHILE.",
      rampart: "A BIGGER WALL THAT HEALS ALLIES NEXT TO IT. MAKE A FORT ANYWHERE.",
      graspingvine: "YOUR SLAP PULLS PEOPLE TO YOU AND STUNS THEM. WITH ROOT CAGE, YANKING A ROOTED FOE HURTS MORE.",
      whiplash: "YOUR SLAP HITS A WHOLE LINE AND EXPLODES. WITH LIVING RAMPART IT STUNS TOO.",
      thornguard: "HITS GROW A BARK SHIELD. VERY HARD TO KILL WHILE YOU'RE SWINGING.",
      overgrowth: "YOUR FINISHER ROOTS PEOPLE AND LEAVES BRAMBLES. EVERY COMBO BECOMES A TRAP.",
      ancientgrove: "BIGGER, LONGER BRAMBLES THAT ALSO HEAL ALLIES. A WHOLE FOREST OF BAD NEWS.",
    },
    evo: {
      r: "TRAP (ROOT CAGE) OR FORT (RAMPART).",
      b: "SLAP UPGRADES. GRASPING VINE GOES WITH ROOT CAGE, WHIPLASH WITH RAMPART.",
      a: "SURVIVE (THORNGUARD) OR CONTROL (OVERGROWTH).",
      z: "ANCIENT GROVE. IT'S BRAMBLES BUT WITH HEALING. GRANDMA'S RECIPE.",
    },
    tactics:
      "STAND BETWEEN YOUR BASE AND THEIRS. WALL THE ROADS, SLAP INTRUDERS, DROP BRAMBLES UNDER BIG FIGHTS. YOU'RE STRONG AGAINST BUILDINGS, SO WHEN YOU PUSH, GO STRAIGHT FOR THE TOWERS.",
    fear: "REMNIL AND STIG'S BALLISTA POKING FROM RANGE. YOU'RE SLOW TO CLOSE THE GAP.",
  },
  marksman: {
    lore: "WREN HOLLOWMERE WAS THE BEST POACHER IN THE KING'S FOREST UNTIL THE KING ASKED HER TO STOP. SHE DIDN'T. NOW SHE SHOOTS FOR WHOEVER PAYS, AND PIP, HER HAWK, KEEPS THE CHANGE. PIP HAS STOLEN FOUR CROWNS, ONE WIG AND THORN'S FAVOURITE ACORN.",
    role: "THE LONGBOW. SHOOTS FROM FURTHER THAN ANYONE BUT REMNIL AND HURTS FOR IT, BUT SHE IS FRAIL AND SLOW: SHE HAS TO HIDE AND PICK HER SHOTS. VANTAGE: FROM GROUND A METRE HIGHER THAN HER TARGET, OR AFTER STANDING STILL FOR A SECOND, HER SHOTS HIT 25% HARDER AND REACH 20% FURTHER. A GOLD GLINT ON HER SAYS IT'S ON.",
    a: [
      "ONE HEAVY LONGBOW ARROW, 11M, THEN A 1.4S RELOAD. HOLD A TO DRAW A FULL POWER SHOT THAT PIERCES THROUGH EVERYTHING IN A LINE. MAKE EVERY ARROW COUNT.",
      "PLANT YOUR FEET. A WREN WHO STANDS STILL BEHIND HER SOLDIERS IS A WREN WHO WINS TRADES.",
    ],
    b: [
      "SEND PIP. THE HAWK FLIES OUT (SLOWLY, EVERYONE SEES HIM COMING) AND LATCHES ONTO THE NEAREST FOE (CHAMPIONS FIRST, HOLD B TO AIM) FOR 5S: THEY'RE SLOWED 25%, TAKE 15% MORE FROM YOU, CAN'T HIDE IN GRASS OR SMOKE, PIP PECKS THEM AND EVERY ARROW EARNS A BONUS PECK, AND EVERY CHANNEL BREAKS: RECALL, JUMP PADS, THE GRUDGE, GRAVEWALK, HORNS. PRESS B AGAIN TO CASH IN: PIP RAKES THEIR FACE FOR 70 AND BLINDS THEM FOR 2.5S (HALF THEIR ATTACKS MISS), THEN FLIES HOME. ONCE HE HAS HELD ON FOR A SECOND, A DODGE ROLL SHAKES HIM OFF.",
      "HOLD THE MARK WHILE YOU SHOOT, THEN RAKE THE MOMENT THEY TURN TO SWING AT YOU.",
    ],
    r: [
      "VOLLEY. A RAIN OF ARROWS FALLS ON A SPOT UP TO 9M AWAY FOR ABOUT 2S. IT HURTS AND SLOWS, AND SOLDIERS TAKE HALF AGAIN AS MUCH.",
      "TAP R TO LOB IT AT WHOEVER YOU'RE FACING, OR HOLD R TO PLACE IT. DROP IT WHERE THEY HAVE TO WALK, NOT WHERE THEY ARE.",
    ],
    z: [
      "HEARTSEEKER. A LONG DRAW, THEN ONE ARROW 28M DOWN A LINE. THE FIRST CHAMPION IT MEETS TAKES A HUGE HIT AND IS KNOCKED BACK; EVERYTHING ELSE IN THE LINE GETS HURT TOO.",
      "YOU STAND STILL WHILE YOU DRAW, SO VANTAGE ALWAYS COUNTS. AIM DOWN A BRIDGE OR A GATE AND LET THEM WALK INTO IT.",
    ],
    picks: {
      firearrows: "THE VOLLEY LEAVES BURNING GROUND. EXCELLENT FOR HOLDING A CHOKEPOINT.",
      doublevolley: "THE SKY FALLS TWICE. SOLDIERS DON'T SURVIVE THE SECOND ONE.",
      longwatch: "PIP STAYS 8S AND THE MARK BITES HARDER.",
      talons: "PIP PECKS EVERY SECOND ON ITS OWN, AND THE PECKS BLEED.",
      broadhead: "ARROWS BURST AROUND THE TARGET. YOUR BASIC ATTACK BECOMES A SOLDIER SHREDDER.",
      quickdraw: "FASTER ARROWS, AND HITTING CHAMPIONS GETS PIP BACK SOONER. FOR HERO HUNTERS.",
      huntersmark: "MARKS EVERYTHING IT HITS FOR YOUR HOUSE AND SENDS PIP AFTER THE CHAMPION.",
    },
    evo: {
      r: "MORE VOLLEY OR BETTER VOLLEY: BURNING GROUND, OR A SECOND RAIN.",
      b: "PIP UPGRADES. LONG WATCH GOES WITH DOUBLE VOLLEY, RAKING TALONS WITH FIRE ARROWS.",
      a: "BROADHEAD FOR SOLDIERS, QUICKDRAW FOR CHAMPIONS.",
      z: "TWO WAYS TO END A FIGHT FROM 28M AWAY. BOTH ARE RUDE.",
    },
    tactics:
      "STAY BEHIND YOUR SOLDIERS, FIND HIGH GROUND OR JUST STOP MOVING, AND SHOOT. SEND PIP AT THE CHAMPION YOU WANT DEAD, THEN LET YOUR ARROWS PECK THEM APART. SAVE VOLLEY FOR CLUMPS OF SOLDIERS AND HEARTSEEKER FOR A HERO IN A LINE.",
    fear: "GRIM. HE'S FAST, HE'S HIDDEN AND HE'S ALREADY BEHIND YOU. KEEP PIP READY: IT FINDS HIM IN THE GRASS, AND SKYSHOT GETS YOU OUT.",
  },
  friar: {
    lore: "BROTHER MADDOCK TOOK A VOW OF POVERTY, A VOW OF SILENCE AND A VOW OF SOBRIETY. HE KEPT THE FIRST ONE. HIS ABBEY BREWS THE BEST ALE IN THE VALLEY AND HE CARRIES A KEG OF IT EVERYWHERE, FOR MEDICINAL REASONS, MOSTLY HIS.",
    role: "THE HEALER. STURDY AND SLOW, HITS SOFTLY, BUT KEEPS EVERYONE AROUND HIM ON THEIR FEET. PLENTY: HE IS ALWAYS HEALING HIMSELF, FRIENDLY SOLDIERS AND CHAMPIONS WITHIN 7M SLOWLY REGENERATE, AND ALL HIS HEALING IS 25% STRONGER ON ANYONE BELOW HALF HEALTH.",
    a: [
      "THREE SWINGS WITH HIS TANKARD AND STAFF. THE LAST ONE IS A BIG BELLY-WEIGHTED WALLOP.",
      "YOU'RE NOT HERE TO WIN DUELS. HIT WHAT COMES CLOSE AND KEEP YOUR KEGS FLYING.",
    ],
    b: [
      "HEALING KEG. LOBS A KEG UP TO 8M THAT BURSTS AND HEALS EVERY FRIEND IN THE SPLASH, CHAMPIONS AND SOLDIERS ALIKE, THEN LEAVES AN ALE PUDDLE FOR 5S: FRIENDS IN IT HEAL AND KEEP HEALING FOR 3S AFTER THEY STEP OUT, FOES WHO WADE IN ARE POISONED FOR 3S.",
      "TAP B AND IT FINDS THE MOST HURT BUNCH OF FRIENDS ON ITS OWN. HOLD B TO PUT IT EXACTLY WHERE YOU WANT.",
    ],
    r: [
      "POWDER KEG. A KEG WITH A LIT FUSE. IT BLOWS A SECOND AFTER IT LANDS, OR STRAIGHT AWAY IF IT LANDS ON A CHAMPION, KNOCKING EVERYONE BACK. TWO CHARGES, 1S APART; WITH BOTH OUT, R BLOWS THEM RIGHT NOW. SOLDIERS AND BUILDINGS HATE IT MOST.",
      "THE FUSE GIVES CHAMPIONS A MOMENT TO RUN. SOLDIERS DON'T RUN. TOWERS CAN'T.",
    ],
    z: [
      "BREWFEST. SLAMS DOWN A GIANT TAPPED CASK: FRIENDS CLOSE BY ARE HEALED AND FREED FROM STUNS AND SLOWS, FOES ARE BLOWN BACK AND STUNNED. FOR 6S, FRIENDS WITHIN 7M HEAL FAST, HIT 20% HARDER AND MOVE FASTER; FOES IN IT ARE TIPSY: SLOWED AND TAKING 15% MORE DAMAGE. THE CASK CAN BE SMASHED.",
      "PLANT IT IN THE MIDDLE OF A BIG FIGHT, NOT IN FRONT OF A TOWER. THEY WILL GO FOR THE CASK.",
    ],
    picks: {
      clusterkeg: "THE POWDER KEG SPLITS INTO LITTLE ONES. CARPETS A CROWD OF SOLDIERS.",
      tarkeg: "THE BLAST LEAVES BURNING TAR THAT SLOWS. NOBODY ESCAPES THE SECOND KEG.",
      stout: "EVERY FRIEND IN THE SPLASH ALSO GETS A SHIELD.",
      wellspring: "A BIGGER, LONGER PUDDLE THAT SPEEDS YOUR FRIENDS UP.",
      tapster: "HITS HEAL YOU AND PATCH UP NEARBY SOLDIERS. FOR THE FRIAR WHO LIKES A SCRAP.",
      bellyflop: "THE FINISHER STUNS. NOW YOUR TANKARD IS A REASON TO KEEP AWAY.",
      grandcask: "A BIGGER, LONGER, STURDIER CASK. MORE PARTY.",
    },
    evo: {
      r: "POWDER KEG UPGRADES: MORE KEGS, OR STICKY BURNING TAR.",
      b: "HEALING KEG UPGRADES. HEARTY STOUT GOES WITH CLUSTER KEG, WELLSPRING WITH TAR KEG.",
      a: "SELF-SUSTAIN (TAPROOM BRAWLER) OR CONTROL (BELLY FLOP).",
      z: "A BIGGER PARTY, OR A PARTY THAT ENDS WITH A BANG.",
    },
    tactics:
      "WALK WITH YOUR SOLDIERS AND YOUR PARTNER, KEEP KEGS ON WHOEVER IS HURTING, AND THROW POWDER KEGS INTO EVERY CLUMP AND AT EVERY TOWER IN REACH. BREWFEST WINS BIG FIGHTS: PLANT IT, STAND IN IT, LET YOUR SIDE OUT-LAST THEIRS.",
    fear: "BEING CAUGHT ALONE BY FRANCOIS OR GRIM. YOU'RE STURDY BUT SLOW, AND THEY CAN OUT-DAMAGE YOUR HEALING. A PUDDLE AND A KEG ROCKET ARE YOUR WAY OUT.",
  },
  scribe: {
    lore: "GRANNY HOLLIN HAS WRITTEN FORTY-ONE NOVELS ABOUT DRAGONS, WIZARDS AND LOST KINGDOMS, AND SHE HAS NEVER ONCE MISSED A DEADLINE. NOW SHE WRITES THE BATTLE AS IT HAPPENS, IN THE MARGINS, AND THE BATTLE HAS LEARNED TO DO AS IT'S TOLD. HER EDITOR IS TERRIFIED OF HER. SO IS EVERYONE ELSE.",
    role: "THE NOVELIST. A SLOW OLD CASTER WHO FIGHTS FROM RANGE AND PLANS AHEAD. ANNOTATIONS: HER CHARGED BOLTS AND HER SWARMS WRITE A GLOWING RUNE WHERE THEY LAND (UP TO 4, 12S EACH). A SPELL THAT LANDS ON ONE OF HER RUNES USES IT UP AND IS EMPOWERED, AND ERRATUM LETS HER SWAP PLACES WITH ANY OF THEM.",
    a: [
      "INK BOLT. A FAST BOLT OF INK, 12.5M, THAT RICOCHETS ONCE: OFF A WALL, OR ON TO THE NEAREST FOE IT HITS (CHAMPIONS FIRST). HOLD A FOR A CHARGED BOLT THAT HITS HARDER, SPLASHES AN INK BLOT THAT BLINDS EVERYONE IN IT FOR 1.2S (HALF THEIR ATTACKS MISS) AND WRITES A RUNE. A BOLT THAT ENDS ON ONE OF YOUR RUNES BURSTS IT FOR A BIGGER BLOT.",
      "BANK BOLTS OFF WALLS AROUND CORNERS, AND SHOOT INTO SOLDIERS NEXT TO A CHAMPION: THE RICOCHET FINDS THE CHAMPION.",
    ],
    b: [
      "PAPER STORM. A WHIRLWIND OF LOOSE MANUSCRIPT PAGES AND PAPER BIRDS ON A SPOT UP TO 9M AWAY FOR 4S: FOES INSIDE GET PAPER CUTS AND ARE SLOWED 35%. IT WRITES A RUNE. CAST IT ON ONE OF YOUR RUNES FOR A GREAT STORM: WIDER, 2S LONGER, CUTS DEEPER. PRESS B AGAIN WHILE IT'S OUT AND THE STORM FLIES TO YOU AND FOLLOWS YOU FOR THE REST OF ITS TIME. (AS THE BEEKEEPER, IT'S A SWARM OF BEES.)",
      "THROW IT ON THEM, THEN CALL IT HOME THE MOMENT SOMEONE DIVES YOU. NOBODY WANTS A THOUSAND PAPER CUTS.",
    ],
    r: [
      "ERRATUM. SWAP PLACES WITH A RUNE UP TO 12M AWAY (WHERE YOUR STICK POINTS, OR THE SAFEST; HOLD R TO CHOOSE); IT MOVES TO WHERE YOU STOOD. NO RUNE IN REACH? R WRITES ONE AT YOUR FEET.",
      "BOOKMARK A SAFE SPOT FIRST. WHEN IT GOES WRONG, YOU WERE NEVER THERE.",
    ],
    z: [
      "ILLUMINATED MANUSCRIPT. ALL YOUR RUNES FLARE FOR 80 AND SLOW, AND PAGES SHOVE FOES OFF YOU. FOR 8S, INK BOLTS WRITE RUNES AND RICOCHET AN EXTRA TIME, AND PAPER STORM AND ERRATUM GET ONE FREE RECAST EACH.",
      "SEED RUNES WHERE THEY'LL STAND, THEN LIGHT THE PAGE.",
    ],
    picks: {
      marginnote: "ERRATUM LEAVES AN INK BLOT THAT BLINDS WHOEVER CHASED YOU.",
      dogeared: "MORE RUNES, LONGER RUNES, MORE ERRATUMS.",
      royalhive: "A BIGGER, LONGER STORM.",
      stingingprose: "A STORM THAT REALLY HURTS AND HOLDS THEM IN PLACE.",
      ricochet: "BOLTS BOUNCE TWICE AND KEEP THEIR BITE. FOR THE FIGHT IN THE SOLDIERS.",
      indelible: "EVERY BOLT SLOWS, AND CHARGED BOLTS BLIND FOR LONGER.",
      grandcodex: "A LONGER MANUSCRIPT AND HARDER FLARES.",
    },
    evo: {
      r: "ERRATUM UPGRADES: LEAVE A BLINDING BLOT BEHIND, OR KEEP MORE RUNES AND SWAP MORE OFTEN.",
      b: "PAPER STORM UPGRADES. EPIC LENGTH GOES WITH MARGIN NOTE, STINGING PROSE WITH DOG-EARED PAGES.",
      a: "INK BOLT: MORE RICOCHETS (RICOCHET RUNES) OR MORE CONTROL (INDELIBLE INK).",
      z: "A BIGGER, BRIGHTER MANUSCRIPT.",
    },
    tactics:
      "STAY BEHIND YOUR SOLDIERS AND PLAN THE FIGHT BEFORE IT HAPPENS: BOOKMARK A RUNE BEHIND YOU, CHARGE BOLTS INTO THEIR LINE TO WRITE MORE, STORM THE CHOKEPOINTS. WHEN THEY COME FOR YOU, CALL THE STORM HOME, ERRATUM AWAY, AND KEEP WRITING.",
    fear: "WREN AND FRANCOIS. WREN OUT-RANGES YOU AND FRANCOIS CLOSES THE GAP FASTER THAN YOU CAN SWAP. FIGHT THEM NEAR YOUR RUNES, NEVER IN THE OPEN.",
  },
};

TEXT.harpooner = {
  lore: "TADWICK FISHED THE SAME TIDAL FLAT FOR FORTY YEARS AND CAUGHT EVERYTHING IN IT, INCLUDING TWO TAX COLLECTORS AND A SEA SERPENT'S NEPHEW. HIS BOW IS A WHALE'S JAWBONE. NOBODY HAS ASKED WHERE THE REST OF THE WHALE WENT.",
  role: "THE HARPOONER. A SQUAT MARKSMAN WHO FIGHTS AROUND WALLS: HIS HARPOONS RICOCHET OFF CLIFFS, ROCKS, TREES AND BUILDINGS (THEY BEND TOWARD A FOE AFTER THE BOUNCE), AND HE DRAGS PEOPLE INTO THINGS. WET: EVERYTHING HE HITS DRIPS FOR 3S AND TAKES 15% MORE FROM HIS HARPOONS; A HARPOON THAT RICOCHETED INTO A WET FOE HITS 35% HARDER ON TOP (A BANK SHOT).",
  a: [
    "ONE HARPOON, 10M, THEN A SHORT RELOAD. IT SKEWERS THROUGH UP TO TWO SOLDIERS (30% EXTRA DAMAGE TO THEM) AND RICOCHETS ONCE OFF A WALL OR STRUCTURE AND CURVES ONTO A FOE AHEAD. HOLD A FOR A FULL POWER HARPOON: FLIES FURTHER, HITS HARDER AND RICOCHETS TWICE.",
    "FIGHT NEXT TO WALLS AND TOWERS. A MISSED HARPOON ISN'T A MISS UNTIL IT RUNS OUT OF BOUNCES.",
  ],
  b: [
    "REEL IN. A HARPOON ON A ROPE: A SOLDIER IT HITS IS DRAGGED ALL THE WAY TO YOU, A CHAMPION HALF THE WAY. IF THE HARPOON BANKED OFF A WALL FIRST, THEY ARE DRAGGED INTO THAT WALL. ANYTHING THAT STOPS THEM ON THE WAY (A CLIFF, A WALL, A TOWER) SPLATS THEM: EXTRA DAMAGE AND A STUN.",
    "STAND ON A LEDGE AND REEL SOMEONE BELOW YOU STRAIGHT INTO THE CLIFF. WITH A TANK PARTNER NEARBY, THE CHAMPION LANDS AT YOUR PARTNER'S FEET INSTEAD.",
  ],
  r: [
    "TONGUE LASH. HIS TONGUE GRABS A LEDGE, TREE, ROCK OR BUILDING UP TO 7M AWAY AND YANKS HIM THERE, UP TO ONE STEP OF HIGH GROUND, OUT OF MELEE. IT AIMS WHERE YOU PUSH THE STICK, OR AWAY FROM THE NEAREST FOE.",
    "YOUR ONLY ESCAPE. KEEP IT FOR THE ONE WHO DIVES YOU, NOT FOR GETTING AROUND.",
  ],
  z: [
    "RIPTIDE. A WHIRLPOOL 6M WIDE BURSTS AROUND HIM FOR 6S: IT HITS EVERYTHING IN IT, THEN FOES INSIDE ARE SLOWED, SOAKED AND SLOWLY DRAGGED TO THE MIDDLE. HIS HARPOONS FIRED INSIDE BOUNCE OFF THE EDGE OF THE RING AND SKIP FROM FOE TO FOE.",
    "EVERYONE IN THE RING IS WET, SO EVERY BOUNCE IS A BANK SHOT. STAND IN THE MIDDLE AND KEEP FIRING.",
  ],
  picks: {
    springlegs: "TONGUE LASH REACHES FURTHER AND COMES BACK SOONER.",
    oilskin: "LANDING A TONGUE LASH SHIELDS YOU AND LEAVES A SLIPPERY PUDDLE BEHIND FOR WHOEVER FOLLOWS.",
    winch: "REEL IN DRAGS CHAMPIONS NEARLY ALL THE WAY. BRING THEM TO YOUR TOWER.",
    undertow: "WHATEVER YOU REEL IN IS SLOWED AND STAYS WET LONGER. THEY WON'T WALK AWAY.",
    barbed: "HARPOONS BLEED. EVERY BOUNCE TOPS IT UP.",
    quickline: "FASTER HARPOONS THAT BOUNCE ONE MORE TIME.",
    maelstrom: "A WIDER, LONGER, ANGRIER RIPTIDE, AND YOUR WHOLE HOUSE HITS HARDER INSIDE IT.",
  },
  evo: {
    r: "A LONGER, QUICKER LASH, OR A LASH THAT LANDS WITH A SHIELD AND A PUDDLE.",
    b: "REEL UPGRADES. WHALER'S WINCH GOES WITH SPRING LEGS, UNDERTOW WITH OILSKIN.",
    a: "BLEEDING HARPOONS (BARBED HEADS) OR MORE BOUNCES (QUICK LINE).",
    z: "THE WHIRLPOOL GROWS TEETH.",
  },
  tactics:
    "KEEP A WALL, A ROCK OR A TOWER NEAR YOUR TARGET AND BOUNCE HARPOONS OFF IT. WET THEM FIRST, THEN BANK THE NEXT ONE. REEL IN WHOEVER STANDS WITH THEIR BACK TO A CLIFF, AND SAVE TONGUE LASH FOR THE MOMENT SOMEONE REACHES YOU.",
  fear: "BEING CAUGHT IN THE OPEN BY GRIM OR THE WARLORD RIGHT AFTER YOU'VE USED REEL IN. NO WALLS, NO TRICKS.",
};

TEXT.wreckwitch = {
  lore: "MOTHER KELP WAS A SHIP'S COOK UNTIL THE SHIP WENT DOWN. SHE DIDN'T. SHE WALKED OUT OF THE SEA FORTY YEARS LATER WITH THE ANCHOR, A LANTERN NOBODY CAN BLOW OUT, AND A TEMPER LIKE A WINTER STORM. SHE STILL COOKS. NOBODY EATS IT.",
  role: "THE BRUISER WHO GETS WORSE THE LONGER YOU STAY. TIDE RISING: EVERY SECOND SHE SPENDS WITHIN 6M OF AN ENEMY CHAMPION ADDS A STACK, UP TO 10. EACH STACK: +5% DAMAGE, 2.5% LESS DAMAGE TAKEN, 3.5% OF HER DAMAGE DRUNK BACK AS HEALTH, AND SHE GROWS. 4S OUT OF REACH AND THE TIDE EBBS AWAY.",
  a: [
    "ANCHOR SWING. TWO WIDE, HEAVY SWEEPS OF THE ANCHOR, THE SECOND ONE WIDER AND HARDER. HOLD A TO WHIRL THE ANCHOR ROUND YOU INSTEAD: IT HITS EVERYONE WITHIN 3M EVERY THIRD OF A SECOND, BUT YOU WALK SLOWLY WHILE YOU SPIN.",
    "SWING AT CHAMPIONS, WHIRL IN A CROWD OF SOLDIERS. EVERY STACK OF TIDE MAKES BOTH HURT MORE AND HEAL YOU MORE.",
  ],
  b: [
    "DREDGE. HURLS THE ANCHOR UP TO 8M ON ITS CHAIN. THE FIRST FOE IT CATCHES (CHAMPIONS FIRST) TAKES A HEAVY HIT AND IS REELED IN ON THE CHAIN TO LAND AT HER FEET, STUNNED ALL THE WAY IN AND SLOWED AFTER. RIGHT INTO HER TIDE, HER SWINGS AND HER GRIP.",
    "DRAG THE ARCHER OUT OF HER SOLDIERS AND INTO YOURS, OR HAUL BACK THE ONE RUNNING AWAY. THEN GRIP THEM BEFORE THEY GET UP.",
  ],
  r: [
    "BILGE. SPITS A CLOUD OF FOUL BRINE UP TO 5M AHEAD. FOES IN IT TAKE A HIT, AND THE CLOUD HANGS FOR 3S, SLOWING AND STINGING ANYONE INSIDE. NOTHING CAUGHT IN IT CAN HEAL FOR 3S: NO KEGS, NO LEECH, NO RESTING UP.",
    "SAVE IT FOR THE HEALER, OR FOR THE CHAMPION WHO JUST RAN HOME TO PATCH UP. HOLD R TO AIM IT.",
  ],
  z: [
    "DAVY'S GRIP. DROWNED HANDS BURST FROM THE GROUND IN A 6M RING AROUND HER. EVERY FOE INSIDE TAKES 60 DAMAGE PLUS 10 FOR EVERY STACK OF TIDE SHE HAS, AND IS HELD IN PLACE FOR 1.5S.",
    "WAIT FOR HIGH TIDE. AT 10 STACKS THAT IS 170, WITH THE TIDE'S OWN +50% ON TOP, AND NOBODY IS WALKING AWAY.",
  ],
  picks: {
    brinesquall: "A BIGGER, LONGER CLOUD THAT STUNS WHOEVER IT HITS FIRST.",
    scurvy: "THE CLOUD HURTS MORE, SLOWS MORE, AND YOUR WHOLE HOUSE HITS HARDER INSIDE IT.",
    keelhaul: "DREDGE HITS HARDER AND STUNS FOR A FULL SECOND.",
    longchain: "11M OF CHAIN, A SHORTER COOLDOWN, AND EVERY CHAMPION YOU CATCH RAISES THE TIDE BY TWO.",
    barnacle: "SWINGS GROW A BARNACLE CRUST: HITTING CHAMPIONS RAISES THE TIDE FASTER.",
    breakers: "THE SECOND SWING STUNS, AND THE WHIRL REACHES FURTHER AND DRAGS FOES INTO IT.",
    davyslocker: "A WIDER RING, A LONGER HOLD, AND EVERY STACK OF TIDE HITS HARDER.",
  },
  evo: {
    r: "A STUNNING SQUALL, OR A CLOUD THAT ROTS THEM FOR YOUR WHOLE HOUSE.",
    b: "DREDGE UPGRADES. KEELHAUL GOES WITH BRINE SQUALL, LONG CHAIN WITH SCURVY.",
    a: "FASTER TIDE (BARNACLE CRUST), OR STUNS AND A BETTER WHIRL (BREAKERS).",
    z: "THE LOCKER OPENS WIDER. NOBODY COMES BACK UP.",
  },
  tactics:
    "GET CLOSE AND STAY CLOSE: THE TIDE ONLY RISES NEAR ENEMY CHAMPIONS. DREDGE IN THE ONE YOU WANT, BILGE ANYONE WHO TRIES TO HEAL, AND KEEP SWINGING. AT HIGH TIDE YOU HIT HARDER, TAKE LESS AND HEAL OFF EVERY BLOW: THAT'S WHEN YOU CALL DAVY'S GRIP AND FINISH IT.",
  fear: "WREN AND REMNIL. THEY KITE YOU BEFORE THE TIDE COMES IN, AND A WITCH WITH NO STACKS IS JUST A SLOW OLD LADY WITH AN ANCHOR. DREDGE THEM OUT OF THEIR SOLDIERS.",
};

TEXT.architect = {
  lore: "PROFESSOR HOOT TAUGHT FORTIFICATION AT THE DROWNED ACADEMY UNTIL THE ACADEMY SANK. HE SAYS THE FLOOD WAS A STRUCTURAL OVERSIGHT, NOT HIS. HE NOW BUILDS IN ICE, WHICH HE CALLS THE MOST HONEST MATERIAL: IT TELLS YOU EXACTLY WHEN IT IS ABOUT TO FAIL. HE GRADES EVERY WALL HE MEETS. MOSTLY C-MINUS.",
  role: "THE SNOW ARCHITECT. A STURDY BUILDER WHO MAKES HIS OWN HIGH GROUND: SNOW FORTS TO HIDE BEHIND, AN ICE LOOKOUT TO STAND ON AND A DOME THAT SHUTS A FIGHT IN. WATCHTOWER: ANYONE OF HIS HOUSE ON TOP OF ONE OF HIS LOOKOUTS HITS 10% HARDER, AND EVERY LOOKOUT KEEPS WATCH 9M AROUND IT: FOES IN ITS WATCH CAN'T HIDE IN GRASS, MIST OR SMOKE.",
  a: [
    "TWO FLAT SWINGS AND A HOPPING CHOP WITH A GIANT CARPENTER'S SQUARE. HOLD A TO THROW IT LIKE A BOOMERANG UP TO 9M: IT HITS ON THE WAY OUT AND AGAIN ON THE WAY BACK. A AGAIN CALLS IT BACK EARLY.",
    "THE THROW IS YOUR REACH. FROM THE LOOKOUT IT HITS 20% HARDER, AND NOBODY BELOW CAN SWING BACK.",
  ],
  b: [
    "SNOW FORT. A CURVED WALL OF SNOW AND ICE RISES WHERE YOU FACE (HOLD B TO PLACE IT) FOR 12S, KNOCKING DOWN FOES CAUGHT IN IT. ONE AT A TIME. FRIENDS RIGHT BEHIND ONE TAKE 40% LESS FROM SHOTS FROM THE FAR SIDE. FORTS ARE FRAGILE.",
    "BLOCK A BRIDGE, CUT OFF A CHASE, OR BUILD COVER FOR YOUR ARCHERS. A FORT IN FRONT OF WREN IS A VERY BAD DAY FOR WREN.",
  ],
  r: [
    "LOOKOUT. A 2M ICE TOWER SHOOTS UP UNDER YOUR FEET FOR 14S. TWO CHARGES THAT RECHARGE ON THEIR OWN, SO YOU CAN RAISE TWO BACK TO BACK. NO STAIRS: SOLDIERS CAN'T CLIMB IT AND FOES ON THE SPOT ARE SHOVED OFF. UP THERE YOUR VANTAGE IS ALWAYS ON. IT CAN BE SMASHED.",
    "STEP OFF ANY EDGE TO LEAVE, AND OWL HOP BACK UP. MELEE CHAMPIONS WILL TRY TO KNOCK YOU DOWN: LET THEM COME TO YOU.",
  ],
  z: [
    "AVALANCHE DOME. A DOME OF ICE FREEZES OVER YOU (HOLD Z TO PLACE IT UP TO 8M AWAY) FOR 6S. FOES CAUGHT IN IT ARE HIT, FROZEN A MOMENT AND SLOWED, FRIENDS MEND, AND NO ENEMY SHOT CROSSES ITS RIM, IN OR OUT - BUT YOUR SIDE SHOOTS THROUGH IT FREELY.",
    "DROP IT ON AN ARCHER OR A CASTER: THEY'RE TRAPPED IN A SNOW GLOBE WITH YOU AND THEIR SHOTS CAN'T GET OUT. OR SIT IN IT YOURSELF WHEN THE TOWERS ARE SHOOTING.",
  ],
  picks: {
    belfry: "THE LOOKOUT FIGHTS FOR YOU: IT SHOOTS ICICLES AT THE NEAREST FOE EVERY SECOND, CHAMPIONS FIRST.",
    collapse: "WHEN THE LOOKOUT FALLS IT BURSTS AND FREEZES EVERYONE AROUND IT. R AGAIN DROPS IT ON THEM ON PURPOSE.",
    bastion: "LONGER, TOUGHER FORTS, THREE OF THEM. A REAL WALL.",
    frostfort: "THE FORT RISES WITH A FROST BLAST THAT FREEZES FOES NEXT TO IT.",
    longmeasure:
      "THE SQUARE FLIES FAR AND FAST, DAZES CHAMPIONS, AND EVERY CHAMPION IT HITS GETS YOUR NEXT FORT UP SOONER.",
    frostbite: "EVERYTHING YOU HIT IS CHILLED AND TAKES MORE FROM YOU. CLOSE-RANGE PROFESSOR.",
    glacier: "A WIDER, LONGER DOME THAT FREEZES HARDER AND HEALS MORE.",
  },
  evo: {
    r: "THE LOOKOUT AS A TURRET (ICICLE BELFRY) OR AS A TRAP (AVALANCHE DROP).",
    b: "FORT UPGRADES. ICE BASTION GOES WITH ICICLE BELFRY, FROST FORT WITH AVALANCHE DROP.",
    a: "REACH (LONG MEASURE) OR PRESSURE (FROSTBITE).",
    z: "A BIGGER SNOW GLOBE.",
  },
  tactics:
    "FIGHT FROM YOUR TOWERS. RAISE A LOOKOUT WHEN A FIGHT STARTS (YOUR PARTNER CAN HOP UP TOO), PLANT ONE BY THE GRASS GRIM HIDES IN, THROW THE SQUARE FROM THE TOP, AND FORT OFF THE PATHS THEIR SOLDIERS AND MELEE CHAMPIONS NEED. SAVE THE DOME FOR THE ARCHER, THE CASTER OR THE TOWER THAT'S HURTING YOU.",
  fear: "BEING CAUGHT ON FLAT GROUND BY A BRUISER WITH THE LOOKOUT ON COOLDOWN. FORT, HOP, AND MAKE THEM WALK AROUND.",
};

TEXT.vintner = {
  lore: "HOGSHEAD KEEPS THE CELLAR UNDER THE MOONLIT VINEYARD, AND NOBODY HAS EVER GOT PAST HIM TO THE GOOD BARRELS. HE CRUSHES GRAPES WITH AN ANVIL BECAUSE HIS FEET ARE TOO BIG FOR THE VAT, AND CARRIES A SECOND ANVIL ON HIS BACK BECAUSE, IN HIS WORDS, YOU NEVER KNOW.",
  role: "THE TANK. BIG, STUBBORN AND HARD TO SHIFT, HE HITS SLOWLY BUT HEAVILY AND PROTECTS HIS FRIENDS. THICK SKIN: WHILE HE STANDS HIS GROUND (OR BLOCKS) HE BUILDS GRIT OVER 2S, UP TO 25% LESS DAMAGE TAKEN; WALKING DRAINS IT. A STONE SHIELD BESIDE HIS Z RING FILLS WITH IT.",
  a: [
    "TWO SLOW ANVIL SWINGS: A HEAVY BACKHAND, THEN A TWO-HANDED OVERHEAD THAT KNOCKS FOES BACK. HOLD A FOR AT LEAST HALF A CHARGE AND HE HEAVES THE ANVIL UP FOR AN ANVIL POUND INSTEAD: A GROUND SLAM AROUND HIM THAT KNOCKS EVERYONE BACK AND STUNS FOR A MOMENT.",
    "SWINGING DOESN'T BREAK YOUR GRIT, WALKING DOES. PLANT YOURSELF IN THEIR PATH AND MAKE THEM COME TO YOU.",
  ],
  b: [
    "HEADBUTT. A SHORT 6M CHARGE. THE FIRST CHAMPION HE MEETS IS CARRIED ON HIS TUSKS; IF THEY HIT A WALL, CLIFF OR BUILDING, BOTH STOP AND THEY'RE PINNED: EXTRA DAMAGE AND A 1.1S STUN. SOLDIERS ARE BOWLED ASIDE, AND NOTHING STUNS HIM MID-RUSH. AFTER THE CHARGE HE RUNS 30% FASTER FOR 2.5S.",
    "LOOK FOR CHAMPIONS STANDING WITH THEIR BACKS TO A WALL, A TOWER OR A CLIFF. IN THE OPEN IT'S A SHOVE; AGAINST STONE IT'S A KILL.",
  ],
  r: [
    "SWITCHEROO. HE SWAPS PLACES WITH A FRIENDLY CHAMPION WITHIN 8M (THE ONE IN MOST TROUBLE, OR WHERE YOUR STICK POINTS); THEY GET A 120 SHIELD, MORE PLUS A BURST OF SPEED FOR A MARKSMAN OR CASTER. WITH NO FRIEND IN REACH HE DIGS IN INSTEAD: ONE HOOF STAMPED DOWN, HIS GRIT FULL AT ONCE, AND FOR 3S NOTHING MOVES HIM, STUNS, SLOWS, ROOTS OR DEBUFFS HIM. HIS NEXT HIT, WHENEVER IT LANDS, DOES 60% MORE.",
    "A PEEL AND A RESCUE IN ONE BUTTON: YOUR PARTNER IS OUT, AND WHOEVER WAS CHASING THEM NOW HAS A BOAR IN THEIR FACE. ALONE, DIG IN WHEN THEY WIND UP THEIR BIG MOVE, THEN ANSWER WITH A HEADBUTT.",
  ],
  z: [
    "CRUSH SEASON. HE RAISES THE ANVIL AND SLAMS IT DOWN THREE TIMES, EACH SLAM BIGGER THAN THE LAST. THE THIRD FLATTENS EVERYTHING IN 4.4M: HEAVY DAMAGE, A LONG STUN, AND A HUGE HIT TO BUILDINGS. HE CAN'T BE STUNNED OR KNOCKED AWAY WHILE HE CRUSHES.",
    "HEADBUTT SOMEONE INTO A WALL FIRST: THEY'RE STILL SEEING STARS WHEN THE SECOND ANVIL LANDS. AND TOWERS HATE THE THIRD ONE.",
  ],
  picks: {
    stompin: "LAND FROM THE SWAP WITH A STOMP. THE CHASER GETS BLOWN BACK AND STUNNED.",
    houserules: "LONGER REACH, A BIGGER SHIELD AND A SHORTER COOLDOWN. THE PURE BODYGUARD.",
    batteringram: "A LONGER RUSH AND A LONGER PIN. WITH STOMP IN THE WALL HITS HARDER TOO.",
    thickhead: "WHILE YOU RUSH AND JUST AFTER, YOU TAKE LESS AND NOTHING MOVES YOU.",
    ironhide: "GRIT BUILDS TWICE AS FAST AND STOPS MORE. STAND STILL AND LAUGH.",
    trample: "THE OVERHEAD STUNS. EVERY SECOND SWING IS A REASON TO RUN.",
    vintageyear: "WIDER SLAMS, AND THE LAST ONE LEAVES A STICKY POOL OF CRUSHED GRAPES THAT SLOWS AND HURTS.",
  },
  evo: {
    r: "SWITCHEROO UPGRADES: A STOMP WHERE YOU LAND, OR MORE REACH AND SHIELD.",
    b: "HEADBUTT UPGRADES. BATTERING RAM GOES WITH STOMP IN, THICK HEAD WITH HOUSE RULES.",
    a: "SURVIVE (IRON HIDE) OR CONTROL (TRAMPLE).",
    z: "A BIGGER CRUSH THAT LEAVES THE GROUND STICKY.",
  },
  tactics:
    "WALK IN FRONT OF YOUR PARTNER AND YOUR SOLDIERS, THEN STOP AND LET THE GRIT BUILD. HEADBUTT ANYONE WHO STANDS NEAR A WALL, SWITCHEROO YOUR PARTNER OUT WHEN THEY'RE CAUGHT, AND SAVE CRUSH SEASON FOR A PINNED CHAMPION OR AN ENEMY TOWER.",
  fear: "BEING KITED. WREN AND REMNIL MAKE YOU WALK, AND WALKING MELTS YOUR GRIT. CURL BEHIND THE ANVIL AND CLOSE THE GAP WITH A HEADBUTT.",
};

TEXT.rider = {
  lore: "BRAMBLE CARRIES HONEY FROM THE HILL HIVES OF RUSSET HOLLOW TO WHOEVER ORDERED IT, AND SOME WHO DIDN'T. MEAD IS HER BUMBLEBEE, ROUGHLY THE SIZE OF A PONY AND TWICE AS STUBBORN. THE HOUSES HIRED THEM BECAUSE NOTHING STOPS A DELIVERY. NOT WALLS, NOT RIVERS, AND CERTAINLY NOT YOU.",
  role: "THE HONEY RIDER. A SUPPORT WHO FIGHTS FROM THE SADDLE: SHE KEEPS HER PARTNER ALIVE, GLUES FOES TO THE GROUND AND FLIES OVER ANYTHING IN HER WAY. SWEET TOOTH: SHE AND EVERY FRIEND WITHIN 7M SLOWLY HEAL. POLLEN: WHEN MEAD BUZZES PAST A FRIENDLY CHAMPION (HER DODGE) SHE DUSTS THEM, AND FOR 3S THEY MOVE 20% FASTER AND HIT 15% HARDER.",
  a: [
    "TWO WHACKS WITH HER BIG HONEY LADLE FROM THE SADDLE, THE SECOND A WIDE ONE THAT KNOCKS BACK. HOLD A AND LET GO TO FLING A DOLLOP OF HONEY UP TO 8M INSTEAD: IT HITS FOR 55 AND SLOWS EVERYONE IT SPLATTERS BY 40% FOR 2S.",
    "WHACK WHAT'S CLOSE, FLING AT WHAT RUNS. A SLOWED FOE CAN'T GET AWAY FROM YOUR PARTNER.",
  ],
  b: [
    "HONEY POT. LOBS A POT UP TO 8M: 38 DAMAGE (DOUBLE ON SOLDIERS), 65 HEALING FOR FRIENDS, THEN A HONEY POOL FOR 4S. FRIENDS IN IT HEAL; FOES ARE SLOWED, STUNG AND CAN'T DODGE. A BRUISER OR ASSASSIN PARTNER HITS 20% HARDER IN IT.",
    "THROW IT BETWEEN YOU AND THEM AND FIGHT IN IT. TAP B TO AIM AT WHO YOU FACE, HOLD B TO PLACE IT.",
  ],
  r: [
    "TAKE WING. MEAD LIFTS HER FOR 3S: STEER OVER WALLS, CLIFFS, WATER AND GAPS, UNTOUCHABLE. A DROPS A HONEY BOMB STRAIGHT DOWN (20 DAMAGE AND A SLOW IN 2M, ONE EVERY 0.7S). R AGAIN LANDS EARLY. LANDING HEALS FRIENDS WITHIN 4M FOR 55, THEN SHE TAKES 20% MORE DAMAGE FOR 1.5S.",
    "IT'S YOUR WAY IN, YOUR WAY OUT AND YOUR SHORTCUT. LAND BEHIND YOUR PARTNER, NOT IN FRONT OF THEIRS.",
  ],
  z: [
    "ROYAL JELLY. EVERY FRIEND WITHIN 10M HEALS 180 (SOLDIERS HALF), GETS A 100 SHIELD FOR 4S, SHAKES OFF SLOWS AND RUNS 25% FASTER FOR 5S.",
    "SAVE IT FOR THE MOMENT THE FIGHT TURNS. A FULL TEAM HEAL AND A SPEED BOOST WINS THE CHASE EITHER WAY.",
  ],
  picks: {
    stingerdive: "TAKE WING ENDS IN A DIVE THAT STUNS EVERYONE YOU LAND ON. NOW THE LANDING IS THEIR PROBLEM.",
    tailwind: "LONGER, FASTER FLIGHTS AND A BIGGER LANDING HEAL. FOR THE COURIER WHO NEVER WALKS.",
    beeswax: "THE POT SHIELDS EVERY FRIENDLY CHAMPION IT SPLASHES.",
    swarmpot: "ANGRY BEES IN THE POT: THE POOL STINGS FOES AND GROWS WIDER.",
    secondhelping: "LADLE HITS HEAL YOU AND THE SOLDIERS AROUND YOU.",
    honeydrizzle: "YOUR SECOND WHACK LEAVES A STICKY PUDDLE THAT SLOWS.",
    queensfeast: "A WIDER ROYAL JELLY WITH A BIGGER SHIELD AND A LONGER RUN.",
  },
  evo: {
    r: "TAKE WING UPGRADES: LAND HARD (STINGER DIVE), OR FLY FURTHER (TAILWIND).",
    b: "HONEY POT UPGRADES. BEESWAX GOES WITH STINGER DIVE, SWARM POT WITH TAILWIND.",
    a: "SUSTAIN (SECOND HELPING) OR CONTROL (HONEY DRIZZLE).",
    z: "THE QUEEN THROWS A BIGGER PARTY.",
  },
  tactics:
    "STICK TO YOUR PARTNER. POT EVERY FIGHT SO YOUR SIDE STANDS IN HONEY AND THEIRS CAN'T ROLL OUT OF IT, FLING HONEY AT ANYONE WHO TRIES TO RUN, AND KEEP ROYAL JELLY FOR WHEN IT MATTERS. DODGE THROUGH YOUR PARTNER AS THEY GO IN: POLLEN MAKES THEM FASTER AND HARDER-HITTING. WHEN IT GOES WRONG, TAKE WING OVER THE NEAREST WALL.",
  fear: "BEING CAUGHT ON THE GROUND RIGHT AFTER A LANDING. EVERYONE CAN SEE WHERE MEAD COMES DOWN, AND GRIM AND THE WARLORD WILL BE WAITING THERE.",
};

const STAT_WORD: Record<string, string> = {
  frail: "FRAIL",
  low: "LOW",
  mid: "AVERAGE",
  high: "HIGH",
  sturdy: "STURDY",
  swift: "VERY FAST",
};

/** Codex category glyph per champion (icons.ts). */
const CHAMP_GLYPH: Record<string, string> = {
  warlord: "slam",
  engineer: "ballista",
  raider: "dash",
  summoner: "summon",
  duelist: "parry",
  marksman: "heartseeker",
  friar: "keg",
  scribe: "manuscript",
  wreckwitch: "tide",
  architect: "fort",
  vintner: "anvil",
  rider: "honeypot",
};

function heroEntry(id: string): CodexEntry {
  const h = HEROES[id];
  const t = TEXT[id];
  const name = h.name.toUpperCase();
  const tal = TALENTS[id];
  const abil = (slot: "a" | "b" | "r" | "z", label: string): CodexPage => {
    const [text, tip] = t[slot];
    const call = h.abilities[slot].callout?.split("·")[0].trim();
    const cd = h.abilities[slot].cooldown;
    return {
      title: `${label}${call ? ` · ${call}` : ""}`,
      text: text + (cd && cd > 1 ? `  COOLDOWN ${cd}S.` : ""),
      tip,
      art: { kind: "shot", hero: id, slot },
    };
  };
  const evo = (slot: "r" | "b" | "a" | "z", level: number, label: string): CodexPage => {
    const list = tal[slot] ?? [];
    return {
      title: `LEVEL ${level} · ${label}`,
      text: t.evo[slot],
      art: { kind: "shot", hero: id, slot },
      picks: list.map((p) => ({ id: p.id, name: p.name, desc: t.picks[p.id] ?? p.desc, combo: p.combo })),
    };
  };
  return {
    cat: "CHAMPIONS",
    title: name,
    glyph: CHAMP_GLYPH[id] ?? "zone",
    pages: [
      {
        title: `${name} · THE LEGEND`,
        text: t.lore,
        tip: `HEALTH ${STAT_WORD[h.health] ?? h.health} · SPEED ${STAT_WORD[h.speed] ?? h.speed} · DAMAGE ${STAT_WORD[h.damage] ?? h.damage}`,
        art: { kind: "portrait", hero: id },
      },
      { title: `${name} · ROLE`, text: t.role, tip: `FEARS: ${t.fear}`, art: { kind: "portrait", hero: id } },
      abil("a", "A · ATTACK"),
      abil("b", "B · SECONDARY"),
      abil("r", "R · SPECIAL"),
      abil("z", "Z · SUPER"),
      evo("r", 2, "SPECIAL EVOLVES"),
      evo("b", 3, "SECONDARY EVOLVES"),
      evo("a", 4, "ATTACK EVOLVES"),
      evo("z", 5, "SUPER EVOLVES"),
      ...(COMBOS[id]
        ? [
            {
              title: `COMBO · ${COMBOS[id][0]}`,
              text: COMBOS[id][1],
              tip: COMBOS[id][2],
              art: { kind: "shot" as const, hero: id, slot: COMBOS[id][3] },
            },
          ]
        : []),
      { title: `${name} · HOW TO WIN`, text: t.tactics, art: { kind: "shot", hero: id, slot: "z" } },
    ],
  };
}

const MAP_DATA = import.meta.glob("../../data/maps/*.json", { eager: true, import: "default" }) as Record<
  string,
  { name: string }
>;

export function buildCodex(mapNames: string[]): CodexEntry[] {
  const sc = U.waves.spawnCost;
  const st = S.types;
  const e = M.economy;
  const sh = M.arena.shop;
  const rel = M.arena.relic;
  const td = (M as { tdm?: { killLimit?: number; respawnSeconds?: number } }).tdm ?? {};
  const og = M.arena.ogre;
  const can = M.arena.cannon;
  const entries: CodexEntry[] = [
    {
      cat: "BASICS",
      title: "HOW TO FIGHT",
      glyph: "combo",
      pages: [
        {
          title: "HITTING THINGS",
          text: "PRESS A TO SWING. KEEP PRESSING TO CHAIN A COMBO, THE LAST HIT IS ALWAYS THE BIG ONE. HOLD A TO CHARGE A HEAVY HIT. B, R AND Z ARE YOUR ABILITIES. Z ONLY WORKS WHEN THE METER IS FULL, AND IT FILLS AS YOU DEAL AND TAKE DAMAGE.",
          tip: "HITTING SOMEONE FROM BEHIND DEALS EXTRA DAMAGE. SO DOES HITTING THEM WHILE THEY'RE STUNNED.",
          art: { kind: "seal", glyph: "combo" },
        },
        {
          title: "NOT GETTING HIT",
          text: "HOLD L TO BLOCK: HITS FROM THE FRONT BARELY HURT, BUT YOU MOVE SLOWLY. L + X DODGES, A QUICK ROLL WHERE NOTHING CAN TOUCH YOU. THEN IT TAKES A MOMENT TO COME BACK, SO A ROLL WASTED ON A FEINT LEAVES YOU OPEN: BAIT THEIRS, KEEP YOURS. L + A SHOVES PEOPLE AWAY AND STUNS THEM FOR A MOMENT (SEE THE SHOVE). ARROWS AND HARPOONS DON'T GO THROUGH WALLS OR BUILDINGS, SO DUCK BEHIND ONE. MAGIC BOLTS DO.",
          tip: "A BLOCKER IS VERY ANNOYING. SHOVE THEM, OR WALK AROUND AND HIT THEIR BACK.",
          art: { kind: "seal", glyph: "parry" },
        },
        {
          title: "THE SHOVE",
          text: "L + A SHOVES EVERYONE IN FRONT OF YOU. IT BARELY HURTS, BUT IT DOES THINGS NOTHING ELSE DOES: IT BREAKS A BLOCK, IT STUNS FOR A MOMENT (WHICH CANCELS A SWING, A RECALL, A JUMP OR A CHANNEL, AND MAKES A GRUDGE CARRIER DROP IT), AND IT THROWS THEM WELL BACK. SHOVE SOMEONE INTO A WALL OR CLIFF FOR A WALL SPLAT: EXTRA DAMAGE AND A LONGER STUN. SHOVE THEM INTO A RUINS PIT OR A FROSTCROSS CHASM AND THEY'RE GONE.",
          tip: "A STUNNED FOE TAKES EXTRA FROM FLURRY AND QUAKE, AND THE WARLORD CAN HEAVE THEM. SHOVE, THEN PUNISH.",
          art: { kind: "seal", glyph: "combo" },
        },
        {
          title: "DYING",
          text: `YOU COME BACK AT YOUR KEEP AFTER A FEW SECONDS, LONGER THE LATER IT GETS. IF ENEMY CHAMPIONS ARE IN YOUR BASE WHEN YOU COME BACK, YOU LAND HEAVY AND THROW THEM OUT THROUGH THE NEAREST GATE. KEEPS ARE TOUGH EARLY ON AND TAKE FULL DAMAGE FROM ABOUT FIVE MINUTES IN. YOUR KEEP'S SHIELD ONLY HOLDS WHILE EVERY HOME PAD HAS ONE OF YOUR BUILDINGS ON IT: LOSE ONE AND THE SHIELD IS DOWN UNTIL YOU REBUILD. WHILE YOUR HOUSE HAS MORE CHAMPIONS STANDING, YOUR SOLDIERS MARCH FASTER. LOSING A CHAMPION SPILLS A THIRD OF YOUR GRAIN. AND AS REGULATION RUNS DOWN THE WAR DRUMS BUILD: OUTPOSTS SEND FASTER, SOLDIERS COST LESS AND HIT HARDER, AND SHIELDS CATCH LESS, UNTIL SUDDEN DEATH. EVERY DEATH COSTS YOUR TEAM ${e.loss.heroDeath} GOLD AND GIVES THE ENEMY A ${e.bounty.hero} GOLD BOUNTY, SO TRY NOT TO DO IT. YOUR MOVES COME BACK READY, BUT A HALF-CHARGED SUPER IS LOST. A FULL ONE YOU KEEP.`,
          tip: "IF YOU'RE BEHIND YOU LOSE LESS GOLD, AND IN FREE FOR ALL YOU ALSO RESPAWN FASTER. COMEBACKS ARE REAL.",
          art: { kind: "seal", glyph: "none", color: "#4a3a2a" },
        },
        {
          title: "CLIFFS AND HIGH GROUND",
          text: "YOU CAN DROP OFF A CLIFF, BUT YOU CAN'T CLIMB ONE. FIND THE RAMP. TROOPS SHOOTING UPHILL MISS MORE OFTEN, SO HIGH GROUND IS WORTH HOLDING.",
          tip: "GRIM IGNORES MOST OF THIS. HE CLIMBS LIKE A GOAT.",
          art: { kind: "seal", glyph: "peak" },
        },
      ],
    },
    {
      cat: "BASICS",
      title: "LEVELLING UP",
      glyph: "rally",
      pages: [
        {
          title: "EXPERIENCE",
          text: "YOU EARN EXPERIENCE BY HURTING HEROES, KILLING TROOPS AND BREAKING BUILDINGS, PLUS A SLOW TRICKLE JUST FOR BEING ALIVE. EACH LEVEL ALSO GIVES YOU A BIT MORE HEALTH AND DAMAGE.",
          tip: "FIGHTING THE OTHER HERO IS THE FASTEST WAY TO LEVEL. ALSO THE FASTEST WAY TO DIE.",
          art: { kind: "seal", glyph: "rally" },
        },
        {
          title: "EVOLUTIONS",
          text: "AT LEVELS 2, 3, 4 AND 5 ONE OF YOUR ABILITIES EVOLVES: SPECIAL (R), THEN SECONDARY (B), THEN ATTACK (A), THEN SUPER (Z). FOR EACH ONE YOU PICK ONE OF TWO VERSIONS WITH LEFT OR RIGHT ON THE ORDERS STICK.",
          tip: "THE CHOICE IS PERMANENT FOR THE MATCH. READ BOTH.",
          art: { kind: "seal", glyph: "works" },
        },
        {
          title: "SYNERGIES",
          text: "YOUR SECONDARY EVOLUTION ALWAYS HAS A BONUS IF IT MATCHES A CERTAIN SPECIAL EVOLUTION. THE CHAMPION PAGES IN THIS BOOK LIST EVERY PAIR. IN SHORT: DECIDE YOUR PLAN AT LEVEL 2 AND STICK TO IT AT LEVEL 3.",
          tip: "MIXING AND MATCHING STILL WORKS, YOU JUST MISS THE BONUS.",
          art: { kind: "seal", glyph: "hex" },
        },
      ],
    },
    {
      cat: "BASICS",
      title: "BUILDING A TEAM",
      glyph: "banner",
      pages: [
        {
          title: "SEVEN KINDS OF CHAMPION",
          text: "EVERY CHAMPION HAS A CLASS (THE LITTLE MARK ON THEIR CARD). ASSASSINS (GRIM, FRANCOIS) DIVE IN AND BURST SOMEONE. BRUISERS (WARLORD, KELP) WIN TRADES UP CLOSE. TANKS (THORN, HOGSHEAD) TAKE THE HITS. MARKSMEN (WREN, TADWICK) AND CASTERS (REMNIL, HOLLIN) FIGHT FROM RANGE. SUPPORTS (MADDOCK, BRAMBLE) KEEP PEOPLE ALIVE. BUILDERS (STIG, HOOT) WIN WITH THINGS THEY PUT DOWN.",
          tip: "NO CLASS IS BEST. EACH ONE BEATS SOME AND LOSES TO OTHERS.",
          art: { kind: "seal", glyph: "rally" },
        },
        {
          title: "A GOOD DUO",
          text: `THE SAFE RECIPE: ONE CHAMPION WHO CAN TAKE A BEATING UP FRONT, AND ONE WHO DEALS DAMAGE FROM RANGE OR KEEPS THE FIRST ONE ALIVE. THORN AND WREN. HOGSHEAD AND HOLLIN. WARLORD AND MADDOCK. THE FRONT ONE HOLDS THEIR ATTENTION, THE BACK ONE DOES THE WORK. THEN STICK TOGETHER: MOST LOST FIGHTS ARE ONE CHAMPION CAUGHT ALONE BY TWO. AND FROM THE THIRD MINUTE, A HOUSE WITH BOTH CHAMPIONS DOWN AT ONCE IS ROUTED: ITS KEEP LOSES ${Math.round((M.rout?.keepFrac ?? 0.12) * 100)}% STRAIGHT THROUGH ANY SHIELD.`,
          tip: "WARLORD AND MADDOCK IS AN EASY FIRST DUO: BOTH TOUGH, NOTHING FIDDLY.",
          art: { kind: "portrait", hero: "friar" },
        },
        {
          title: "WHY TWO DIVERS LOSE",
          text: "TWO ASSASSINS OR BRUISERS TOGETHER HIT HARD AND WIN A LOT AGAINST SQUISHY OR SLOW TEAMS. BUT A TANK SOAKS THEIR BURST, RANGE KITES THEM, AND A HEALER UNDOES IT. TWO RANGED CHAMPIONS HAVE THE OPPOSITE PROBLEM: ANYONE WHO REACHES THEM WINS. A HEALER ON THE OTHER SIDE MEANS FOCUS THE HEALER FIRST, OR BRING KELP, WHOSE BILGE STOPS ALL HEALING.",
          tip: "IN OUR TESTS GRIM AND FRANCOIS BEAT KELP AND HOOT 8 TIMES IN 10, AND LOST TO WREN AND HOGSHEAD 9 TIMES IN 10.",
          art: { kind: "portrait", hero: "raider" },
        },
        {
          title: "AFTER A LOSS",
          text: "LOOK AT WHAT BEAT YOU, THEN CHANGE ONE CHAMPION, NOT BOTH. LOST TO RANGE? A TANK OR A HEALER SOAKS IT. LOST TO A TANK? RANGE WEARS IT DOWN. LOST TO DIVERS? SOMETHING THAT PUNISHES MELEE: HOOT'S FORTS, WARLORD'S SLAM, STIG'S TOWERS. THE RESULTS SCREEN GIVES YOU A TIP AFTER EVERY LOSS.",
          tip: "ONE ON ONE, THE TIP NAMES THE CHAMPIONS WHO BEAT THE ONE THAT BEAT YOU.",
          art: { kind: "portrait", hero: "marksman" },
        },
      ],
    },
    {
      cat: "ARMY",
      title: "YOUR TROOPS",
      glyph: "banner",
      pages: [
        {
          title: "THREE KINDS OF SOLDIER",
          text: `GRUNTS (${sc.grunt} GRAIN): CHEAP, QUICK, GOOD AT HACKING BRUTES APART. ARCHERS (${sc.ranged} GRAIN): SHOOT FROM RANGE, SHRED GRUNTS. BRUTES (${sc.heavy} GRAIN): BIG, SLOW, SMASH ARCHERS AND BUILDINGS.`,
          tip: "GRUNTS BEAT BRUTES. ARCHERS BEAT GRUNTS. BRUTES BEAT ARCHERS. A MIXED ARMY BEATS ANY SINGLE KIND.",
          art: { kind: "scene", scene: "troops" },
        },
        {
          title: "VETERANS",
          text: "TROOPS THAT GET KILLS RANK UP: VETERAN, ELITE, THEN HEROIC. EACH RANK HITS HARDER, HAS MORE HEALTH AND HEALS A BIT. HEROIC TROOPS SLOWLY REGENERATE.",
          tip: `KEEPING TROOPS ALIVE MATTERS. THE ARMY CAP IS ${U.popCap}, SO DON'T THROW THEM AWAY.`,
          art: { kind: "seal", glyph: "rank", color: "#c8a020" },
        },
      ],
    },
    {
      cat: "ARMY",
      title: "GIVING ORDERS",
      glyph: "rally",
      pages: [
        {
          title: "THE FOUR ORDERS",
          text: "FLICK THE ORDERS STICK (C, OR THE ARROW KEYS). UP: ATTACK, MARCH ON THE ENEMY KEEP. FLICK UP AGAIN WHILE ATTACKING TO PICK A LANE (TOP, MIDDLE, BOTTOM, THEN ANY), OR IN FREE FOR ALL WHICH HOUSE TO HIT. A BIG ATTACK SENDS A FEW SOLDIERS ROUND ANOTHER LANE ON ITS OWN. LEFT: GUARD, THE GRUNTS AND BRUTES STAND BETWEEN YOU AND THE NEAREST THREAT AND THE ARCHERS KEEP BEHIND YOU. RIGHT: SPLIT, GRUNTS AND BRUTES ATTACK AS A SECOND FRONT WHILE THE ARCHERS GUARD YOU. DOWN: DEFEND, GO TO WHICHEVER OF YOUR BUILDINGS IS UNDER ATTACK (OR GUARD THE GATES AT HOME). SOLDIERS ALSO THINK FOR THEMSELVES: THEY SPREAD OUT OVER TARGETS, ARCHERS STEP BACK FROM MELEE, AND MARCHERS WAIT FOR THEIR PACK.",
          tip: "D-PAD LEFT AND RIGHT PICK WHO OBEYS: EVERYONE, OR JUST GRUNTS, ARCHERS OR BRUTES.",
          art: { kind: "seal", glyph: "rally" },
        },
        {
          title: "WHEN TO USE WHAT",
          text: "ATTACK WHEN YOU HAVE A BIG ARMY. FOLLOW WHEN YOU WANT TO PUSH TOGETHER WITH YOUR HERO. DEFEND WHEN SOMEONE IS HITTING YOUR TOWERS OR BREAKING INTO YOUR BASE: YOUR TROOPS RUN TO THE BUILDING UNDER ATTACK, OR SPLIT ACROSS EVERY ENTRANCE WHEN NOTHING IS. SOLDIERS ALWAYS FIGHT BACK AGAINST WHATEVER HITS THEM ON THE WAY. HOLD WHEN YOU WANT A WALL OF BODIES SOMEWHERE SPECIFIC.",
          tip: "ARCHERS ON HOLD BEHIND GRUNTS ON ATTACK IS A CLASSIC FOR A REASON.",
          art: { kind: "seal", glyph: "wall" },
        },
      ],
    },
    {
      cat: "ARMY",
      title: "OUTPOSTS",
      glyph: "castle",
      pages: [
        {
          title: "WHERE TROOPS COME FROM",
          text: `TROOPS ONLY COME FROM OUTPOSTS. BUILD THEM ON PADS WITH X: A BARRACKS MAKES GRUNTS, A RANGE MAKES ARCHERS, A FOUNDRY MAKES BRUTES. EACH COSTS ${st.barracks.cost} GOLD. EACH OUTPOST KEEPS ITS OWN CLOCK FROM THE MOMENT IT'S BUILT: A BARRACKS SENDS A GRUNT EVERY ${st.barracks.cadence} SECONDS, A RANGE AN ARCHER EVERY ${st.range.cadence}, A FOUNDRY A BRUTE EVERY ${st.foundry.cadence}, AND UPGRADED ONES ARE A THIRD FASTER. YOU PAY GRAIN FOR EACH SOLDIER AS IT COMES OUT. WHEN ONE OF ITS SOLDIERS DIES, THAT OUTPOST TAKES A MOMENT LONGER TO SEND THE NEXT. WHILE ANY CHAMPION OF YOUR HOUSE IS DOWN, EVERY OUTPOST STOPS, AND WHEN THEY'RE BACK EACH ONE STARTS ITS COUNT FROM ZERO.`,
          tip: "NO GRAIN, NO TROOPS. IF YOUR OUTPOSTS GO QUIET, CHECK YOUR SACK.",
          art: { kind: "seal", glyph: "castle" },
        },
        {
          title: "MIXED OUTPOSTS",
          text: `SOME FIELDS ARE TOO CRAMPED FOR SPECIALISTS. THERE YOU CAN ONLY BUILD A PLAIN OUTPOST, ${st.outpost.cost} GOLD, AND EVERY SOLDIER IT SENDS IS PICKED AT RANDOM: ABOUT ${Math.round((st.outpost.mix?.grunt ?? 0) * 100)}% GRUNTS, ${Math.round((st.outpost.mix?.ranged ?? 0) * 100)}% ARCHERS AND ${Math.round((st.outpost.mix?.heavy ?? 0) * 100)}% BRUTES. RIGHT NOW THAT'S THE RUINS.`,
          tip: "YOU DON'T GET TO CHOOSE. NEITHER DO THEY. IT'S VERY DEMOCRATIC.",
          art: { kind: "seal", glyph: "castle" },
        },
        {
          title: "UPGRADES AND FORWARD OUTPOSTS",
          text: `UPGRADE AN OUTPOST (Y AT ITS PAD, ${st.barracks.upgradeCost} GOLD) TO SEND SOLDIERS FASTER, WITH BETTER STATS. OUTPOSTS ON FORWARD OR NEUTRAL PADS MAKE TOUGHER SOLDIERS, AND STANDING NEAR ONE HEALS YOU LIKE YOUR OWN TURF.`,
          tip: "A FORWARD OUTPOST IS A SECOND HOME. LOSE IT AND YOU'LL FEEL IT.",
          art: { kind: "seal", glyph: "banner" },
        },
      ],
    },
    {
      cat: "ARMY",
      title: "GOLD AND GRAIN",
      glyph: "repair",
      pages: [
        {
          title: "TWO PURSES",
          text: `GOLD PAYS FOR BUILDINGS, UPGRADES AND THE KEEP SHOP. GRAIN FEEDS YOUR ARMY: EVERY SOLDIER YOUR OUTPOSTS SEND COSTS GRAIN, EVERY TOWER SHOT AND PULSE COSTS GRAIN, AND EVERY LIVING SOLDIER KEEPS EATING (BRUTES THE MOST). GRAIN GROWS FROM YOUR KEEP AND EVERY BUILDING YOU OWN, MORE FOR UPGRADED ONES AND MUCH MORE FOR BUILDINGS OUT ON FORWARD AND MIDDLE PADS, SO THE ARMY YOU CAN KEEP IS AS BIG AS YOUR BUILDINGS CAN FEED: LOSE BUILDINGS AND IT SHRINKS. BOTH ARE NEXT TO YOUR KEEP GEM; THE NUMBER AFTER THE SACK IS YOUR GRAIN PER SECOND AFTER UPKEEP (RED WHEN YOUR SOLDIERS EAT MORE THAN YOU GROW).`,
          tip: "BUILDINGS FEED YOU, KILLS PAY YOU. A HOUSE THAT ONLY BUILDS STARVES FOR GOLD, A HOUSE THAT ONLY FIGHTS STARVES FOR GRAIN.",
          art: { kind: "seal", glyph: "repair" },
        },
        {
          title: "MAKING GOLD",
          text: `GOLD COMES FROM KILLING. EVERY ENEMY SOLDIER PAYS A FEW COINS, A HERO ${e.bounty.hero}, A BUILDING ${e.bounty.structure}. YOUR KEEP ADDS A TRICKLE OF ${e.income} A SECOND SO A QUIET START ISN'T FROZEN.`,
          tip: "YOUR ARMY IS YOUR INCOME. A WAVE THAT DIES FOR NOTHING IS GOLD YOU NEVER SEE.",
          art: { kind: "seal", glyph: "quake" },
        },
        {
          title: "MAKING GRAIN",
          text: `GRAIN COMES FROM YOUR BUILDINGS. YOUR KEEP GROWS ${e.grain?.base ?? 0} A SECOND, AND EVERY FINISHED TOWER OR OUTPOST ADDS ${(e.grain?.perLevel ?? []).join(", ")} AT LEVEL ${(e.grain?.perLevel ?? []).map((_, k) => k + 1).join(", ")}. GRAIN YOU DON'T NEED IS NOT WASTED: ABOVE ${e.grain?.surplus ?? 0} IN THE SACK, EVERY OUTPOST WORKS FASTER. RUN OUT AND YOUR OUTPOSTS GO QUIET AND YOUR TOWERS FIRE AT A CRAWL.`,
          tip: "UPGRADING ISN'T JUST A STRONGER BUILDING. IT'S MORE BREAD.",
          art: { kind: "seal", glyph: "castle" },
        },
        {
          title: "LOSING IT",
          text: `EVERY TIME YOUR HERO DIES YOUR TEAM LOSES ${e.loss.heroDeath} GOLD. EVERY TOWER YOU LOSE ON YOUR OWN SIDE COSTS ${e.loss.tower} (ONE ON A NEUTRAL PAD COSTS NOTHING). AND WHEN THE ENEMY FELLS ONE OF YOUR TOWERS, THEIR WHOLE ARMY RALLIES: +${pct(e.rally.damageMul)} DAMAGE AND +${pct(e.rally.speedMul)} SPEED FOR ${e.rally.seconds} SECONDS.`,
          tip: "THE SAME GOES FOR YOU. KNOCK A TOWER DOWN AND CHARGE WHILE THE RALLY LASTS.",
          art: { kind: "seal", glyph: "quake" },
        },
      ],
    },
    {
      cat: "BASE",
      title: "TOWERS",
      glyph: "turret",
      pages: [
        {
          title: "THE THREE TOWERS",
          text: `BUILD WITH Y AT A PAD. DAMAGE TOWER: SHOOTS BOLTS. CONTROL TOWER: PULSES AROUND ITSELF, SLOWS AND SHOVES. SUPPORT TOWER: HEALS FRIENDS AND MAKES THEM HIT HARDER. EACH COSTS ${st.damage.cost}, UPGRADES ${st.damage.upgradeCost}.`,
          tip: "THERE'S NO LIMIT. IF YOU HAVE THE PADS AND THE GOLD, BUILD.",
          art: { kind: "seal", glyph: "turret" },
        },
        {
          title: "WHO TOWERS SHOOT",
          text: "TOWERS SHOOT YOUR TROOPS FIRST. THEY ONLY SWITCH TO YOU IF YOU WALK IN WITH NO TROOPS AROUND, OR IF YOU HIT SOMETHING OF THEIRS NEAR THE TOWER.",
          tip: "NEVER DIVE A TOWER ALONE. WALK IN BEHIND YOUR SOLDIERS AND LET THEM SOAK THE BOLTS.",
          art: { kind: "seal", glyph: "shoot" },
        },
        {
          title: "LANE TOWERS",
          text: "TOWERS ON FORWARD AND NEUTRAL PADS ARE MUCH TOUGHER, HIT MUCH HARDER AND SLOW HEROES THEY SHOOT. YOU CAN'T JUST JOG PAST THEM. TOWERS INSIDE YOUR BASE ARE NORMAL ONES.",
          tip: "TAKE THE LANE TOWER FIRST, THEN THE ROAD IS OPEN.",
          art: { kind: "seal", glyph: "wall" },
        },
        {
          title: "LEVEL 3 TOWERS",
          text: `A LEVEL 2 DAMAGE OR CONTROL TOWER CAN GO ONE STEP FURTHER. HOLD Y AT IT AND PICK ONE OF THREE FOR ${st.damage.specCost ?? 250} GOLD. EACH ONE CHANGES HOW THE TOWER FIGHTS, NOT JUST HOW HARD, AND YOU CAN SEE WHICH ONE IT IS FROM ACROSS THE FIELD.`,
          tip: "LOOK AT WHAT THEY'RE SENDING. FIREPOTS EAT GRUNT SWARMS, A BALLISTA SKEWERS A LINE, A GRAVITY WELL HOLDS THEM FOR YOUR ARMY.",
          art: { kind: "seal", glyph: "turret", color: "#c8a020" },
        },
        ...[
          ...(st.damage.specs ?? []).map((sp) => ["DAMAGE", sp] as const),
          ...(st.control.specs ?? []).map((sp) => ["CONTROL", sp] as const),
        ].map(([kind, sp]) => ({
          title: `${kind} · ${sp.name}`,
          text: sp.blurb,
          tip: SPEC_TIPS[sp.id] ?? "",
          art: { kind: "scene" as const, scene: `tower:${sp.id}` },
        })),
        {
          title: "RUBBLE",
          text: `A DESTROYED BUILDING LEAVES RUBBLE FOR ${S.rubbleSeconds} SECONDS. THE OWNER CAN'T REBUILD THERE UNTIL IT CLEARS, BUT THE ENEMY CAN BUILD STRAIGHT ON IT.`,
          tip: "STEAL THEIR PAD THE MOMENT IT FALLS.",
          art: { kind: "seal", glyph: "quake", color: "#6a6058" },
        },
      ],
    },
    {
      cat: "BASE",
      title: "KEEP AND SHOP",
      glyph: "castle",
      pages: [
        {
          title: "THE KEEP",
          text: "YOUR KEEP IS YOUR LIFE. LOSE IT AND YOU LOSE. IF TIME RUNS OUT, WHOEVER DID MORE DAMAGE TO THE OTHER KEEP WINS. YOUR KEEP HAS A WARD THAT SOAKS DAMAGE AT FIRST.",
          tip: "EVERY HIT ON THEIR KEEP COUNTS. EVEN ONE BRUTE SMACKING IT ADDS UP.",
          art: { kind: "scene", scene: "keep" },
        },
        {
          title: "THE SHOP",
          text: `PRESS Y AT YOUR KEEP. BOMB (${sh.bomb.cost}): THROW IT, OR STICK IT TO A BUILDING. IT FLATTENS A TOWER AND DOES ${sh.bomb.coreDamage} TO A KEEP. YOUR HOUSE CAN BUY ONE EVERY ${(sh.bomb as { cooldown?: number }).cooldown ?? 20} SECONDS, AND YOU CAN'T RIDE A JUMP PAD WHILE HOLDING ONE. SHIELD (${sh.ward.cost}): PATCHES A QUARTER OF YOUR KEEP'S WARD BACK. CANNON (${sh.cannon.cost}): AIM ${sh.cannon.shots} SHELLS ANYWHERE ON THE FIELD.`,
          tip: "A BOMB THROWN INTO A CLUMP OF TROOPS DELETES THEM. THEY DON'T LIKE THAT.",
          art: { kind: "seal", glyph: "trap" },
        },
        {
          title: "RECALL",
          text: "AWAY FROM YOUR KEEP, PRESS Y TO RECALL: 4 SECONDS LATER YOU'RE TELEPORTED HOME. YOU CAN STILL WALK WHILE IT CHANNELS, SLOWLY. ATTACKING, USING AN ABILITY, DODGING OR GETTING HIT CANCELS IT. ONCE PER LIFE.",
          tip: "RECALL THE MOMENT YOU SEE SOMEONE SNEAKING INTO YOUR BASE, NOT WHEN THE KEEP IS ON FIRE.",
          art: { kind: "seal", glyph: "leap" },
        },
      ],
    },
    {
      cat: "BASE",
      title: "BUILDING",
      glyph: "works",
      pages: [
        {
          title: "PADS",
          text: `EVERY BUILDING GOES ON A PAD. HOME PADS ARE IN YOUR BASE, FORWARD PADS ARE OUT IN YOUR HALF, NEUTRAL PADS ARE IN THE MIDDLE. BUILDING TAKES ABOUT ${S.buildSeconds} SECONDS, FASTER WITH TWO HEROES OR WITH TROOPS NEARBY.`,
          tip: "BUILT HALF A TOWER AND RAN? IT KEEPS BUILDING SLOWLY ON ITS OWN WHEN TROOPS ARE CLOSE.",
          art: { kind: "seal", glyph: "pad" },
        },
        {
          title: "WHAT TO BUILD FIRST",
          text: "ONE OUTPOST FOR TROOPS, THEN A TOWER ON YOUR FORWARD PAD, THEN A SECOND OUTPOST. AFTER THAT, UPGRADE WHAT YOU HAVE BEFORE BUILDING NEW STUFF IN THE MIDDLE.",
          tip: "STIG BUILDS EVERYTHING CHEAPER. IF YOU HAVE A STIG, LET HIM BUILD.",
          art: { kind: "seal", glyph: "works" },
        },
      ],
    },
    {
      cat: "ARENA",
      title: "THE GRUDGE",
      glyph: "hex",
      pages: [
        {
          title: "THE RELIC",
          text: `AFTER ${rel.firstSeconds} SECONDS THE GRUDGE APPEARS IN THE MIDDLE OF THE FIELD. PICK IT UP AND CARRY IT HOME. YOU'RE SLOWER WHILE CARRYING AND CAN'T ATTACK. PRESS L TO DROP IT.`,
          tip: "SEND SOMEONE WITH ESCORTS. A LONE CARRIER IS A GIFT. IF THEY'RE ABOUT TO CATCH YOU, DROP IT BEHIND A FRIEND.",
          art: { kind: "scene", scene: "grudge" },
        },
        {
          title: "ENSHRINING IT",
          text: `STAND AT A TOWER, OUTPOST OR YOUR KEEP FOR ${rel.enshrineSeconds} SECONDS TO ENSHRINE IT. A TOWER SHRINE HITS HARDER AND FURTHER, AN OUTPOST SHRINE SENDS EXTRA, TOUGHER TROOPS, THE KEEP SHRINE REGROWS ITS WARD. ANY SHRINE GIVES ${pct(rel.incomeMul)} MORE GOLD.`,
          tip: `THE ENEMY CAN STEAL IT BACK BY STANDING ON IT FOR ${rel.stealSeconds} SECONDS. GUARD YOUR SHRINE.`,
          art: { kind: "seal", glyph: "castle", color: "#c8a020" },
        },
      ],
    },
    {
      cat: "ARENA",
      title: "THE OGRE",
      glyph: "slam",
      pages: [
        {
          title: "BIG, GREEN, NEUTRAL",
          text: `AFTER ${og.firstSeconds} SECONDS AN OGRE WAKES UP SOMEWHERE ON THE FIELD. ${og.hp} HEALTH AND AN ENORMOUS CLUB. HE HATES EVERYONE EQUALLY, WHICH IS VERY FAIR OF HIM. HE STOMPS UP AND DOWN HIS BEAT, STOPS AT EACH END TO LOOK AROUND, AND ONLY REALLY WATCHES WHAT'S IN FRONT OF HIM. GET SPOTTED AND HE CHARGES UNTIL YOU'RE WELL OFF HIS BEAT.`,
          tip: "DON'T FIGHT HIM AT THE SAME TIME AS THE ENEMY. LET THEM WEAKEN HIM FIRST.",
          art: { kind: "unit", type: "ogre" },
        },
        {
          title: "THE BLESSING",
          text: `KILL HIM AND YOUR TEAM GETS ${og.bounty} GOLD AND A BLESSING FOR ${og.blessSeconds} SECONDS: MORE DAMAGE, MORE SPEED, A BIG CHUNK OF EXPERIENCE AND SOME HEALING. HE COMES BACK ${og.respawnSeconds} SECONDS LATER.`,
          tip: "A BLESSED PUSH RIGHT AFTER THE OGRE IS THE STRONGEST MOVE IN THE GAME.",
          art: { kind: "seal", glyph: "rally", color: "#2a7a20" },
        },
      ],
    },
    {
      cat: "ARENA",
      title: "THE CANNON",
      glyph: "ballista",
      pages: [
        {
          title: "INCOMING",
          text: `FROM ${can.firstSeconds} SECONDS ON, EVERY ${can.everySeconds} SECONDS OR SO, A WILD CANNON SHELLS THE FIELD. YOU GET A WARNING CIRCLE A MOMENT BEFORE EACH SHELL LANDS. ${can.damage} TO TROOPS AND HEROES, ${can.structureDamage} TO BUILDINGS, NEVER THE KEEP.`,
          tip: "WALK OUT OF THE CIRCLES. THIS IS ALL OF THE ADVICE.",
          art: { kind: "seal", glyph: "ballista" },
        },
      ],
    },
    {
      cat: "ARENA",
      title: "FREE FOR ALL",
      glyph: "banner",
      pages: [
        {
          title: "FOUR HOUSES",
          text: `SOME FIELDS HAVE FOUR KEEPS: BLUE, RED, YELLOW AND GREEN. EVERY HOUSE GETS ONE CHAMPION, UP TO ${U.popCap} SOLDIERS AND ZERO FRIENDS. EVERY PAD OUTSIDE THE KEEPS IS NEUTRAL, SO WHOEVER BUILDS ON IT FIRST OWNS IT, UNTIL SOMEONE ELSE DISAGREES WITH A BRUTE. ARMIES ARE BIGGER HERE: TROOPS COME EVERY 12 SECONDS, OUTPOSTS AND SOLDIERS COST A QUARTER LESS, THE CAP IS HALF AGAIN AS HIGH, AND THREE ARCHERS STAND GUARD AT YOUR KEEP SO YOU CAN GO FIGHT. ORDER ATTACK AGAIN WHILE YOUR TROOPS ARE ALREADY ATTACKING TO PICK WHICH HOUSE THEY MARCH ON: EACH PRESS MOVES TO THE NEXT HOUSE, THEN BACK TO WHOEVER IS NEAREST. THE ATTACK BADGE TURNS THAT HOUSE'S COLOUR. CHAMPION KILLS PAY TWO AND A HALF TIMES THE GOLD, TOWERS LEFT ALONE FOR A FEW SECONDS PATCH THEMSELVES UP FAST AND LOSING ONE COSTS NOTHING. FALLEN CHAMPIONS WAIT LONGER TO COME BACK HERE (18 SECONDS, GROWING AS THE MATCH GOES ON), SO A GOOD FIGHT IS A REAL CHANCE TO TAKE A KEEP.`,
          tip: `THE GRUDGE STILL WAKES IN THE MIDDLE AFTER ${rel.firstSeconds} SECONDS. ALL FOUR HOUSES CAN SEE IT. ALL FOUR WANT IT. THIS GOES ABOUT AS WELL AS YOU'D THINK.`,
          art: { kind: "seal", glyph: "banner", color: "#2a8a3a" },
        },
        {
          title: "JUMP PADS",
          text: "FREE FOR ALL FIELDS ARE BIG, SO THEY'RE DOTTED WITH SPRING PADS. STAND ON ONE AND HOLD A: IT WINDS UP FOR A SECOND AND FLINGS YOU ACROSS THE MAP (GET HIT WHILE IT WINDS UP AND IT FIZZLES). AFTER EACH JUMP THE PAD NEEDS 5 SECONDS TO RESET, SO NOBODY CAN FOLLOW YOU THROUGH IT. ROUTES: FROM THE MIDDLE BACK TO YOUR KEEP, FROM YOUR KEEP TO THE MIDDLE, AND BETWEEN THE ARMS. THEY ONLY GO ONE WAY, SO THE TRIP BACK IS A DIFFERENT PAD AND A BIT OF A WALK. THE MINIMAP SHOWS WHERE EACH ONE LANDS. YOU CAN'T TAKE THE GRUDGE ALONG.",
          tip: "YOUR ARMY CAN'T JUMP. YOU CAN. USE IT TO GET BACK TO A FIGHT YOUR SOLDIERS ARE LOSING.",
          art: { kind: "seal", glyph: "leap", color: "#c8a020" },
        },
        {
          title: "LAST HOUSE STANDING",
          text: "LOSE YOUR KEEP AND YOUR HOUSE IS OUT. YOUR TOWERS CRUMBLE, YOUR SOLDIERS WANDER HOME AND YOUR CHAMPION STAYS DOWN, SULKING. THE LAST HOUSE WITH A KEEP WINS. IF THE BELL TOLLS FIRST, THE HOUSE STILL STANDING THAT DID THE MOST DAMAGE TO OTHER KEEPS TAKES IT.",
          tip: `TWO HOUSES FIGHTING IS GREAT NEWS FOR THE OTHER TWO. A FALLEN CHAMPION STILL PAYS ${e.bounty.hero} GOLD TO WHOEVER DID IT, SO EVERYONE IS ALWAYS LOOKING AT YOU.`,
          art: { kind: "seal", glyph: "castle", color: "#c89a14" },
        },
        {
          title: "TEAM DEATHMATCH",
          text: `EIGHT CHAMPIONS, TWO HOUSES, NO KEEPS, NO TOWERS, NO SOLDIERS, NO GOLD. THE FIRST HOUSE TO ${td.killLimit ?? 20} CHAMPION KILLS WINS (SET IT IN THE RULES); IF THE BELL TOLLS FIRST, MOST KILLS WINS, AND A TIE GOES TO SUDDEN DEATH: NEXT KILL WINS. FALL AND YOU'RE BACK IN ${td.respawnSeconds ?? 2} SECONDS, SOMEWHERE AWAY FROM THE ENEMY. THE GRUDGE STILL WAKES IN THE MIDDLE, BUT HERE IT JUST MAKES ITS CARRIER NASTIER: MORE DAMAGE, LESS DAMAGE TAKEN, A LITTLE FASTER, SLOWLY HEALING. YOU KEEP FIGHTING WITH IT; IT DROPS WHEN YOU DIE, AND AFTER 15 SECONDS IT SLIPS AWAY BACK TO THE MIDDLE ANYWAY. WITH NO ARMY TO ORDER, THE D-PAD TURNS YOUR CAMERA LEFT AND RIGHT, AND FLICKING THE C-STICK CALLS YOUR HOUSE'S CPUS TO PUSH THAT WAY.`,
          tip: "POTIONS HEAL, THE AXE HITS HARDER, THE WING RUNS FASTER, THE SHIELD SOAKS, THE HOURGLASS READIES EVERY ABILITY AND CHARGES YOUR SUPER. EVERYONE IS FASTER IN DEATHMATCH AND STARTS SOMEWHERE RANDOM. EVERY MINUTE OR SO CHAOS BREAKS OUT: CANNONS, THE OGRE, A BLOOD MOON, POTION RAIN OR SWIFT WINDS. FFA DEATHMATCH IS THE SAME WITH EIGHT HOUSES OF ONE: FIRST CHAMPION TO THE KILL LIMIT WINS.",
          art: { kind: "seal", glyph: "combo", color: "#8a40e0" },
        },
      ],
    },
  ];
  const md = (name: string) => Object.values(MAP_DATA).find((m) => m.name === name) as Record<string, any> | undefined;
  const cr = md("Grudgeholm Crossing")?.mist ?? {};
  const ru = md("Grudgekeep Ruins")?.lantern ?? {};
  const fc = md("Frostcross Summit")?.avalanche ?? {};
  const ga = md("Bellwick Gardens") ?? {};
  const gg = ga.gates ?? {};
  const gf = ga.fountain ?? {};
  const sh2 = md("Grudgetide Shoals")?.tide ?? {};
  const rh = md("Russet Hollow")?.geysers ?? {};
  const es = md("Emberdune Spires")?.serpent ?? {};
  const MAP_TEXT: Record<
    string,
    { glyph: string; text: string; tip: string; mech?: { title: string; text: string; tip: string } }
  > = {
    "Grudgeholm Crossing": {
      glyph: "river",
      text: "A LONG FIELD SPLIT BY TWO RIVER CHANNELS. THE MIDDLE ISLAND HOLDS THE NEUTRAL PADS AND THE FORDS ARE SLOW TO CROSS. EACH KEEP HAS A NORTH GATE, A SOUTH GATE AND A BRIDGE TO THE EAST. IT'S A LONG WAY ACROSS, SO SOLDIERS MARCH A THIRD FASTER HERE.",
      tip: "THE FORDS ARE THE KILLING GROUND. FIGHT ON THE ISLAND, NOT IN THE WATER.",
      mech: {
        title: "RIVER MIST",
        text: `EVERY ${cr.everySeconds ?? 75} SECONDS OR SO A MIST ROLLS DOWN BOTH RIVERS, SITS THERE FOR ABOUT ${cr.holdSeconds ?? 16} SECONDS LOOKING MYSTERIOUS, THEN WANDERS OFF SOUTH. ANYTHING IN THE MIST IS HIDDEN, JUST LIKE TALL GRASS: TOWERS CAN'T SEE IN, AND WHOEVER SWINGS FIRST OUT OF IT GETS THE AMBUSH BONUS.`,
        tip: "THE FORDS ARE NOW ALSO THE HIDING GROUND. WALK INTO THE MIST CAREFULLY. SOMETHING IN THERE IS WAITING TO HIT YOU, AND IT MIGHT BE A TREE.",
      },
    },
    "Grudgekeep Ruins": {
      glyph: "castle",
      text: "A SQUARE OF OLD WALLS AND PITS, MIRRORED CORNER TO CORNER. EACH KEEP HAS A FRONT GATE TOWARD THE CENTRE AND A BACK GATE IN THE SIDE. THE OTHER TWO CORNERS ARE OLD GRAVEYARDS NOBODY VISITS. THERE'S SO LITTLE ROOM THAT EVERY OUTPOST HERE IS A MIXED ONE: YOU BUILD IT, IT DECIDES WHO TO SEND.",
      tip: "THE BACK GATE IS EASY TO FORGET. SO IS THE GRIM WALKING THROUGH IT.",
      mech: {
        title: "THE BONE LANTERN",
        text: `EVERY ${ru.everySeconds ?? 60} SECONDS SOMETHING IN THE PITS WAKES UP AND A BONE LANTERN FLOATS OUT, THEN DRIFTS OFF TO THE NEAREST EMPTY GRAVEYARD CORNER TO SULK FOR ${ru.restSeconds ?? 25} SECONDS. THE FIRST CHAMPION TO TOUCH IT IS HAUNTED FOR ${ru.hauntSeconds ?? 20} SECONDS: ${Math.round(((ru.damageMul ?? 1.3) - 1) * 100)}% MORE DAMAGE AND ${Math.round(((ru.speedMul ?? 1.15) - 1) * 100)}% MORE SPEED. THE DEAD DO NOT CHECK WHICH SIDE YOU ARE ON.`,
        tip: "YOU CAN GRAB IT WHILE IT'S STILL DRIFTING. IF YOU WAIT FOR IT IN THE CORNER, SO WILL THE OTHER CHAMPION, AND NOW THERE ARE TWO OF YOU IN A GRAVEYARD.",
      },
    },
    "Grudgetide Shoals": {
      glyph: "tide",
      text: "TWO ISLAND KEEPS ON A MUD FLAT. EACH HOUSE HAS ITS OWN DRY STONE CAUSEWAY ON ITS OWN FLANK. THE KEEPS ARE ON CLIFFS: YOU CAN DROP OFF THEM BUT NOT CLIMB BACK UP.",
      tip: "WEAR BOOTS. NOT THAT YOU CAN.",
      mech: {
        title: "THE TIDE",
        text: `EVERY ${(sh2.lowSeconds ?? 40) + (sh2.highSeconds ?? 30)} SECONDS THE TIDE COMES IN AND THE FLATS FLOOD FOR ${sh2.highSeconds ?? 30} SECONDS, SLOWING EVERYONE ON THEM. THEN IT GOES BACK OUT, AS TIDES DO.`,
        tip: "PUSH AT LOW TIDE. AT HIGH TIDE, STICK TO THE CAUSEWAYS AND ISLETS.",
      },
    },
    "Frostcross Summit": {
      glyph: "peak",
      text: "A FREE FOR ALL FIELD. FOUR KEEPS SIT AT THE FEET OF A FROZEN CROSS, WITH THE GRUDGE UP ON THE SUMMIT IN THE MIDDLE. BETWEEN THE ARMS ARE DEEP ICY BOWLS, CROSSED BY NARROW ROCK CAUSEWAYS THAT LINK EACH KEEP TO ITS NEIGHBOURS. THE OGRE LIVES ON THOSE.",
      tip: "YOUR NEIGHBOURS ARE CLOSER THAN THE HOUSE ACROSS THE PEAK. SO ARE YOU, TO THEM.",
      mech: {
        title: "AVALANCHE",
        text: `EVERY ${fc.everySeconds ?? 38} SECONDS ONE ARM RUMBLES FOR ${fc.warnSeconds ?? 6} SECONDS, THEN A WALL OF SNOW COMES DOWN IT FROM THE SUMMIT TOWARD THE KEEP. CHAMPIONS TAKE ${fc.heroDamage ?? 140} DAMAGE AND GET SHOVED; SOLDIERS LOSE ${Math.round((fc.unitDamage ?? 0.75) * 100)}% OF THEIR HEALTH. BUILDINGS ARE FINE. THE SNOW STAYS FOR ${fc.driftSeconds ?? 14} SECONDS AND SLOWS EVERYONE WADING THROUGH IT. IT GOES ROUND THE ARMS CLOCKWISE.`,
        tip: "WHEN THE SNOW RUMBLES, GET OUT OF THE LANE. IF YOU CAN COUNT, YOU KNOW WHICH LANE IS NEXT. ON EACH CAUSEWAY SITS AN AVALANCHE HORN: STAND AT IT ALONE FOR 3 SECONDS AND IT SENDS THE NEXT AVALANCHE DOWN A NEIGHBOUR'S ARM, NEVER YOURS. THEN IT NEEDS 75 SECONDS TO RECHARGE.",
      },
    },
    "Emberdune Spires": {
      glyph: "serpent",
      text: "A FREE FOR ALL FIELD. FOUR KEEPS IN A MOONLIT SANDSTONE CANYON. A CURVED CLIFF BLADE BENDS EACH KEEP'S EAST ROAD IN TOWARD THE MIDDLE, SO THE WHOLE MAP TURNS LIKE A PINWHEEL, WITH ONE NARROW PASS THROUGH EVERY BLADE. ALL ROADS END AT A RING OF SOFT DUNE SAND AROUND THE STONE ISLAND WHERE THE GRUDGE WAITS.",
      tip: "YOUR NEIGHBOUR ON ONE SIDE COMES THROUGH THE PASS. YOUR NEIGHBOUR ON THE OTHER SIDE COMES AROUND THE BLADE. KNOW WHICH IS WHICH.",
      mech: {
        title: "THE DUNE SERPENT",
        text: `SOMETHING SWIMS IN THE DUNE SEA. YOU CAN SEE ITS FINS AND THE SAND IT PUSHES UP, AND ANYTHING NEAR IT WADES THROUGH CHURNING SAND. EVERY ${es.everySeconds ?? 20} SECONDS IT STOPS, THE GROUND RUMBLES FOR ${es.warnSeconds ?? 2.5} SECONDS, AND IT BURSTS OUT: CHAMPIONS TAKE ${es.damage ?? 120} AND GET THROWN, SOLDIERS GET EATEN. AND IT HUNTS: WHOEVER CARRIES THE GRUDGE ACROSS THE SAND HAS IT CHASING THEM, A LITTLE SLOWER THAN A CHAMPION, AND IT COMES UP UNDER THEM THE MOMENT IT CATCHES UP.`,
        tip: "CARRYING THE GRUDGE OUT IS THE HARD PART. RUN STRAIGHT FOR THE ROCK, DODGE WHEN THE SAND RUMBLES UNDER YOU, AND LET THE SERPENT EAT WHOEVER IS CHASING YOU.",
      },
    },
    "Russet Hollow": {
      glyph: "apple",
      text: "A CIDER ORCHARD AT THE END OF HARVEST, SHAPED LIKE AN HOURGLASS AND PINCHED TO ONE LANE AT THE CIDER PRESS, WHERE THE GRUDGE SITS. ON EACH SIDE, TWO RAISED ORCHARD TERRACES CLIMB FROM A RAMP BY YOUR KEEP AND END IN A BANK OVER THE WAIST: YOU CAN DROP OFF IT, NOT CLIMB IT. HIGH GROUND, TALL WINDFALL GRASS AND LOTS OF TREES.",
      tip: "THE TERRACES ARE YOURS UNTIL SOMEONE FLIES ONTO THEM.",
      mech: {
        title: "THE CIDER WELLS",
        text: `THREE CIDER WELLS ON EACH SIDE: ONE IN THE LANE, ONE ON EACH TERRACE. EVERY ${rh.everySeconds ?? 15} SECONDS EITHER THE LANE WELLS OR THE TERRACE WELLS BUBBLE FOR ${rh.warnSeconds ?? 4} SECONDS AND THEN BLOW. ANY CHAMPION STANDING ON ONE RIDES THE SPOUT: A LANE WELL THROWS YOU RIGHT PAST THE PRESS INTO ENEMY GROUND, A TERRACE WELL THROWS YOU TO THE OTHER TERRACE. SOLDIERS GET BLASTED ASIDE. EVERYONE TAKES A LITTLE DAMAGE, AND THE WELL LEAVES STICKY MUD THAT SLOWS ANYONE IN IT FOR ${rh.mudSeconds ?? 6} SECONDS.`,
        tip: "SHOVE AN ENEMY ONTO THEIR OWN LANE WELL JUST BEFORE IT BLOWS AND IT THROWS THEM DEEP INTO YOUR SIDE, UNDER YOUR TOWERS. OR RIDE YOURS AND START THE FIGHT BEHIND THEM.",
      },
    },
    "Bellwick Gardens": {
      glyph: "bell",
      text: "A FREE FOR ALL FIELD. FOUR KEEPS IN THE CORNERS OF A VERY POSH WALLED GARDEN. A GRAVEL AVENUE RUNS FROM EACH KEEP PAST A ROUNDABOUT TOWER TO THE COURT IN THE MIDDLE. EVERYTHING ELSE IS HEDGES.",
      tip: "THE AVENUE NEVER CLOSES. THE HEDGES NEVER OPEN. EVERYTHING IN BETWEEN DEPENDS ON THE BELLS.",
      mech: {
        title: "BELLS AND THE FOUNTAIN",
        text: `EVERY ${gg.everySeconds ?? 40} SECONDS THE BELLS RING AND THE IRON GATES SWAP: EITHER BOTH BORDER LANES TO YOUR NEIGHBOURS ARE SHUT AND THE ONLY WAY ACROSS IS THROUGH THE COURT, OR THE COURT IS SEALED AND THE BORDER LANES ARE OPEN. THE GRUDGE SITS IN A FOUNTAIN. CHAMPIONS WADING IN THE BASIN HEAL ${gf.heal ?? 32} HEALTH A SECOND.`,
        tip: "THE FOUNTAIN HEALS EVERYONE. THAT INCLUDES THE THREE PEOPLE TRYING TO DROWN YOU IN IT.",
      },
    },
    "Emberglass Mere": {
      glyph: "tide",
      text: "TWO SNOWBOUND KEEPS AT SUNSET WITH A FROZEN LAKE BETWEEN THEM. THE SHORE PATHS GO THE LONG WAY ROUND THROUGH THE PINES. THE LAKE IS THE SHORT WAY ACROSS, WITH TWO ROCKY ISLETS HOLDING THE NEUTRAL PADS, AND THE GRUDGE WAKES IN THE MIDDLE OF THE ICE.",
      tip: "FROZEN REEDS LINE THE SHORE. WHOEVER WAITS IN THEM GETS TO HIT YOU AS YOU STEP OFF THE ICE.",
      mech: {
        title: "THIN ICE",
        text: "THE ICE IS SLICK: YOU'RE SLOW TO START AND SLOW TO STOP, A ROLL TURNS INTO A LONG SLIDE, AND A SHOVE OR A BIG HIT SENDS YOU SKATING, STRAIGHT INTO A ROCK FOR A WALL SPLAT IF THERE'S ONE IN THE WAY. HEAVY BLOWS AND HARD LANDINGS CRACK IT. CRACK A PATCH ENOUGH AND IT BREAKS: WHOEVER STANDS ON IT IS DUNKED, AND FOR A WHILE IT'S FREEZING WATER WHERE YOU WADE SLOWLY AND CAN'T ROLL. THEN IT FREEZES OVER AGAIN.",
        tip: "FIGHT SOMEONE NEXT TO A CRACKED PATCH AND FINISH IT UNDER THEM. AND DON'T STAND ON A PATCH THAT'S ALREADY WHITE WITH CRACKS.",
      },
    },
    "Bellfry Abbey": {
      glyph: "bell",
      text: "A DEATHMATCH FIELD. A ROOFLESS ABBEY ON A HILL AT NIGHT, RINGED BY ITS OWN GRAVEYARD. THE PRECINCT IN THE MIDDLE STANDS ON A RETAINING WALL: TWO STAIRS UP ON EACH SIDE, AND YOU CAN DROP OFF IT ANYWHERE. ACROSS IT RUNS THE LONG ROOFLESS NAVE, WITH THE GRUDGE AT THE ALTAR, AND A BROKEN CLOISTER AROUND AN OVERGROWN GARDEN. TWO BELL TOWER STUMPS STAND ON OPPOSITE CORNERS OF THE PRECINCT. EACH HAS ONE STAIR UP AND A LONG DROP ON TWO SIDES.",
      tip: "THE BELL TOWERS ARE THE BEST SEAT IN THE HOUSE FOR ANYONE WITH A BOW. THERE'S ONE STAIR UP, SO THERE'S ONE STAIR TO GUARD.",
      mech: {
        title: "GRAVES AND CRYPTS",
        text: "THE GRAVEYARD RING IS ALL LONG GRASS, YEWS, HEADSTONES AND A HEDGE OR TWO THAT GO NOWHERE. IT'S THE BEST PLACE ON THE MAP TO HIDE AND THE WORST PLACE TO CHASE SOMEONE. BELOW IT ON TWO SIDES ARE THE CRYPT YARDS: SUNKEN, WALLED, WITH ONE STAIR DOWN AND NO WAY OUT BUT THAT STAIR OR A JUMP PAD BACK UP TO THE GRAVES.",
        tip: "NEVER FOLLOW ANYONE INTO A CRYPT YARD. THEY KNOW WHERE THE JUMP PAD IS, AND THEIR FRIENDS KNOW WHERE THE STAIR IS.",
      },
    },
    "Cutstone Quarry": {
      glyph: "pick",
      text: "A DEATHMATCH FIELD. AN ABANDONED QUARRY AT SUNSET, CUT IN THREE GREAT STEPS. THE LIP AROUND THE OUTSIDE IS OPEN SCRUB WITH TALL GRASS, CRANES AND THE CAMPS WHERE THE HOUSES START. BELOW IT A STONE SHELF RINGS THE PIT, WITH MINE ADITS CUT BACK INTO THE ROCK THAT GO NOWHERE. AT THE BOTTOM IS THE OPEN PIT FLOOR, WITH THE CRUSHER MOUND IN THE MIDDLE WHERE THE GRUDGE WAKES. YOU CAN DROP DOWN ANYWHERE, BUT THE ONLY WAY UP IS THE HAUL ROADS, OR THE JUMP PADS THAT FLING YOU FROM THE PIT BACK TO THE LIP.",
      tip: "WHOEVER HOLDS THE LIP SHOOTS DOWN. WHOEVER IS IN THE PIT WALKS ALL THE WAY ROUND TO ANSWER.",
      mech: {
        title: "WHERE THE GOODS ARE",
        text: "THE QUARRY'S POWER-UPS ALWAYS SPAWN IN THE SAME PLACES. THE AXE, THE WING AND THE HOURGLASS ARE UP ON THE LIP AND IN AN ADIT. THE SHIELDS ARE ON THE SHELF. ALL SIX POTIONS ARE DOWN IN THE PIT AND ON THE SHELF. SO THE HURT GO DOWN AND THE GREEDY GO UP.",
        tip: "THE ADITS ARE GREAT FOR HIDING AND AWFUL FOR LEAVING. IF SOMEONE IS IN THE MOUTH, YOU'RE IN A HOLE IN A WALL.",
      },
    },
  };
  mapNames.forEach((name, index) => {
    const m = MAP_TEXT[name] ?? { glyph: "river", text: "A FIELD OF BATTLE. IT HAS GRASS ON IT.", tip: "WIN." };
    const pages: CodexEntry["pages"] = [
      { title: name.toUpperCase(), text: m.text, tip: m.tip, art: { kind: "map", index } },
    ];
    pages[0].art = { kind: "scene", scene: `map:${index}` };
    if (m.mech)
      pages.push({
        title: m.mech.title,
        text: m.mech.text,
        tip: m.mech.tip,
        art: { kind: "scene", scene: `map:${index}` },
      });
    entries.push({ cat: "FIELDS", title: name.toUpperCase().replace(/^GRUDGE\w*\s*/, ""), glyph: m.glyph, pages });
  });
  const heroes = Object.keys(TEXT).filter((h) => HEROES[h]);
  const hh = HEROES.herald;
  const hab = (slot: "a" | "b" | "r" | "z", label: string, text: string, tip: string): CodexPage => {
    const call = hh?.abilities[slot].callout?.split("·")[0].trim();
    const cd = hh?.abilities[slot].cooldown;
    return {
      title: `${label}${call ? ` · ${call}` : ""}`,
      text: text + (cd && cd > 1 ? `  COOLDOWN ${cd}S.` : ""),
      tip,
      art: { kind: "shot", hero: "herald", slot },
    };
  };
  const herald: CodexEntry = {
    cat: "HERALD",
    title: "THE HERALD",
    glyph: "banner",
    pages: [
      {
        title: "THE HERALD · THE COMMANDER",
        text: "A SKINNY KNIGHT WITH A VERY BIG FLAG. IN 2V2 HE CAN TAKE THE THIRD OR FOURTH SEAT, OR A CHAMPION CAN BECOME HIM MID-MATCH. HE SEES THE WHOLE ARMY, D-PAD UP SENDS A GROUP TO SIEGE, D-PAD DOWN MAKES THEM HOLD, AND HIS ORDERS BEAT HIS PARTNER'S. NO TALENTS, JUST AN ARMY.",
        tip: "HE'S NOT HERE TO WIN FIGHTS. HE'S HERE TO MAKE SURE YOUR SOLDIERS WIN THEM.",
        art: { kind: "portrait", hero: "herald" },
      },
      hab(
        "a",
        "A · ATTACK",
        "A QUICK, WEAK BOLT. ENOUGH TO FINISH A SOLDIER OR ANNOY A CHAMPION.",
        "IF YOU'RE SHOOTING A LOT, SOMETHING HAS GONE WRONG.",
      ),
      hab(
        "b",
        "B · WAR BANNER",
        "PLANTS THE HOUSE BANNER A FEW STEPS AHEAD. TROOPS ON FOLLOW GATHER AT IT, HOLD ORDERS HOLD THERE, AND TROOPS NEAR IT MOVE FASTER. INSIDE ITS REACH YOUR HOUSE CAN SHOP AND BUILD ON NEARBY PADS.",
        "PLANT IT NEXT TO A FAR PAD AND YOUR PARTNER CAN BUY BOMBS IN THE MIDDLE OF THE MAP.",
      ),
      hab(
        "r",
        "R · WAR HORN",
        "EVERYONE ON YOUR SIDE NEARBY HITS HARDER AND RUNS FASTER FOR A FEW SECONDS.",
        "BLOW IT RIGHT AS THE TWO ARMIES MEET.",
      ),
      hab(
        "z",
        "Z · RALLY",
        "HEALS EVERY FRIEND NEARBY, SHAKES OFF STUNS AND SLOWS, HARDENS THEM FOR A FEW SECONDS AND HALVES YOUR PARTNER'S B AND R COOLDOWNS WHEREVER THEY ARE.",
        "SAVE IT FOR THE MOMENT YOUR PARTNER IS ABOUT TO LOSE A FIGHT.",
      ),
      {
        title: "L · FORMATIONS",
        text: "THE HERALD DOESN'T BLOCK, SO L CHANGES THE ARMY'S SHAPE: LOOSE, COLUMN FOR BRIDGES AND FORDS, LINE FOR HOLDING (BRUTES IN FRONT, ARCHERS BEHIND) OR WEDGE FOR CHARGING. IT SHAPES TROOPS THAT HOLD OR FOLLOW.",
        tip: "COLUMN OVER A BRIDGE, LINE ON THE FAR SIDE. NOW IT'S A BRIDGEHEAD.",
        art: { kind: "scene", scene: "formation" },
      },
      {
        title: "X · TAKE UP THE BANNER",
        text: `IN A 2V2 WITH NO HERALDS, HOLD X AWAY FROM A PAD FOR ${M.arena.morph?.holdSeconds ?? 0.6} SECONDS AND YOUR CHAMPION BECOMES THE HERALD: NO LEVELS, NO TALENTS, IN CHARGE OF THE ARMY. ONE PER HOUSE. YOU STAY THAT WAY UNTIL YOU DIE, OR HOLD X AT YOUR KEEP TO CHANGE BACK FOR ${M.arena.morph?.revertCost ?? 50} GOLD.`,
        tip: "FOR WHEN THE ARMY NEEDS A BABYSITTER MORE THAN THE FIGHT NEEDS YOU.",
        art: { kind: "scene", scene: "morph" },
      },
    ],
  };
  return [...heroes.map(heroEntry), herald, ...entries];
}
