import heroJson from "../../data/heroes.json";
import talentJson from "../../data/talents.json";
import unitJson from "../../data/units.json";
import structJson from "../../data/structures.json";
import matchJson from "../../data/match.json";

const COMBOS: Record<string, [string, string, string, "a" | "b" | "r" | "z"]> = {
  warlord: [
    "CRACK CHARGE",
    "WITH EARTHSPLITTER, PRESS B WHILE YOUR FINISHER'S ROCK WAVE IS STILL RUNNING. YOU CHARGE DOWN THE CRACK TWICE AS FAR AS A NORMAL CHARGE, BOWLING OVER ANYONE IN THE WAY, AND SLAM AT THE END.",
    "A CHASE-DOWN OR A GETAWAY. AIM YOUR FINISHER WHERE YOU WANT TO GO.",
    "a",
  ],
  warden: [
    "ARM SHOVE",
    "WHILE YOUR LONG ARM SLAP IS STILL STRETCHED OUT, PRESS L+A. EVERYTHING ALONG THE ARM GETS SHOVED HARD AWAY FROM YOU AND STUNNED.",
    "PEEL A DIVER OFF YOUR BACK, OR SLAP SOMEONE OFF A BRIDGE AND SHOVE THEM INTO THE WATER.",
    "b",
  ],
  engineer: [
    "RAMP JUMP",
    "STANDING ON YOUR SIEGE RAMP, DODGE (L+X) TOWARD WHERE YOU WANT TO GO. STIG LAUNCHES OFF THE RAMP IN A LONG JUMP, CLEAR OVER WALLS.",
    "BUILD THE RAMP FACING THEIR KEEP WALL, THEN JUMP STRAIGHT INTO THEIR BASE. OR FACING HOME, AS AN ESCAPE HATCH.",
    "r",
  ],
  summoner: [
    "HEX SWAP",
    "WHILE AN ENEMY CHAMPION YOU'VE HEXED IS WITHIN 10M, DODGE (L+X) AND YOU SWAP PLACES WITH THEM. THEY'RE STUNNED FOR A MOMENT WHERE YOU WERE STANDING. HEXED SOLDIERS DON'T COUNT.",
    "WHEN SOMEONE DIVES YOU, HEX THEM, THEN SWAP: THEY'RE LEFT IN THE MIDDLE OF YOUR SKELETONS.",
    "b",
  ],
  duelist: [
    "RIPOSTE WHIRL",
    "RIGHT AFTER A SUCCESSFUL PARRY, PRESS A. FRANCOIS SPINS A FULL CIRCLE, HITTING EVERYTHING AROUND HIM, NOT JUST THE ATTACKER.",
    "YOUR ANSWER TO A MOB OF SOLDIERS: PARRY THE FIRST ONE, THEN SPIN.",
    "r",
  ],
  marksman: [
    "SKYSHOT",
    "WHILE PIP IS HANGING ON TO SOMEONE WITHIN 14M, DODGE (L+X). WREN BACKFLIPS 4M AWAY FROM THEM AND, BEFORE HER BOOTS TOUCH THE GRASS, PUTS A GUARANTEED CRITICAL ARROW INTO PIP'S PREY.",
    "THE ANSWER TO ANYONE WHO GETS CLOSE: SEND PIP, LET THEM COME, THEN FLIP AWAY AND SHOOT THEM IN THE FACE ON THE WAY.",
    "b",
  ],
  friar: [
    "KEG ROCKET",
    "STANDING IN YOUR OWN ALE PUDDLE, DODGE (L+X). MADDOCK HOPS ON A KEG AND ROLLS FLAT OUT ABOUT 10M, BOWLING FOES ASIDE AND LEAVING A SHORT TRAIL OF HEALING ALE. THE TRAIL DOESN'T COUNT AS A PUDDLE, SO NO ENCORES.",
    "THROW A HEALING KEG AT YOUR FEET AS A LAUNCH PAD. IT'S AN ESCAPE, A CHASE, AND A VERY UNDIGNIFIED ENTRANCE.",
    "b",
  ],
  herald: [
    "BANNER VAULT",
    "DODGE (L+X) TOWARD YOUR PLANTED BANNER WHEN IT'S 3 TO 13M AWAY AND THE HERALD VAULTS STRAIGHT TO IT.",
    "PLANT THE BANNER SOMEWHERE SAFE BEFORE THINGS GO WRONG. IT'S YOUR WAY OUT.",
    "b",
  ],
};

const SPEC_TIPS: Record<string, string> = {
  ballista: "PUT IT WHERE THEY COME AT YOU IN A LINE: A BRIDGE, A RAMP, A ROAD.",
  firepot: "SOLDIERS STANDING IN THE FIRE KEEP BURNING. GREAT WHERE THEY BUNCH UP.",
  volley: "THE ANSWER TO GRIM. HE CAN'T SNEAK PAST SOMETHING THAT SEES HIM.",
  frost: "FROZEN SOLDIERS DON'T HIT BACK. YOUR TROOPS GET FREE SWINGS.",
  storm: "THE STUN HITS CHAMPIONS TOO. FIGHT UNDER IT AND THEY CAN'T ESCAPE.",
  well: "PAIR IT WITH A FIREPOT OR A BALLISTA NEARBY. EVERYTHING ENDS UP IN ONE PILE.",
};

export type CodexArt =
  | { kind: "shot"; hero: string; slot: "a" | "b" | "r" | "z" }
  | { kind: "portrait"; hero: string }
  | { kind: "map"; index: number }
  | { kind: "seal"; glyph: string; color?: string }
  | { kind: "unit"; type: string }
  | { kind: "scene"; scene: string };

export interface CodexPick {
  id: string;
  name: string;
  desc: string;
  combo?: string;
}

export interface CodexPage {
  title: string;
  text: string;
  art: CodexArt;
  tip?: string;
  picks?: CodexPick[];
}

export interface CodexEntry {
  cat: string;
  title: string;
  glyph: string;
  pages: CodexPage[];
}

type Ability = { kind: string; callout?: string; cooldown?: number };
type Hero = {
  name: string;
  health: string;
  speed: string;
  damage: string;
  abilities: Record<"a" | "b" | "r" | "z", Ability>;
};
type Talent = { id: string; name: string; desc: string; combo?: string };

const HEROES = (heroJson as unknown as { heroes: Record<string, Hero> }).heroes;
const TALENTS = (talentJson as unknown as { heroes: Record<string, Record<"r" | "b" | "a" | "z", Talent[]>> }).heroes;
const U = unitJson as unknown as {
  waves: { everySeconds: number; spawnCost: Record<string, number> };
  types: Record<string, { hp: number; bounty: number }>;
  popCap: number;
};
const S = structJson as unknown as {
  types: Record<
    string,
    {
      name: string;
      cost: number;
      upgradeCost: number;
      mix?: Record<string, number>;
      cadence?: number;
      specCost?: number;
      specs?: { id: string; name: string; blurb: string }[];
    }
  >;
  buildSeconds: number;
  rubbleSeconds: number;
};
const M = matchJson as unknown as {
  economy: {
    start: number;
    income: number;
    grain?: { base: number; perLevel: number[]; surplus?: number };
    padIncome?: Record<string, number>;
    loss: { heroDeath: number; tower: number };
    rally: { seconds: number; damageMul: number; speedMul: number };
    bounty: { hero: number; structure: number };
  };
  arena: {
    shop: {
      bomb: { cost: number; coreDamage: number };
      ward: { cost: number; cooldown: number };
      cannon: { cost: number; shots: number };
    };
    relic: { firstSeconds: number; enshrineSeconds: number; stealSeconds: number; incomeMul: number };
    ogre: { firstSeconds: number; hp: number; bounty: number; blessSeconds: number; respawnSeconds: number };
    cannon: { firstSeconds: number; everySeconds: number; damage: number; structureDamage: number };
    morph?: { holdSeconds: number; channelSeconds: number; revertCost: number };
  };
};
const pct = (m: number) => `${Math.round((m - 1) * 100)}%`;

interface HeroText {
  lore: string;
  role: string;
  a: [string, string];
  b: [string, string];
  r: [string, string];
  z: [string, string];
  picks: Record<string, string>;
  evo: Record<"r" | "b" | "a" | "z", string>;
  tactics: string;
  fear: string;
}

const TEXT: Record<string, HeroText> = {
  warlord: {
    lore: "BORN IN A TENT, RAISED BY A WAR DRUM, NAMED BY A GOAT. HE HAS NEVER LOST AN ARGUMENT, MOSTLY BECAUSE HE ANSWERS EVERY ONE BY HITTING THE FLOOR VERY HARD. HIS BRUTES LOVE HIM. NOBODY HAS ASKED WHY.",
    role: "THE HEAVY. SLOW TO START, MISERABLE TO STAND NEXT TO. HIS BRUTES COME OUT TOUGHER THAN ANYONE ELSE'S. OUT OF A FIGHT FOR A FEW SECONDS HE MARCHES A THIRD FASTER. UNBREAKABLE: WITH TWO ENEMY CHAMPIONS ON HIM HE TAKES 40% LESS FROM THEM AND HITS THEM 30% HARDER.",
    a: [
      "TWO BIG SWINGS. THE SECOND ONE SENDS PEOPLE BACKWARDS.",
      "THE FINISHER KNOCKS FOES OUT OF REACH. IF YOU WANT TO KEEP HITTING, WALK AFTER THEM.",
    ],
    b: [
      "GROUND SLAM. A RING OF PAIN THAT SLOWS AND COWS EVERYONE IN IT, SO THEY HIT SOFTER FOR A MOMENT.",
      "SLAM FIRST, QUAKE SECOND. EARTHQUAKE HITS SLOWED FOES HARDER.",
    ],
    r: [
      "WAR CRY. EVERY ALLY NEARBY HITS HARDER AND MOVES FASTER FOR A FEW SECONDS. TROOPS COUNT.",
      "SAVE IT FOR WHEN YOUR ARMY IS ALREADY SWINGING AT SOMETHING. A WAR CRY AT AN EMPTY FIELD IS JUST SHOUTING.",
    ],
    z: [
      "EARTHQUAKE. A HUGE STOMP THAT STUNS EVERYONE AROUND YOU AND HURTS BUILDINGS TOO.",
      "WAIT FOR THEM TO CLUMP UP OR COMMIT TO A FIGHT. A WHIFFED QUAKE IS A VERY LOUD APOLOGY.",
    ],
    picks: {
      bloodroar: "TAKE IT IF YOU FIGHT ALONGSIDE A BIG ARMY. EVERY TROOP BECOMES A LITTLE LEECH.",
      challenge: "TAKE IT IF YOU KEEP LOSING DUELS. YANKING A FAST HERO INTO YOUR LAP SOLVES MOST PROBLEMS.",
      magnitude: "PULLS EVERYONE INTO ONE SPOT. PERFECT SETUP FOR EARTHQUAKE. WITH CHALLENGE IT STUNS TOO.",
      shouldercharge: "TURNS YOUR SLAM INTO A GAP-CLOSER. GOOD AGAINST RUNNERS LIKE GRIM AND REMNIL.",
      earthsplitter: "GIVES YOU A RANGED STUN ON EVERY FINISHER. GREAT FOR CLEARING TROOPS IN A LINE.",
      berserker: "SELF-HEALING AND FASTER SWINGS. PICK IT IF YOU PLAN TO STAND IN THE MIDDLE OF EVERYTHING.",
      cataclysm: "MORE QUAKE. NOBODY HAS EVER COMPLAINED ABOUT MORE QUAKE.",
    },
    evo: {
      r: "THE BIG QUESTION: ARE YOU LEADING AN ARMY OR HUNTING HEROES?",
      b: "SLAM UPGRADES. LOOK AT YOUR WAR CRY PICK FIRST, EACH SLAM HAS A FAVOURITE.",
      a: "PICK BY WHAT YOU'RE HITTING MOST: A LINE OF TROOPS OR ONE ANNOYING HERO.",
      z: "THE QUAKE GETS BIGGER AND LEAVES LAVA. THAT'S IT. THAT'S THE PAGE.",
    },
    tactics:
      "WALK IN BEHIND YOUR BRUTES, SLAM WHEN THEY ENGAGE, WAR CRY WHEN EVERYONE IS SWINGING, QUAKE WHEN THEY TRY TO RUN. YOU ARE NOT FAST, SO DON'T CHASE FOR LONG. LET THEM COME TO YOU.",
    fear: "GETTING KITED. REMNIL AND STIG'S BALLISTA CAN HURT YOU FROM FAR AWAY WHILE YOU STOMP AT NOTHING.",
  },
  engineer: {
    lore: "STIG BUILT HIS FIRST TOWER AT AGE SIX OUT OF SPOONS. IT HELD FOR THREE WEEKS AND HURT A MAILMAN. HE HAS NEVER BEEN PROUDER OF ANYTHING. HE BUILDS CHEAPER BECAUSE HE ARGUES WITH EVERY MERCHANT FOR AN HOUR.",
    role: "THE BUILDER. HIS TOWERS AND UPGRADES COST LESS (A LITTLE LESS SO IN FREE FOR ALL), HE REPAIRS THEM, AND HE CAN RAISE A RAMP AND PARK A BALLISTA ON IT. HIS REPAIR PULSE ALSO PATCHES UP SOLDIERS AND HIS PARTNER.",
    a: [
      "A WRENCH COMBO. NOTHING FANCY. STANDING ON YOUR OWN RAMP, A INSTEAD THROWS THE WRENCH.",
      "STIG IS STURDY, SO YOU CAN TRADE HITS. JUST DON'T EXPECT TO WIN A DUEL WITH FRANCOIS ON WRENCH ALONE.",
    ],
    b: [
      "REPAIR. HEALS EVERY BUILDING AROUND YOU AND HITS NEARBY FOES WITH THE PULSE.",
      "A TOWER ABOUT TO FALL IS A TOWER THAT ISN'T. KEEP AN EYE ON YOUR HEALTH BARS.",
    ],
    r: [
      "SIEGE RAMP. RAISES A RAMP YOU CAN STAND ON. HIGH GROUND, BETTER SHOTS, ANGRY ENEMIES BELOW.",
      "BUILD IT NEXT TO AN ENEMY TOWER, THEN PUT THE BALLISTA ON TOP.",
    ],
    z: [
      "BALLISTA. PLANTS A BIG CROSSBOW THAT SHOOTS ON ITS OWN. ON A RAMP IT HITS HARDER. ONLY ONE AT A TIME.",
      "PLACE IT WHERE THEY HAVE TO WALK, NOT WHERE THEY ALREADY ARE.",
    ],
    picks: {
      teslatower: "YOUR RAMP KEEPS ITS RAMP AND GETS A LIGHTNING COIL ON TOP. EXCELLENT AGAINST CROWDS OF TROOPS.",
      palisade: "YOUR RAMP BECOMES A SPIKED WALL THAT POPS UP UNDER PEOPLE. BLOCKS ROADS, STUNS, HURTS.",
      shockwrench: "REPAIR BECOMES A STUN BOMB. WITH TESLA TOWER IT ALSO MAKES YOUR TOWERS FIRE DOUBLE SPEED.",
      fortify: "REPAIRS HAND OUT SHIELDS TO EVERYONE. WITH PALISADE YOUR WALLS STAY UP LONGER.",
      riveter: "YOUR FINISHER SHOOTS HOT RIVETS. FINALLY, A REASON TO HIT THINGS.",
      overclock: "HITTING STUFF LOWERS YOUR REPAIR COOLDOWN AND STARTS ZAPPING. GOOD IF YOU BRAWL A LOT.",
      greatballista: "A BIGGER, MEANER, LONGER-LIVED BALLISTA. TAKE IT. YOU DON'T HAVE A CHOICE ANYWAY.",
    },
    evo: {
      r: "WHAT SHOULD YOUR RAMP BECOME? LIGHTNING FOR THE CROWDS, OR A WALL FOR THE ROADS.",
      b: "REPAIR UPGRADES. BOTH COMBOS ARE STRONG, SO MATCH THE ONE THAT GOES WITH YOUR RAMP.",
      a: "STIG DOESN'T LIVE ON HIS BASIC ATTACK, BUT THESE MAKE IT WORTH PRESSING.",
      z: "GREAT BALLISTA. PROBABLY THE MOST POLITE WAY TO DESTROY A KEEP.",
    },
    tactics:
      "BUILD EARLY, BUILD OFTEN. YOU GET TOWERS CHEAPER, SO SPEND THAT GOLD ON OUTPOSTS AND UPGRADES. PUSH WITH A RAMP AND BALLISTA COMBO AND LET THE MACHINES DO THE DAMAGE.",
    fear: "GRIM SNEAKING AROUND YOUR TOWERS AND BREAKING THEM WHILE YOU'RE BUSY BEING HANDY ELSEWHERE.",
  },
  raider: {
    lore: "GRIM WAS RAISED BY WOLVES, WHO LATER SUED. HE HAS NO HOUSE, NO BANNER AND NO TABLE MANNERS. HE DOES HAVE TWO VERY SHARP KNIVES AND AN ENORMOUS GRUDGE AGAINST EVERYONE TALLER THAN HIM, WHICH IS EVERYONE.",
    role: "THE GLASS CANNON. FASTEST HERO, LEAST HEALTH, MOST STAB. GETS IN, KILLS SOMEONE, GETS OUT. CAN CLIMB SLOPES OTHERS CAN'T. LONE WOLF: WITH NO FRIENDLY CHAMPION WITHIN 14M HE HEALS 30% OF THE DAMAGE HE DEALS TO CHAMPIONS AND TAKES 30% LESS FROM SOLDIERS AND TOWERS.",
    a: [
      "A FLURRY OF NEAR-INSTANT STABS WITH A HEAVIER FINISHER. HITS FROM BEHIND DEAL MORE.",
      "STICK TO ONE TARGET. YOUR SWINGS ARE NARROW, SO SPINNING AROUND IN A CROWD WASTES THEM.",
    ],
    b: [
      "LEAP. JUMP UP TO 8M AND LAND ON SOMEONE. KILLS RESET THE COOLDOWN.",
      "USE IT TO GET IN, OR TO GET OUT. NOT BOTH, UNLESS YOU KILL SOMETHING.",
    ],
    r: [
      "SMOKE. GO INVISIBLE FOR A FEW SECONDS AND MOVE FASTER. YOUR FIRST HIT OUT OF SMOKE HURTS DOUBLE.",
      "WALK BEHIND THEM, THEN ATTACK. A STEALTHED STAB TO THE BACK IS THE WHOLE POINT OF YOU.",
    ],
    z: [
      "EXECUTE DASH. A LONG DASH THAT DEALS HUGE DAMAGE AND HITS EVEN HARDER ON WOUNDED FOES.",
      "DON'T OPEN WITH IT. FINISH WITH IT.",
    ],
    picks: {
      smokebomb: "YOUR SMOKE ALSO CHOKES AND SLOWS ANYONE STANDING IN IT. NOBODY ESCAPES.",
      shadowstep: "YOUR SMOKE BECOMES A SHORT TELEPORT. CROSS WALLS, CLIFFS AND BAD DECISIONS.",
      pounce: "LEAP MARKS ITS VICTIM, THEN THE MARK EXPLODES. WITH SMOKE BOMB MARKS HURT EVEN MORE.",
      doublejump: "LEAP TWICE. WITH SHADOW STEP, BLINKING GIVES YOU LEAP BACK. YOU WILL NEVER TOUCH THE GROUND.",
      serrated: "BLEED STACKS AND A BIG RIP ON THE FINISHER. YOU HEAL OFF BLEEDING FOES.",
      twinfangs: "YOUR FINISHER THROWS POISON DAGGERS THAT SLOW AND BOUNCE. GOOD FOR CHASING.",
      deathmark: "EXECUTE AT HALF HEALTH INSTEAD OF 40%, AND A KILL REFUNDS YOUR METER. CHAIN KILLS.",
    },
    evo: {
      r: "AMBUSHER OR ESCAPE ARTIST. SMOKE BOMB TRAPS, SHADOW STEP TELEPORTS.",
      b: "LEAP UPGRADES. EACH ONE IS BUILT FOR ONE OF YOUR SMOKE PICKS, SO MATCH THEM.",
      a: "BLEED THEM OUT OR SLOW THEM DOWN. BOTH SAY 'YOU'RE NOT LEAVING'.",
      z: "DEATH MARK TURNS ONE KILL INTO TWO. VERY RUDE.",
    },
    tactics:
      "PICK ON SOMEONE ALONE. GO INVISIBLE, WALK BEHIND THEM, LEAP OR STAB, EXECUTE WHEN THEY'RE LOW. IF IT GOES WRONG, LEAVE IMMEDIATELY. A DEAD GRIM LOSES YOUR TEAM GOLD.",
    fear: "LANE TOWERS AND THORN. YOU ARE MADE OF PAPER AND BOTH OF THEM ARE MADE OF NOT-PAPER.",
  },
  summoner: {
    lore: "REMNIL STUDIED NECROMANCY BECAUSE THE LIBRARY HAD RUN OUT OF BOOKS ON GARDENING. HE TALKS TO HIS SKELETONS, NAMES THEM, AND IS VISIBLY UPSET WHEN THEY GET SMASHED. THEY DO NOT TALK BACK. YET.",
    role: "THE RANGED MIXED ATTACKER. SHOOTS FROM FAR, HEXES GROUPS, RAISES THE DEAD TO FIGHT FOR HIM AND WALKS THROUGH THE GRAVE TO ANY OF HIS BUILDINGS.",
    a: [
      "A VOLLEY OF THREE BOLTS. THE THIRD IS A BIG ORB THAT SPLASHES AND SLOWS.",
      "BOLTS NO LONGER STAGGER HEROES, BUT THE ORB DOES. TIME THE THIRD SHOT FOR WHEN THEY CHARGE.",
    ],
    b: [
      "HEX. A CURSE CIRCLE THAT HURTS AND SLOWS. ANYONE WHO DIES WHILE HEXED GETS BACK UP ON YOUR SIDE.",
      "HEX A CROWD OF ENEMY TROOPS RIGHT BEFORE THEY DIE AND GROW YOUR ARMY FOR FREE.",
    ],
    r: [
      "GRAVEWALK. HOLD R: EVERY BUILDING YOU CAN WALK TO LIGHTS UP. STEER THE MARKER WITH THE STICK TO PICK ONE, LET GO, AND AFTER A 1S CHANNEL YOU STEP OUT OF A GRAVE BESIDE IT. TAP R TO GO STRAIGHT HOME. YOU EMPOWER IT RIGHT AWAY FOR AS LONG AS YOU STAY WITHIN 6M: AN OUTPOST TRAINS 40% FASTER, A TOWER ATTACKS 50% FASTER.",
      "A STUN BREAKS THE CHANNEL. WHILE THE GATES ARE SHUT YOU CAN ONLY WALK TO BUILDINGS INSIDE YOUR OWN WALLS.",
    ],
    z: [
      "RAISE AN ARMY. A WHOLE SQUAD OF THE DEAD SHOWS UP AT ONCE.",
      "DROP IT IN THE MIDDLE OF A PUSH. A SURPRISE ARMY TURNS A FAIR FIGHT INTO A VERY UNFAIR ONE.",
    ],
    picks: {
      risenranks:
        "SOLDIERS FROM AN OUTPOST YOU'RE EMPOWERING COME OUT AS VETERANS. BUILD AN ARMY THAT'S ALREADY RANKED.",
      wraithgate:
        "A FASTER CHANNEL AND YOU ARRIVE SWINGING: FOES NEAR YOUR LANDING ARE HURT, HEXED AND SLOWED, AND YOU GET A SHIELD. FOR JUMPING INTO A FIGHT AT YOUR TOWER.",
      gravepull: "HEX DRAGS PEOPLE TOGETHER AND LEAVES SPIKES. WITH WRAITH GATE IT ALSO STUNS.",
      cascade: "HEX FALLS THREE TIMES IN A LINE. WITH RISEN RANKS EVERY HEX RAISES A GRUNT.",
      soulsiphon: "YOUR BOLTS HEAL YOU AND BUILD A SHIELD. MAKES YOU MUCH HARDER TO JUMP ON.",
      arcbolts: "BOLTS JUMP BETWEEN TARGETS. IT TURNS YOU INTO A TROOP SHREDDER.",
      legion: "A BIGGER ARMY FOR LONGER, AND YOUR HEX REACHES FURTHER. MORE FRIENDS, ALL DEAD.",
    },
    evo: {
      r: "ARMY OR AMBUSH. RISEN RANKS GROWS VETERANS AT HOME, WRAITH GATE TURNS THE WALK INTO AN ATTACK.",
      b: "HEX UPGRADES. EACH HAS A STRONG COMBO WITH ONE GRAVEWALK EVOLUTION, SO PICK THE MATCHING ONE.",
      a: "SURVIVE (SIPHON) OR SHRED (ARC BOLTS). IF PEOPLE KEEP DIVING YOU, TAKE SIPHON.",
      z: "LEGION. YOUR ARMY OF THE DEAD BECOMES A SLIGHTLY LARGER ARMY OF THE DEAD.",
    },
    tactics:
      "STAY BEHIND YOUR TROOPS AND SHOOT. HEX CLUMPS OF ENEMY SOLDIERS TO STEAL THEM. WHEN SOMEONE DIVES YOU, HEX THEM AND SWAP AWAY. WHEN A TOWER IS UNDER SIEGE, GRAVEWALK TO IT AND STAND YOUR GROUND BESIDE IT.",
    fear: "GRIM APPEARING BEHIND YOU WITH NO WARNING. KEEP GRAVEWALK READY AS YOUR WAY HOME, AND CHANNEL IT OUT OF HIS SIGHT.",
  },
  duelist: {
    lore: "FRANCOIS HAS BEEN IN 312 DUELS AND HAS WON ALL OF THEM, ACCORDING TO FRANCOIS. HE FIGHTS WITH ONE HAND BEHIND HIS BACK. THE OTHER HAND IS HOLDING A BAGUETTE. NOBODY KNOWS WHERE THE BAGUETTE GOES DURING THE FIGHT.",
    role: "THE ALL-ROUNDER. DECENT AT EVERYTHING, GREAT AT ONE-ON-ONE. REWARDS GOOD TIMING MORE THAN ANYONE. A DUELLIST, NOT A MOWER: EACH SWING, LUNGE OR FLURRY BEAT HITS AT MOST TWO SOLDIERS (CHAMPIONS ALWAYS COUNT).",
    a: [
      "THREE QUICK THRUSTS WITH A LUNGING FINISHER. CRITS A LOT.",
      "THE THRUSTS ARE NARROW BUT REACH FAR. POKE FROM THE EDGE OF THEIR RANGE.",
    ],
    b: [
      "LUNGE. A FAST DASH THROUGH THE FIRST FOE IN LINE.",
      "GOOD FOR CHASING, BETTER FOR DODGING THROUGH SOMEONE WHO EXPECTED YOU TO RUN AWAY.",
    ],
    r: [
      "PARRY. A SHORT GUARD WINDOW. IF THEY HIT YOU INSIDE IT, YOU COUNTER, STUN THEM AND RESET LUNGE.",
      "PARRY WHEN THEY START SWINGING, NOT WHEN THEY'RE HALFWAY THROUGH. LISTEN FOR THE WIND-UP.",
    ],
    z: [
      "BLADE FLURRY. A STORM OF STABS THAT HITS STUNNED FOES MUCH HARDER.",
      "PARRY, THEN FLURRY. THE COUNTER STUNS THEM AND THE FLURRY DOES THE REST.",
    ],
    picks: {
      riposte: "A WIDER PARRY THAT GIVES A SHIELD AND A HARDER COUNTER. FOR PEOPLE WHO LIKE TO WAIT.",
      volte: "PARRY BECOMES A SIDESTEP, AND YOUR NEXT ATTACK HITS MUCH HARDER. FOR PEOPLE WHO DON'T.",
      blinkstep: "LUNGE TWICE, AND A GHOST OF YOU LUNGES AGAIN. WITH VOLTE, SIDESTEPPING GIVES LUNGE BACK.",
      marked: "LUNGE MARKS FOES: YOUR WHOLE TEAM HITS THEM HARDER. WITH RIPOSTE, PARRIED FOES ARE MARKED TOO.",
      fleche: "A STRONGER FINISHER THAT SENDS A SLASH THROUGH A LINE. GOOD AGAINST TROOPS.",
      momentum: "EVERY HIT STACKS DAMAGE AND SPEED AND CUTS YOUR PARRY COOLDOWN. LONG FIGHTS BECOME YOURS.",
      thousandcuts: "MORE FLURRY, AND EVEN MORE AGAINST THE STUNNED. RIPOSTE INTO THIS IS NASTY.",
    },
    evo: {
      r: "PATIENT (RIPOSTE) OR SLIPPERY (VOLTE). BOTH ARE GREAT. ONE OF THEM SUITS YOU.",
      b: "LUNGE UPGRADES. BLINK STEP WANTS VOLTE, MARKED WANTS RIPOSTE.",
      a: "FLECHE FOR CLEARING TROOPS, MOMENTUM FOR LONG HERO FIGHTS.",
      z: "THOUSAND CUTS. MORE CUTS THAN A THOUSAND? NO, EXACTLY A THOUSAND. WE COUNTED.",
    },
    tactics:
      "FIGHT THE OTHER HERO, NOT THEIR ARMY. WAIT FOR THEM TO SWING, PARRY, PUNISH WITH FLURRY OR A FULL COMBO. IF THEY STOP SWINGING AT YOU, LUNGE THROUGH THEM AND MAKE THEM.",
    fear: "BEING SWARMED. PARRY ONLY STOPS ONE HIT, AND TEN GRUNTS HAVE TEN SWORDS.",
  },
  warden: {
    lore: "THORN IS A TREE. NOT A MAN DRESSED AS A TREE, NOT A TREE-SHAPED MAN. A TREE. HE GOT INVOLVED IN THE GRUDGE BECAUSE SOMEONE CHOPPED HIS COUSIN INTO A PALISADE. STIG STILL WON'T SAY WHERE HE GOT THE WOOD.",
    role: "THE KEEPER. A TANKY AREA CONTROLLER. WALLS OFF ROADS, SLOWS PEOPLE DOWN, SPEEDS FRIENDS UP AND HITS BUILDINGS HARDER THAN MOST.",
    a: [
      "TWO WIDE SWEEPS OF BARK. HITS EVERYTHING IN FRONT OF YOU.",
      "GREAT FOR CLEARING CLUMPS OF TROOPS. AIM AT THE MIDDLE OF THE CROWD.",
    ],
    b: [
      "LONG ARM SLAP. A RANGED BRANCH SWING THAT KNOCKS BACK AND STUNS BRIEFLY.",
      "SLAP PEOPLE OFF CLIFFS. IT'S NOT IN THE TOOLTIP BUT IT SHOULD BE.",
    ],
    r: [
      "STONE WALL. RAISES A WALL WITH SNARES AT BOTH ENDS. BLOCKS ROADS AND CHOKEPOINTS.",
      "WALL A NARROW GAP BEHIND A FLEEING HERO. THE SNARES WILL GET THEM.",
    ],
    z: [
      "BRAMBLES. A BIG FIELD OF THORNS: FOES ARE SLOWED AND HURT, ALLIES INSIDE MOVE FASTER.",
      "THROW IT UNDER A FIGHT AND STAND IN IT. YOUR WHOLE TEAM BECOMES QUICKER AND THEIRS SLOWER.",
    ],
    picks: {
      rootcage: "THE WALL BECOMES A ROOT TRAP YOU AIM. HOLDS A HERO IN PLACE FOR A GOOD WHILE.",
      rampart: "A BIGGER WALL THAT HEALS ALLIES NEXT TO IT. MAKE A FORT ANYWHERE.",
      graspingvine: "YOUR SLAP PULLS PEOPLE TO YOU AND STUNS THEM. WITH ROOT CAGE, YANKING A ROOTED FOE HURTS MORE.",
      whiplash: "YOUR SLAP HITS A WHOLE LINE AND EXPLODES. WITH LIVING RAMPART IT STUNS TOO.",
      thornguard: "HITS GROW A BARK SHIELD. VERY HARD TO KILL WHILE YOU'RE SWINGING.",
      overgrowth: "YOUR FINISHER ROOTS PEOPLE AND LEAVES BRAMBLES. EVERY COMBO BECOMES A TRAP.",
      ancientgrove: "BIGGER, LONGER BRAMBLES THAT ALSO HEAL ALLIES. A WHOLE FOREST OF BAD NEWS.",
    },
    evo: {
      r: "TRAP (ROOT CAGE) OR FORT (RAMPART).",
      b: "SLAP UPGRADES. GRASPING VINE GOES WITH ROOT CAGE, WHIPLASH WITH RAMPART.",
      a: "SURVIVE (THORNGUARD) OR CONTROL (OVERGROWTH).",
      z: "ANCIENT GROVE. IT'S BRAMBLES BUT WITH HEALING. GRANDMA'S RECIPE.",
    },
    tactics:
      "STAND BETWEEN YOUR BASE AND THEIRS. WALL THE ROADS, SLAP INTRUDERS, DROP BRAMBLES UNDER BIG FIGHTS. YOU'RE STRONG AGAINST BUILDINGS, SO WHEN YOU PUSH, GO STRAIGHT FOR THE TOWERS.",
    fear: "REMNIL AND STIG'S BALLISTA POKING FROM RANGE. YOU'RE SLOW TO CLOSE THE GAP.",
  },
  marksman: {
    lore: "WREN HOLLOWMERE WAS THE BEST POACHER IN THE KING'S FOREST UNTIL THE KING ASKED HER TO STOP. SHE DIDN'T. NOW SHE SHOOTS FOR WHOEVER PAYS, AND PIP, HER HAWK, KEEPS THE CHANGE. PIP HAS STOLEN FOUR CROWNS, ONE WIG AND THORN'S FAVOURITE ACORN.",
    role: "THE LONGBOW. SHOOTS FROM FURTHER THAN ANYONE BUT REMNIL AND HURTS FOR IT, BUT SHE IS FRAIL AND SLOW: SHE HAS TO HIDE AND PICK HER SHOTS. VANTAGE: FROM GROUND A METRE HIGHER THAN HER TARGET, OR AFTER STANDING STILL FOR A SECOND, HER SHOTS HIT 25% HARDER AND REACH 20% FURTHER. A GOLD GLINT ON HER SAYS IT'S ON.",
    a: [
      "ONE HEAVY LONGBOW ARROW, 11M, THEN A 1.4S RELOAD. HOLD A TO DRAW A FULL POWER SHOT THAT PIERCES THROUGH EVERYTHING IN A LINE. MAKE EVERY ARROW COUNT.",
      "PLANT YOUR FEET. A WREN WHO STANDS STILL BEHIND HER SOLDIERS IS A WREN WHO WINS TRADES.",
    ],
    b: [
      "SEND PIP. THE HAWK FLIES OUT (SLOWLY, EVERYONE SEES HIM COMING) AND LATCHES ONTO THE NEAREST FOE (CHAMPIONS FIRST, HOLD B TO AIM) FOR 5S: THEY'RE SLOWED 25%, TAKE 15% MORE FROM YOU, CAN'T HIDE IN GRASS OR SMOKE, PIP PECKS THEM AND EVERY ARROW EARNS A BONUS PECK, AND EVERY CHANNEL BREAKS: RECALL, JUMP PADS, THE GRUDGE, GRAVEWALK, HORNS. PRESS B AGAIN TO CASH IN: PIP RAKES THEIR FACE FOR 70 AND BLINDS THEM FOR 2.5S (HALF THEIR ATTACKS MISS), THEN FLIES HOME.",
      "HOLD THE MARK WHILE YOU SHOOT, THEN RAKE THE MOMENT THEY TURN TO SWING AT YOU.",
    ],
    r: [
      "VOLLEY. A RAIN OF ARROWS FALLS ON A SPOT UP TO 9M AWAY FOR ABOUT 2S. IT HURTS AND SLOWS, AND SOLDIERS TAKE HALF AGAIN AS MUCH.",
      "TAP R TO LOB IT AT WHOEVER YOU'RE FACING, OR HOLD R TO PLACE IT. DROP IT WHERE THEY HAVE TO WALK, NOT WHERE THEY ARE.",
    ],
    z: [
      "HEARTSEEKER. A LONG DRAW, THEN ONE ARROW 28M DOWN A LINE. THE FIRST CHAMPION IT MEETS TAKES A HUGE HIT AND IS KNOCKED BACK; EVERYTHING ELSE IN THE LINE GETS HURT TOO.",
      "YOU STAND STILL WHILE YOU DRAW, SO VANTAGE ALWAYS COUNTS. AIM DOWN A BRIDGE OR A GATE AND LET THEM WALK INTO IT.",
    ],
    picks: {
      firearrows: "THE VOLLEY LEAVES BURNING GROUND. EXCELLENT FOR HOLDING A CHOKEPOINT.",
      doublevolley: "THE SKY FALLS TWICE. SOLDIERS DON'T SURVIVE THE SECOND ONE.",
      longwatch: "PIP STAYS 8S AND THE MARK BITES HARDER.",
      talons: "PIP PECKS EVERY SECOND ON ITS OWN, AND THE PECKS BLEED.",
      broadhead: "ARROWS BURST AROUND THE TARGET. YOUR BASIC ATTACK BECOMES A SOLDIER SHREDDER.",
      quickdraw: "FASTER ARROWS, AND HITTING CHAMPIONS GETS PIP BACK SOONER. FOR HERO HUNTERS.",
      huntersmark: "MARKS EVERYTHING IT HITS FOR YOUR HOUSE AND SENDS PIP AFTER THE CHAMPION.",
    },
    evo: {
      r: "MORE VOLLEY OR BETTER VOLLEY: BURNING GROUND, OR A SECOND RAIN.",
      b: "PIP UPGRADES. LONG WATCH GOES WITH DOUBLE VOLLEY, RAKING TALONS WITH FIRE ARROWS.",
      a: "BROADHEAD FOR SOLDIERS, QUICKDRAW FOR CHAMPIONS.",
      z: "TWO WAYS TO END A FIGHT FROM 28M AWAY. BOTH ARE RUDE.",
    },
    tactics:
      "STAY BEHIND YOUR SOLDIERS, FIND HIGH GROUND OR JUST STOP MOVING, AND SHOOT. SEND PIP AT THE CHAMPION YOU WANT DEAD, THEN LET YOUR ARROWS PECK THEM APART. SAVE VOLLEY FOR CLUMPS OF SOLDIERS AND HEARTSEEKER FOR A HERO IN A LINE.",
    fear: "GRIM. HE'S FAST, HE'S HIDDEN AND HE'S ALREADY BEHIND YOU. KEEP PIP READY: IT FINDS HIM IN THE GRASS, AND SKYSHOT GETS YOU OUT.",
  },
  friar: {
    lore: "BROTHER MADDOCK TOOK A VOW OF POVERTY, A VOW OF SILENCE AND A VOW OF SOBRIETY. HE KEPT THE FIRST ONE. HIS ABBEY BREWS THE BEST ALE IN THE VALLEY AND HE CARRIES A KEG OF IT EVERYWHERE, FOR MEDICINAL REASONS, MOSTLY HIS.",
    role: "THE HEALER. STURDY AND SLOW, HITS SOFTLY, BUT KEEPS EVERYONE AROUND HIM ON THEIR FEET. PLENTY: FRIENDLY SOLDIERS AND CHAMPIONS WITHIN 7M SLOWLY REGENERATE, AND ALL HIS HEALING IS 25% STRONGER ON ANYONE BELOW HALF HEALTH.",
    a: [
      "THREE SWINGS WITH HIS TANKARD AND STAFF. THE LAST ONE IS A BIG BELLY-WEIGHTED WALLOP.",
      "YOU'RE NOT HERE TO WIN DUELS. HIT WHAT COMES CLOSE AND KEEP YOUR KEGS FLYING.",
    ],
    b: [
      "HEALING KEG. LOBS A KEG UP TO 8M THAT BURSTS AND HEALS EVERY FRIEND IN THE SPLASH, CHAMPIONS AND SOLDIERS ALIKE, THEN LEAVES AN ALE PUDDLE THAT KEEPS HEALING ANYONE STANDING IN IT FOR 5S.",
      "TAP B AND IT FINDS THE MOST HURT BUNCH OF FRIENDS ON ITS OWN. HOLD B TO PUT IT EXACTLY WHERE YOU WANT.",
    ],
    r: [
      "POWDER KEG. A KEG WITH A LIT FUSE. IT BLOWS A SECOND AFTER IT LANDS, OR STRAIGHT AWAY IF IT LANDS ON A CHAMPION, KNOCKING EVERYONE BACK. SOLDIERS AND BUILDINGS HATE IT MOST.",
      "THE FUSE GIVES CHAMPIONS A MOMENT TO RUN. SOLDIERS DON'T RUN. TOWERS CAN'T.",
    ],
    z: [
      "BREWFEST. PLANTS A GIANT TAPPED CASK FOR 10S. FRIENDS WITHIN 7M HEAL, HIT 15% HARDER AND SHRUG OFF SLOWS; FOES IN IT GET TIPSY AND SLOW. THE CASK CAN BE SMASHED.",
      "PLANT IT IN THE MIDDLE OF A BIG FIGHT, NOT IN FRONT OF A TOWER. THEY WILL GO FOR THE CASK.",
    ],
    picks: {
      clusterkeg: "THE POWDER KEG SPLITS INTO LITTLE ONES. CARPETS A CROWD OF SOLDIERS.",
      tarkeg: "THE BLAST LEAVES BURNING TAR THAT SLOWS. NOBODY ESCAPES THE SECOND KEG.",
      stout: "EVERY FRIEND IN THE SPLASH ALSO GETS A SHIELD.",
      wellspring: "A BIGGER, LONGER PUDDLE THAT SPEEDS YOUR FRIENDS UP.",
      tapster: "HITS HEAL YOU AND PATCH UP NEARBY SOLDIERS. FOR THE FRIAR WHO LIKES A SCRAP.",
      bellyflop: "THE FINISHER STUNS. NOW YOUR TANKARD IS A REASON TO KEEP AWAY.",
      grandcask: "A BIGGER, LONGER, STURDIER CASK. MORE PARTY.",
    },
    evo: {
      r: "POWDER KEG UPGRADES: MORE KEGS, OR STICKY BURNING TAR.",
      b: "HEALING KEG UPGRADES. HEARTY STOUT GOES WITH CLUSTER KEG, WELLSPRING WITH TAR KEG.",
      a: "SELF-SUSTAIN (TAPROOM BRAWLER) OR CONTROL (BELLY FLOP).",
      z: "A BIGGER PARTY, OR A PARTY THAT ENDS WITH A BANG.",
    },
    tactics:
      "WALK WITH YOUR SOLDIERS AND YOUR PARTNER, KEEP KEGS ON WHOEVER IS HURTING, AND THROW POWDER KEGS INTO EVERY CLUMP AND AT EVERY TOWER IN REACH. BREWFEST WINS BIG FIGHTS: PLANT IT, STAND IN IT, LET YOUR SIDE OUT-LAST THEIRS.",
    fear: "BEING CAUGHT ALONE BY FRANCOIS OR GRIM. YOU'RE STURDY BUT SLOW, AND THEY CAN OUT-DAMAGE YOUR HEALING. A PUDDLE AND A KEG ROCKET ARE YOUR WAY OUT.",
  },
};

const STAT_WORD: Record<string, string> = {
  frail: "FRAIL",
  low: "LOW",
  mid: "AVERAGE",
  high: "HIGH",
  sturdy: "STURDY",
  swift: "VERY FAST",
};

function heroEntry(id: string): CodexEntry {
  const h = HEROES[id];
  const t = TEXT[id];
  const name = h.name.toUpperCase();
  const tal = TALENTS[id];
  const abil = (slot: "a" | "b" | "r" | "z", label: string): CodexPage => {
    const [text, tip] = t[slot];
    const call = h.abilities[slot].callout?.split("·")[0].trim();
    const cd = h.abilities[slot].cooldown;
    return {
      title: `${label}${call ? ` · ${call}` : ""}`,
      text: text + (cd && cd > 1 ? `  COOLDOWN ${cd}S.` : ""),
      tip,
      art: { kind: "shot", hero: id, slot },
    };
  };
  const evo = (slot: "r" | "b" | "a" | "z", level: number, label: string): CodexPage => {
    const list = tal[slot] ?? [];
    return {
      title: `LEVEL ${level} · ${label}`,
      text: t.evo[slot],
      art: { kind: "shot", hero: id, slot },
      picks: list.map((p) => ({ id: p.id, name: p.name, desc: t.picks[p.id] ?? p.desc, combo: p.combo })),
    };
  };
  return {
    cat: "CHAMPIONS",
    title: name,
    glyph:
      id === "warlord"
        ? "slam"
        : id === "engineer"
          ? "ballista"
          : id === "raider"
            ? "dash"
            : id === "summoner"
              ? "summon"
              : id === "duelist"
                ? "parry"
                : id === "marksman"
                  ? "heartseeker"
                  : id === "friar"
                    ? "keg"
                    : "zone",
    pages: [
      {
        title: `${name} · THE LEGEND`,
        text: t.lore,
        tip: `HEALTH ${STAT_WORD[h.health] ?? h.health} · SPEED ${STAT_WORD[h.speed] ?? h.speed} · DAMAGE ${STAT_WORD[h.damage] ?? h.damage}`,
        art: { kind: "portrait", hero: id },
      },
      { title: `${name} · ROLE`, text: t.role, tip: `FEARS: ${t.fear}`, art: { kind: "portrait", hero: id } },
      abil("a", "A · ATTACK"),
      abil("b", "B · SECONDARY"),
      abil("r", "R · SPECIAL"),
      abil("z", "Z · SUPER"),
      evo("r", 2, "SPECIAL EVOLVES"),
      evo("b", 3, "SECONDARY EVOLVES"),
      evo("a", 4, "ATTACK EVOLVES"),
      evo("z", 5, "SUPER EVOLVES"),
      ...(COMBOS[id]
        ? [
            {
              title: `COMBO · ${COMBOS[id][0]}`,
              text: COMBOS[id][1],
              tip: COMBOS[id][2],
              art: { kind: "shot" as const, hero: id, slot: COMBOS[id][3] },
            },
          ]
        : []),
      { title: `${name} · HOW TO WIN`, text: t.tactics, art: { kind: "shot", hero: id, slot: "z" } },
    ],
  };
}

const MAP_DATA = import.meta.glob("../../data/maps/*.json", { eager: true, import: "default" }) as Record<
  string,
  { name: string }
>;

export function buildCodex(mapNames: string[]): CodexEntry[] {
  const sc = U.waves.spawnCost;
  const st = S.types;
  const e = M.economy;
  const sh = M.arena.shop;
  const rel = M.arena.relic;
  const og = M.arena.ogre;
  const can = M.arena.cannon;
  const entries: CodexEntry[] = [
    {
      cat: "BASICS",
      title: "HOW TO FIGHT",
      glyph: "combo",
      pages: [
        {
          title: "HITTING THINGS",
          text: "PRESS A TO SWING. KEEP PRESSING TO CHAIN A COMBO, THE LAST HIT IS ALWAYS THE BIG ONE. HOLD A TO CHARGE A HEAVY HIT. B, R AND Z ARE YOUR ABILITIES. Z ONLY WORKS WHEN THE METER IS FULL, AND IT FILLS AS YOU DEAL AND TAKE DAMAGE.",
          tip: "HITTING SOMEONE FROM BEHIND DEALS EXTRA DAMAGE. SO DOES HITTING THEM WHILE THEY'RE STUNNED.",
          art: { kind: "seal", glyph: "combo" },
        },
        {
          title: "NOT GETTING HIT",
          text: "HOLD L TO BLOCK: HITS FROM THE FRONT BARELY HURT, BUT YOU MOVE SLOWLY. L + X DODGES, A QUICK ROLL WHERE NOTHING CAN TOUCH YOU. IT HAS A SHORT COOLDOWN, SO DON'T SPAM IT. L + A SHOVES PEOPLE AWAY AND STUNS THEM FOR A MOMENT.",
          tip: "A BLOCKER IS VERY ANNOYING. SHOVE THEM, OR WALK AROUND AND HIT THEIR BACK.",
          art: { kind: "seal", glyph: "parry" },
        },
        {
          title: "DYING",
          text: `YOU COME BACK AT YOUR KEEP AFTER A FEW SECONDS. EVERY DEATH COSTS YOUR TEAM ${e.loss.heroDeath} GOLD AND GIVES THE ENEMY A ${e.bounty.hero} GOLD BOUNTY, SO TRY NOT TO DO IT. YOUR MOVES COME BACK ON THE SAME COOLDOWNS YOU DIED WITH, PLUS ${(e as { respawnCooldownPenalty?: number }).respawnCooldownPenalty ?? 2} SECONDS, AND A HALF-CHARGED SUPER IS LOST. A FULL ONE YOU KEEP.`,
          tip: "IF YOU'RE BEHIND YOU LOSE LESS GOLD, AND IN FREE FOR ALL YOU ALSO RESPAWN FASTER. COMEBACKS ARE REAL.",
          art: { kind: "seal", glyph: "none", color: "#4a3a2a" },
        },
        {
          title: "CLIFFS AND HIGH GROUND",
          text: "YOU CAN DROP OFF A CLIFF, BUT YOU CAN'T CLIMB ONE. FIND THE RAMP. TROOPS SHOOTING UPHILL MISS MORE OFTEN, SO HIGH GROUND IS WORTH HOLDING.",
          tip: "GRIM IGNORES MOST OF THIS. HE CLIMBS LIKE A GOAT.",
          art: { kind: "seal", glyph: "peak" },
        },
      ],
    },
    {
      cat: "BASICS",
      title: "LEVELLING UP",
      glyph: "rally",
      pages: [
        {
          title: "EXPERIENCE",
          text: "YOU EARN EXPERIENCE BY HURTING HEROES, KILLING TROOPS AND BREAKING BUILDINGS, PLUS A SLOW TRICKLE JUST FOR BEING ALIVE. EACH LEVEL ALSO GIVES YOU A BIT MORE HEALTH AND DAMAGE.",
          tip: "FIGHTING THE OTHER HERO IS THE FASTEST WAY TO LEVEL. ALSO THE FASTEST WAY TO DIE.",
          art: { kind: "seal", glyph: "rally" },
        },
        {
          title: "EVOLUTIONS",
          text: "AT LEVELS 2, 3, 4 AND 5 ONE OF YOUR ABILITIES EVOLVES: SPECIAL (R), THEN SECONDARY (B), THEN ATTACK (A), THEN SUPER (Z). FOR EACH ONE YOU PICK ONE OF TWO VERSIONS WITH LEFT OR RIGHT ON THE ORDERS STICK.",
          tip: "THE CHOICE IS PERMANENT FOR THE MATCH. READ BOTH.",
          art: { kind: "seal", glyph: "works" },
        },
        {
          title: "SYNERGIES",
          text: "YOUR SECONDARY EVOLUTION ALWAYS HAS A BONUS IF IT MATCHES A CERTAIN SPECIAL EVOLUTION. THE CHAMPION PAGES IN THIS BOOK LIST EVERY PAIR. IN SHORT: DECIDE YOUR PLAN AT LEVEL 2 AND STICK TO IT AT LEVEL 3.",
          tip: "MIXING AND MATCHING STILL WORKS, YOU JUST MISS THE BONUS.",
          art: { kind: "seal", glyph: "hex" },
        },
      ],
    },
    {
      cat: "ARMY",
      title: "YOUR TROOPS",
      glyph: "banner",
      pages: [
        {
          title: "THREE KINDS OF SOLDIER",
          text: `GRUNTS (${sc.grunt} GRAIN): CHEAP, QUICK, GOOD AT HACKING BRUTES APART. ARCHERS (${sc.ranged} GRAIN): SHOOT FROM RANGE, SHRED GRUNTS. BRUTES (${sc.heavy} GRAIN): BIG, SLOW, SMASH ARCHERS AND BUILDINGS.`,
          tip: "GRUNTS BEAT BRUTES. ARCHERS BEAT GRUNTS. BRUTES BEAT ARCHERS. A MIXED ARMY BEATS ANY SINGLE KIND.",
          art: { kind: "scene", scene: "troops" },
        },
        {
          title: "VETERANS",
          text: "TROOPS THAT GET KILLS RANK UP: VETERAN, ELITE, THEN HEROIC. EACH RANK HITS HARDER, HAS MORE HEALTH AND HEALS A BIT. HEROIC TROOPS SLOWLY REGENERATE.",
          tip: `KEEPING TROOPS ALIVE MATTERS. THE ARMY CAP IS ${U.popCap}, SO DON'T THROW THEM AWAY.`,
          art: { kind: "seal", glyph: "rank", color: "#c8a020" },
        },
      ],
    },
    {
      cat: "ARMY",
      title: "GIVING ORDERS",
      glyph: "rally",
      pages: [
        {
          title: "THE FOUR ORDERS",
          text: "FLICK THE ORDERS STICK (C, OR THE ARROW KEYS). UP: ATTACK, MARCH ON THE ENEMY KEEP. FLICK UP AGAIN WHILE ATTACKING TO PICK A LANE (TOP, MIDDLE, BOTTOM, THEN ANY), OR IN FREE FOR ALL WHICH HOUSE TO HIT. LEFT: FOLLOW YOU AROUND. RIGHT: DEFEND, GO HOME AND GUARD EVERY GATE. DOWN: HOLD, STAY WHERE YOU ARE.",
          tip: "D-PAD LEFT AND RIGHT PICK WHO OBEYS: EVERYONE, OR JUST GRUNTS, ARCHERS OR BRUTES.",
          art: { kind: "seal", glyph: "rally" },
        },
        {
          title: "WHEN TO USE WHAT",
          text: "ATTACK WHEN YOU HAVE A BIG ARMY. FOLLOW WHEN YOU WANT TO PUSH TOGETHER WITH YOUR HERO. DEFEND WHEN SOMEONE IS BREAKING INTO YOUR BASE: YOUR TROOPS SPLIT ACROSS EVERY ENTRANCE AND HUNT ANYTHING THAT GETS INSIDE. HOLD WHEN YOU WANT A WALL OF BODIES SOMEWHERE SPECIFIC.",
          tip: "ARCHERS ON HOLD BEHIND GRUNTS ON ATTACK IS A CLASSIC FOR A REASON.",
          art: { kind: "seal", glyph: "wall" },
        },
      ],
    },
    {
      cat: "ARMY",
      title: "OUTPOSTS",
      glyph: "castle",
      pages: [
        {
          title: "WHERE TROOPS COME FROM",
          text: `TROOPS ONLY COME FROM OUTPOSTS. BUILD THEM ON PADS WITH X: A BARRACKS MAKES GRUNTS, A RANGE MAKES ARCHERS, A FOUNDRY MAKES BRUTES. EACH COSTS ${st.barracks.cost} GOLD. EACH OUTPOST KEEPS ITS OWN CLOCK FROM THE MOMENT IT'S BUILT: A BARRACKS SENDS A GRUNT EVERY ${st.barracks.cadence} SECONDS, A RANGE AN ARCHER EVERY ${st.range.cadence}, A FOUNDRY A BRUTE EVERY ${st.foundry.cadence}, AND UPGRADED ONES ARE A THIRD FASTER. YOU PAY GRAIN FOR EACH SOLDIER AS IT COMES OUT. WHEN ONE OF ITS SOLDIERS DIES, THAT OUTPOST TAKES A MOMENT LONGER TO SEND THE NEXT. WHILE ANY CHAMPION OF YOUR HOUSE IS DOWN, EVERY OUTPOST STOPS, AND WHEN THEY'RE BACK EACH ONE STARTS ITS COUNT FROM ZERO.`,
          tip: "NO GRAIN, NO TROOPS. IF YOUR OUTPOSTS GO QUIET, CHECK YOUR SACK.",
          art: { kind: "seal", glyph: "castle" },
        },
        {
          title: "MIXED OUTPOSTS",
          text: `SOME FIELDS ARE TOO CRAMPED FOR SPECIALISTS. THERE YOU CAN ONLY BUILD A PLAIN OUTPOST, ${st.outpost.cost} GOLD, AND EVERY SOLDIER IT SENDS IS PICKED AT RANDOM: ABOUT ${Math.round((st.outpost.mix?.grunt ?? 0) * 100)}% GRUNTS, ${Math.round((st.outpost.mix?.ranged ?? 0) * 100)}% ARCHERS AND ${Math.round((st.outpost.mix?.heavy ?? 0) * 100)}% BRUTES. RIGHT NOW THAT'S THE RUINS.`,
          tip: "YOU DON'T GET TO CHOOSE. NEITHER DO THEY. IT'S VERY DEMOCRATIC.",
          art: { kind: "seal", glyph: "castle" },
        },
        {
          title: "UPGRADES AND FORWARD OUTPOSTS",
          text: `UPGRADE AN OUTPOST (Y AT ITS PAD, ${st.barracks.upgradeCost} GOLD) TO SEND SOLDIERS FASTER, WITH BETTER STATS. OUTPOSTS ON FORWARD OR NEUTRAL PADS MAKE TOUGHER SOLDIERS, AND STANDING NEAR ONE HEALS YOU LIKE YOUR OWN TURF.`,
          tip: "A FORWARD OUTPOST IS A SECOND HOME. LOSE IT AND YOU'LL FEEL IT.",
          art: { kind: "seal", glyph: "banner" },
        },
      ],
    },
    {
      cat: "ARMY",
      title: "GOLD AND GRAIN",
      glyph: "repair",
      pages: [
        {
          title: "TWO PURSES",
          text: `GOLD PAYS FOR BUILDINGS, UPGRADES AND THE KEEP SHOP. GRAIN FEEDS YOUR ARMY: EVERY SOLDIER YOUR OUTPOSTS SEND COSTS GRAIN, AND SO DOES EVERY TOWER SHOT AND PULSE. BOTH ARE NEXT TO YOUR KEEP GEM; THE NUMBER AFTER THE SACK IS YOUR GRAIN PER SECOND.`,
          tip: "BUILDINGS FEED YOU, KILLS PAY YOU. A HOUSE THAT ONLY BUILDS STARVES FOR GOLD, A HOUSE THAT ONLY FIGHTS STARVES FOR GRAIN.",
          art: { kind: "seal", glyph: "repair" },
        },
        {
          title: "MAKING GOLD",
          text: `GOLD COMES FROM KILLING. EVERY ENEMY SOLDIER PAYS A FEW COINS, A HERO ${e.bounty.hero}, A BUILDING ${e.bounty.structure}. YOUR KEEP ADDS A TRICKLE OF ${e.income} A SECOND SO A QUIET START ISN'T FROZEN.`,
          tip: "YOUR ARMY IS YOUR INCOME. A WAVE THAT DIES FOR NOTHING IS GOLD YOU NEVER SEE.",
          art: { kind: "seal", glyph: "quake" },
        },
        {
          title: "MAKING GRAIN",
          text: `GRAIN COMES FROM YOUR BUILDINGS. YOUR KEEP GROWS ${e.grain?.base ?? 0} A SECOND, AND EVERY FINISHED TOWER OR OUTPOST ADDS ${(e.grain?.perLevel ?? []).join(", ")} AT LEVEL ${(e.grain?.perLevel ?? []).map((_, k) => k + 1).join(", ")}. GRAIN YOU DON'T NEED IS NOT WASTED: ABOVE ${e.grain?.surplus ?? 0} IN THE SACK, EVERY OUTPOST WORKS FASTER. RUN OUT AND YOUR OUTPOSTS GO QUIET AND YOUR TOWERS FIRE AT A CRAWL.`,
          tip: "UPGRADING ISN'T JUST A STRONGER BUILDING. IT'S MORE BREAD.",
          art: { kind: "seal", glyph: "castle" },
        },
        {
          title: "LOSING IT",
          text: `EVERY TIME YOUR HERO DIES YOUR TEAM LOSES ${e.loss.heroDeath} GOLD. EVERY TOWER YOU LOSE COSTS ${e.loss.tower}. AND WHEN THE ENEMY FELLS ONE OF YOUR TOWERS, THEIR WHOLE ARMY RALLIES: +${pct(e.rally.damageMul)} DAMAGE AND +${pct(e.rally.speedMul)} SPEED FOR ${e.rally.seconds} SECONDS.`,
          tip: "THE SAME GOES FOR YOU. KNOCK A TOWER DOWN AND CHARGE WHILE THE RALLY LASTS.",
          art: { kind: "seal", glyph: "quake" },
        },
      ],
    },
    {
      cat: "BASE",
      title: "TOWERS",
      glyph: "turret",
      pages: [
        {
          title: "THE THREE TOWERS",
          text: `BUILD WITH Y AT A PAD. DAMAGE TOWER: SHOOTS BOLTS. CONTROL TOWER: PULSES AROUND ITSELF, SLOWS AND SHOVES. SUPPORT TOWER: HEALS FRIENDS AND MAKES THEM HIT HARDER. EACH COSTS ${st.damage.cost}, UPGRADES ${st.damage.upgradeCost}.`,
          tip: "THERE'S NO LIMIT. IF YOU HAVE THE PADS AND THE GOLD, BUILD.",
          art: { kind: "seal", glyph: "turret" },
        },
        {
          title: "WHO TOWERS SHOOT",
          text: "TOWERS SHOOT YOUR TROOPS FIRST. THEY ONLY SWITCH TO YOU IF YOU WALK IN WITH NO TROOPS AROUND, OR IF YOU HIT SOMETHING OF THEIRS NEAR THE TOWER.",
          tip: "NEVER DIVE A TOWER ALONE. WALK IN BEHIND YOUR SOLDIERS AND LET THEM SOAK THE BOLTS.",
          art: { kind: "seal", glyph: "shoot" },
        },
        {
          title: "LANE TOWERS",
          text: "TOWERS ON FORWARD AND NEUTRAL PADS ARE MUCH TOUGHER, HIT MUCH HARDER AND SLOW HEROES THEY SHOOT. YOU CAN'T JUST JOG PAST THEM. TOWERS INSIDE YOUR BASE ARE NORMAL ONES.",
          tip: "TAKE THE LANE TOWER FIRST, THEN THE ROAD IS OPEN.",
          art: { kind: "seal", glyph: "wall" },
        },
        {
          title: "LEVEL 3 TOWERS",
          text: `A LEVEL 2 DAMAGE OR CONTROL TOWER CAN GO ONE STEP FURTHER. HOLD Y AT IT AND PICK ONE OF THREE FOR ${st.damage.specCost ?? 250} GOLD. EACH ONE CHANGES HOW THE TOWER FIGHTS, NOT JUST HOW HARD, AND YOU CAN SEE WHICH ONE IT IS FROM ACROSS THE FIELD.`,
          tip: "LOOK AT WHAT THEY'RE SENDING. FIREPOTS EAT GRUNT SWARMS, A BALLISTA SKEWERS A LINE, A GRAVITY WELL HOLDS THEM FOR YOUR ARMY.",
          art: { kind: "seal", glyph: "turret", color: "#c8a020" },
        },
        ...[
          ...(st.damage.specs ?? []).map((sp) => ["DAMAGE", sp] as const),
          ...(st.control.specs ?? []).map((sp) => ["CONTROL", sp] as const),
        ].map(([kind, sp]) => ({
          title: `${kind} · ${sp.name}`,
          text: sp.blurb,
          tip: SPEC_TIPS[sp.id] ?? "",
          art: { kind: "scene" as const, scene: `tower:${sp.id}` },
        })),
        {
          title: "RUBBLE",
          text: `A DESTROYED BUILDING LEAVES RUBBLE FOR ${S.rubbleSeconds} SECONDS. THE OWNER CAN'T REBUILD THERE UNTIL IT CLEARS, BUT THE ENEMY CAN BUILD STRAIGHT ON IT.`,
          tip: "STEAL THEIR PAD THE MOMENT IT FALLS.",
          art: { kind: "seal", glyph: "quake", color: "#6a6058" },
        },
      ],
    },
    {
      cat: "BASE",
      title: "KEEP AND SHOP",
      glyph: "castle",
      pages: [
        {
          title: "THE KEEP",
          text: "YOUR KEEP IS YOUR LIFE. LOSE IT AND YOU LOSE. IF TIME RUNS OUT, WHOEVER DID MORE DAMAGE TO THE OTHER KEEP WINS. YOUR KEEP HAS A WARD THAT SOAKS DAMAGE AT FIRST.",
          tip: "EVERY HIT ON THEIR KEEP COUNTS. EVEN ONE BRUTE SMACKING IT ADDS UP.",
          art: { kind: "scene", scene: "keep" },
        },
        {
          title: "THE SHOP",
          text: `PRESS Y AT YOUR KEEP. BOMB (${sh.bomb.cost}): THROW IT, OR STICK IT TO A BUILDING. IT FLATTENS A TOWER AND DOES ${sh.bomb.coreDamage} TO A KEEP. YOUR HOUSE CAN BUY ONE EVERY ${(sh.bomb as { cooldown?: number }).cooldown ?? 20} SECONDS, AND YOU CAN'T RIDE A JUMP PAD WHILE HOLDING ONE. SHIELD (${sh.ward.cost}): PATCHES A QUARTER OF YOUR KEEP'S WARD BACK. CANNON (${sh.cannon.cost}): AIM ${sh.cannon.shots} SHELLS ANYWHERE ON THE FIELD.`,
          tip: "A BOMB THROWN INTO A CLUMP OF TROOPS DELETES THEM. THEY DON'T LIKE THAT.",
          art: { kind: "seal", glyph: "trap" },
        },
        {
          title: "RECALL",
          text: "AWAY FROM YOUR KEEP, PRESS Y TO RECALL: STAND STILL FOR 6 SECONDS AND YOU'RE TELEPORTED HOME. MOVING, ATTACKING OR GETTING HIT CANCELS IT. ONCE PER LIFE.",
          tip: "RECALL THE MOMENT YOU SEE SOMEONE SNEAKING INTO YOUR BASE, NOT WHEN THE KEEP IS ON FIRE.",
          art: { kind: "seal", glyph: "leap" },
        },
      ],
    },
    {
      cat: "BASE",
      title: "BUILDING",
      glyph: "works",
      pages: [
        {
          title: "PADS",
          text: `EVERY BUILDING GOES ON A PAD. HOME PADS ARE IN YOUR BASE, FORWARD PADS ARE OUT IN YOUR HALF, NEUTRAL PADS ARE IN THE MIDDLE. BUILDING TAKES ABOUT ${S.buildSeconds} SECONDS, FASTER WITH TWO HEROES OR WITH TROOPS NEARBY.`,
          tip: "BUILT HALF A TOWER AND RAN? IT KEEPS BUILDING SLOWLY ON ITS OWN WHEN TROOPS ARE CLOSE.",
          art: { kind: "seal", glyph: "pad" },
        },
        {
          title: "WHAT TO BUILD FIRST",
          text: "ONE OUTPOST FOR TROOPS, THEN A TOWER ON YOUR FORWARD PAD, THEN A SECOND OUTPOST. AFTER THAT, UPGRADE WHAT YOU HAVE BEFORE BUILDING NEW STUFF IN THE MIDDLE.",
          tip: "STIG BUILDS EVERYTHING CHEAPER. IF YOU HAVE A STIG, LET HIM BUILD.",
          art: { kind: "seal", glyph: "works" },
        },
      ],
    },
    {
      cat: "ARENA",
      title: "THE GRUDGE",
      glyph: "hex",
      pages: [
        {
          title: "THE RELIC",
          text: `AFTER ${rel.firstSeconds} SECONDS THE GRUDGE APPEARS IN THE MIDDLE OF THE FIELD. PICK IT UP AND CARRY IT HOME. YOU'RE SLOWER WHILE CARRYING AND CAN'T ATTACK. PRESS L TO DROP IT.`,
          tip: "SEND SOMEONE WITH ESCORTS. A LONE CARRIER IS A GIFT. IF THEY'RE ABOUT TO CATCH YOU, DROP IT BEHIND A FRIEND.",
          art: { kind: "scene", scene: "grudge" },
        },
        {
          title: "ENSHRINING IT",
          text: `STAND AT A TOWER, OUTPOST OR YOUR KEEP FOR ${rel.enshrineSeconds} SECONDS TO ENSHRINE IT. A TOWER SHRINE HITS HARDER AND FURTHER, AN OUTPOST SHRINE SENDS EXTRA, TOUGHER TROOPS, THE KEEP SHRINE REGROWS ITS WARD. ANY SHRINE GIVES ${pct(rel.incomeMul)} MORE GOLD.`,
          tip: `THE ENEMY CAN STEAL IT BACK BY STANDING ON IT FOR ${rel.stealSeconds} SECONDS. GUARD YOUR SHRINE.`,
          art: { kind: "seal", glyph: "castle", color: "#c8a020" },
        },
      ],
    },
    {
      cat: "ARENA",
      title: "THE OGRE",
      glyph: "slam",
      pages: [
        {
          title: "BIG, GREEN, NEUTRAL",
          text: `AFTER ${og.firstSeconds} SECONDS AN OGRE WAKES UP SOMEWHERE ON THE FIELD. ${og.hp} HEALTH AND AN ENORMOUS CLUB. HE HATES EVERYONE EQUALLY, WHICH IS VERY FAIR OF HIM. HE STOMPS UP AND DOWN HIS BEAT, STOPS AT EACH END TO LOOK AROUND, AND ONLY REALLY WATCHES WHAT'S IN FRONT OF HIM. GET SPOTTED AND HE CHARGES UNTIL YOU'RE WELL OFF HIS BEAT.`,
          tip: "DON'T FIGHT HIM AT THE SAME TIME AS THE ENEMY. LET THEM WEAKEN HIM FIRST.",
          art: { kind: "unit", type: "ogre" },
        },
        {
          title: "THE BLESSING",
          text: `KILL HIM AND YOUR TEAM GETS ${og.bounty} GOLD AND A BLESSING FOR ${og.blessSeconds} SECONDS: MORE DAMAGE, MORE SPEED, A BIG CHUNK OF EXPERIENCE AND SOME HEALING. HE COMES BACK ${og.respawnSeconds} SECONDS LATER.`,
          tip: "A BLESSED PUSH RIGHT AFTER THE OGRE IS THE STRONGEST MOVE IN THE GAME.",
          art: { kind: "seal", glyph: "rally", color: "#2a7a20" },
        },
      ],
    },
    {
      cat: "ARENA",
      title: "THE CANNON",
      glyph: "ballista",
      pages: [
        {
          title: "INCOMING",
          text: `FROM ${can.firstSeconds} SECONDS ON, EVERY ${can.everySeconds} SECONDS OR SO, A WILD CANNON SHELLS THE FIELD. YOU GET A WARNING CIRCLE A MOMENT BEFORE EACH SHELL LANDS. ${can.damage} TO TROOPS AND HEROES, ${can.structureDamage} TO BUILDINGS, NEVER THE KEEP.`,
          tip: "WALK OUT OF THE CIRCLES. THIS IS ALL OF THE ADVICE.",
          art: { kind: "seal", glyph: "ballista" },
        },
      ],
    },
    {
      cat: "ARENA",
      title: "FREE FOR ALL",
      glyph: "banner",
      pages: [
        {
          title: "FOUR HOUSES",
          text: `SOME FIELDS HAVE FOUR KEEPS: BLUE, RED, YELLOW AND GREEN. EVERY HOUSE GETS ONE CHAMPION, UP TO ${U.popCap} SOLDIERS AND ZERO FRIENDS. EVERY PAD OUTSIDE THE KEEPS IS NEUTRAL, SO WHOEVER BUILDS ON IT FIRST OWNS IT, UNTIL SOMEONE ELSE DISAGREES WITH A BRUTE. ARMIES ARE BIGGER HERE: TROOPS COME EVERY 12 SECONDS, OUTPOSTS AND SOLDIERS COST A QUARTER LESS, THE CAP IS HALF AGAIN AS HIGH, AND THREE ARCHERS STAND GUARD AT YOUR KEEP SO YOU CAN GO FIGHT. ORDER ATTACK AGAIN WHILE YOUR TROOPS ARE ALREADY ATTACKING TO PICK WHICH HOUSE THEY MARCH ON: EACH PRESS MOVES TO THE NEXT HOUSE, THEN BACK TO WHOEVER IS NEAREST. THE ATTACK BADGE TURNS THAT HOUSE'S COLOUR.`,
          tip: `THE GRUDGE STILL WAKES IN THE MIDDLE AFTER ${rel.firstSeconds} SECONDS. ALL FOUR HOUSES CAN SEE IT. ALL FOUR WANT IT. THIS GOES ABOUT AS WELL AS YOU'D THINK.`,
          art: { kind: "seal", glyph: "banner", color: "#2a8a3a" },
        },
        {
          title: "JUMP PADS",
          text: "FREE FOR ALL FIELDS ARE BIG, SO THEY'RE DOTTED WITH SPRING PADS. STAND ON ONE FOR A SECOND AND IT FLINGS YOU ACROSS THE MAP (GET HIT WHILE IT WINDS UP AND IT FIZZLES). AFTER EACH JUMP THE PAD NEEDS 5 SECONDS TO RESET, SO NOBODY CAN FOLLOW YOU THROUGH IT. ROUTES: FROM THE MIDDLE BACK TO YOUR KEEP, FROM YOUR KEEP TO THE MIDDLE, AND BETWEEN THE ARMS. THEY ONLY GO ONE WAY, SO THE TRIP BACK IS A DIFFERENT PAD AND A BIT OF A WALK. THE MINIMAP SHOWS WHERE EACH ONE LANDS. YOU CAN'T TAKE THE GRUDGE ALONG.",
          tip: "YOUR ARMY CAN'T JUMP. YOU CAN. USE IT TO GET BACK TO A FIGHT YOUR SOLDIERS ARE LOSING.",
          art: { kind: "seal", glyph: "leap", color: "#c8a020" },
        },
        {
          title: "LAST HOUSE STANDING",
          text: "LOSE YOUR KEEP AND YOUR HOUSE IS OUT. YOUR TOWERS CRUMBLE, YOUR SOLDIERS WANDER HOME AND YOUR CHAMPION STAYS DOWN, SULKING. THE LAST HOUSE WITH A KEEP WINS. IF THE BELL TOLLS FIRST, THE HOUSE STILL STANDING THAT DID THE MOST DAMAGE TO OTHER KEEPS TAKES IT.",
          tip: `TWO HOUSES FIGHTING IS GREAT NEWS FOR THE OTHER TWO. A FALLEN CHAMPION STILL PAYS ${e.bounty.hero} GOLD TO WHOEVER DID IT, SO EVERYONE IS ALWAYS LOOKING AT YOU.`,
          art: { kind: "seal", glyph: "castle", color: "#c89a14" },
        },
      ],
    },
  ];
  const md = (name: string) => Object.values(MAP_DATA).find((m) => m.name === name) as Record<string, any> | undefined;
  const cr = md("Grudgeholm Crossing")?.mist ?? {};
  const ru = md("Grudgekeep Ruins")?.lantern ?? {};
  const fc = md("Frostcross Summit")?.avalanche ?? {};
  const ga = md("Bellwick Gardens") ?? {};
  const gg = ga.gates ?? {};
  const gf = ga.fountain ?? {};
  const sh2 = md("Grudgetide Shoals")?.tide ?? {};
  const MAP_TEXT: Record<
    string,
    { glyph: string; text: string; tip: string; mech?: { title: string; text: string; tip: string } }
  > = {
    "Grudgeholm Crossing": {
      glyph: "river",
      text: "A LONG FIELD SPLIT BY TWO RIVER CHANNELS. THE MIDDLE ISLAND HOLDS THE NEUTRAL PADS AND THE FORDS ARE SLOW TO CROSS. EACH KEEP HAS A NORTH GATE, A SOUTH GATE AND A BRIDGE TO THE EAST.",
      tip: "THE FORDS ARE THE KILLING GROUND. FIGHT ON THE ISLAND, NOT IN THE WATER.",
      mech: {
        title: "RIVER MIST",
        text: `EVERY ${cr.everySeconds ?? 75} SECONDS OR SO A MIST ROLLS DOWN BOTH RIVERS, SITS THERE FOR ABOUT ${cr.holdSeconds ?? 16} SECONDS LOOKING MYSTERIOUS, THEN WANDERS OFF SOUTH. ANYTHING IN THE MIST IS HIDDEN, JUST LIKE TALL GRASS: TOWERS CAN'T SEE IN, AND WHOEVER SWINGS FIRST OUT OF IT GETS THE AMBUSH BONUS.`,
        tip: "THE FORDS ARE NOW ALSO THE HIDING GROUND. WALK INTO THE MIST CAREFULLY. SOMETHING IN THERE IS WAITING TO HIT YOU, AND IT MIGHT BE A TREE.",
      },
    },
    "Grudgekeep Ruins": {
      glyph: "castle",
      text: "A SQUARE OF OLD WALLS AND PITS, MIRRORED CORNER TO CORNER. EACH KEEP HAS A FRONT GATE TOWARD THE CENTRE AND A BACK GATE IN THE SIDE. THE OTHER TWO CORNERS ARE OLD GRAVEYARDS NOBODY VISITS. THERE'S SO LITTLE ROOM THAT EVERY OUTPOST HERE IS A MIXED ONE: YOU BUILD IT, IT DECIDES WHO TO SEND.",
      tip: "THE BACK GATE IS EASY TO FORGET. SO IS THE GRIM WALKING THROUGH IT.",
      mech: {
        title: "THE BONE LANTERN",
        text: `EVERY ${ru.everySeconds ?? 60} SECONDS SOMETHING IN THE PITS WAKES UP AND A BONE LANTERN FLOATS OUT, THEN DRIFTS OFF TO THE NEAREST EMPTY GRAVEYARD CORNER TO SULK FOR ${ru.restSeconds ?? 25} SECONDS. THE FIRST CHAMPION TO TOUCH IT IS HAUNTED FOR ${ru.hauntSeconds ?? 20} SECONDS: ${Math.round(((ru.damageMul ?? 1.3) - 1) * 100)}% MORE DAMAGE AND ${Math.round(((ru.speedMul ?? 1.15) - 1) * 100)}% MORE SPEED. THE DEAD DO NOT CHECK WHICH SIDE YOU ARE ON.`,
        tip: "YOU CAN GRAB IT WHILE IT'S STILL DRIFTING. IF YOU WAIT FOR IT IN THE CORNER, SO WILL THE OTHER CHAMPION, AND NOW THERE ARE TWO OF YOU IN A GRAVEYARD.",
      },
    },
    "Grudgetide Shoals": {
      glyph: "tide",
      text: "TWO ISLAND KEEPS ON A MUD FLAT. EACH HOUSE HAS ITS OWN DRY STONE CAUSEWAY ON ITS OWN FLANK. THE KEEPS ARE ON CLIFFS: YOU CAN DROP OFF THEM BUT NOT CLIMB BACK UP.",
      tip: "WEAR BOOTS. NOT THAT YOU CAN.",
      mech: {
        title: "THE TIDE",
        text: `EVERY ${(sh2.lowSeconds ?? 40) + (sh2.highSeconds ?? 30)} SECONDS THE TIDE COMES IN AND THE FLATS FLOOD FOR ${sh2.highSeconds ?? 30} SECONDS, SLOWING EVERYONE ON THEM. THEN IT GOES BACK OUT, AS TIDES DO.`,
        tip: "PUSH AT LOW TIDE. AT HIGH TIDE, STICK TO THE CAUSEWAYS AND ISLETS.",
      },
    },
    "Frostcross Summit": {
      glyph: "peak",
      text: "A FREE FOR ALL FIELD. FOUR KEEPS SIT AT THE FEET OF A FROZEN CROSS, WITH THE GRUDGE UP ON THE SUMMIT IN THE MIDDLE. BETWEEN THE ARMS ARE DEEP ICY BOWLS, CROSSED BY NARROW ROCK CAUSEWAYS THAT LINK EACH KEEP TO ITS NEIGHBOURS. THE OGRE LIVES ON THOSE.",
      tip: "YOUR NEIGHBOURS ARE CLOSER THAN THE HOUSE ACROSS THE PEAK. SO ARE YOU, TO THEM.",
      mech: {
        title: "AVALANCHE",
        text: `EVERY ${fc.everySeconds ?? 38} SECONDS ONE ARM RUMBLES FOR ${fc.warnSeconds ?? 6} SECONDS, THEN A WALL OF SNOW COMES DOWN IT FROM THE SUMMIT TOWARD THE KEEP. CHAMPIONS TAKE ${fc.heroDamage ?? 140} DAMAGE AND GET SHOVED; SOLDIERS LOSE ${Math.round((fc.unitDamage ?? 0.75) * 100)}% OF THEIR HEALTH. BUILDINGS ARE FINE. THE SNOW STAYS FOR ${fc.driftSeconds ?? 14} SECONDS AND SLOWS EVERYONE WADING THROUGH IT. IT GOES ROUND THE ARMS CLOCKWISE.`,
        tip: "WHEN THE SNOW RUMBLES, GET OUT OF THE LANE. IF YOU CAN COUNT, YOU KNOW WHICH LANE IS NEXT. ON EACH CAUSEWAY SITS AN AVALANCHE HORN: STAND AT IT ALONE FOR 3 SECONDS AND IT SENDS THE NEXT AVALANCHE DOWN A NEIGHBOUR'S ARM, NEVER YOURS. THEN IT NEEDS 75 SECONDS TO RECHARGE.",
      },
    },
    "Bellwick Gardens": {
      glyph: "bell",
      text: "A FREE FOR ALL FIELD. FOUR KEEPS IN THE CORNERS OF A VERY POSH WALLED GARDEN. A GRAVEL AVENUE RUNS FROM EACH KEEP PAST A ROUNDABOUT TOWER TO THE COURT IN THE MIDDLE. EVERYTHING ELSE IS HEDGES.",
      tip: "THE AVENUE NEVER CLOSES. THE HEDGES NEVER OPEN. EVERYTHING IN BETWEEN DEPENDS ON THE BELLS.",
      mech: {
        title: "BELLS AND THE FOUNTAIN",
        text: `EVERY ${gg.everySeconds ?? 40} SECONDS THE BELLS RING AND THE IRON GATES SWAP: EITHER THE OUTER GATES NEAR THE KEEPS ARE OPEN, OR THE GATES INTO THE COURT AND THE MIDDLE OF THE BORDERS. THE GRUDGE SITS IN A FOUNTAIN. CHAMPIONS WADING IN THE BASIN HEAL ${gf.heal ?? 32} HEALTH A SECOND.`,
        tip: "THE FOUNTAIN HEALS EVERYONE. THAT INCLUDES THE THREE PEOPLE TRYING TO DROWN YOU IN IT.",
      },
    },
  };
  mapNames.forEach((name, index) => {
    const m = MAP_TEXT[name] ?? { glyph: "river", text: "A FIELD OF BATTLE. IT HAS GRASS ON IT.", tip: "WIN." };
    const pages: CodexEntry["pages"] = [
      { title: name.toUpperCase(), text: m.text, tip: m.tip, art: { kind: "map", index } },
    ];
    pages[0].art = { kind: "scene", scene: `map:${index}` };
    if (m.mech)
      pages.push({
        title: m.mech.title,
        text: m.mech.text,
        tip: m.mech.tip,
        art: { kind: "scene", scene: `map:${index}` },
      });
    entries.push({ cat: "FIELDS", title: name.toUpperCase().replace(/^GRUDGE\w*\s*/, ""), glyph: m.glyph, pages });
  });
  const heroes = Object.keys(TEXT).filter((h) => HEROES[h]);
  const hh = HEROES.herald;
  const hab = (slot: "a" | "b" | "r" | "z", label: string, text: string, tip: string): CodexPage => {
    const call = hh?.abilities[slot].callout?.split("·")[0].trim();
    const cd = hh?.abilities[slot].cooldown;
    return {
      title: `${label}${call ? ` · ${call}` : ""}`,
      text: text + (cd && cd > 1 ? `  COOLDOWN ${cd}S.` : ""),
      tip,
      art: { kind: "shot", hero: "herald", slot },
    };
  };
  const herald: CodexEntry = {
    cat: "HERALD",
    title: "THE HERALD",
    glyph: "banner",
    pages: [
      {
        title: "THE HERALD · THE COMMANDER",
        text: "A SKINNY KNIGHT WITH A VERY BIG FLAG. IN 2V2 HE CAN TAKE THE THIRD OR FOURTH SEAT, OR A CHAMPION CAN BECOME HIM MID-MATCH. HE SEES THE WHOLE ARMY, D-PAD UP SENDS A GROUP TO SIEGE, D-PAD DOWN MAKES THEM HOLD, AND HIS ORDERS BEAT HIS PARTNER'S. NO TALENTS, JUST AN ARMY.",
        tip: "HE'S NOT HERE TO WIN FIGHTS. HE'S HERE TO MAKE SURE YOUR SOLDIERS WIN THEM.",
        art: { kind: "portrait", hero: "herald" },
      },
      hab(
        "a",
        "A · ATTACK",
        "A QUICK, WEAK BOLT. ENOUGH TO FINISH A SOLDIER OR ANNOY A CHAMPION.",
        "IF YOU'RE SHOOTING A LOT, SOMETHING HAS GONE WRONG.",
      ),
      hab(
        "b",
        "B · WAR BANNER",
        "PLANTS THE HOUSE BANNER A FEW STEPS AHEAD. TROOPS ON FOLLOW GATHER AT IT, HOLD ORDERS HOLD THERE, AND TROOPS NEAR IT MOVE FASTER. INSIDE ITS REACH YOUR HOUSE CAN SHOP AND BUILD ON NEARBY PADS.",
        "PLANT IT NEXT TO A FAR PAD AND YOUR PARTNER CAN BUY BOMBS IN THE MIDDLE OF THE MAP.",
      ),
      hab(
        "r",
        "R · WAR HORN",
        "EVERYONE ON YOUR SIDE NEARBY HITS HARDER AND RUNS FASTER FOR A FEW SECONDS.",
        "BLOW IT RIGHT AS THE TWO ARMIES MEET.",
      ),
      hab(
        "z",
        "Z · RALLY",
        "HEALS EVERY FRIEND NEARBY, SHAKES OFF STUNS AND SLOWS, HARDENS THEM FOR A FEW SECONDS AND HALVES YOUR PARTNER'S B AND R COOLDOWNS WHEREVER THEY ARE.",
        "SAVE IT FOR THE MOMENT YOUR PARTNER IS ABOUT TO LOSE A FIGHT.",
      ),
      {
        title: "L · FORMATIONS",
        text: "THE HERALD DOESN'T BLOCK, SO L CHANGES THE ARMY'S SHAPE: LOOSE, COLUMN FOR BRIDGES AND FORDS, LINE FOR HOLDING (BRUTES IN FRONT, ARCHERS BEHIND) OR WEDGE FOR CHARGING. IT SHAPES TROOPS THAT HOLD OR FOLLOW.",
        tip: "COLUMN OVER A BRIDGE, LINE ON THE FAR SIDE. NOW IT'S A BRIDGEHEAD.",
        art: { kind: "scene", scene: "formation" },
      },
      {
        title: "X · TAKE UP THE BANNER",
        text: `IN A 2V2 WITH NO HERALDS, HOLD X AWAY FROM A PAD FOR ${M.arena.morph?.holdSeconds ?? 0.6} SECONDS AND YOUR CHAMPION BECOMES THE HERALD: NO LEVELS, NO TALENTS, IN CHARGE OF THE ARMY. ONE PER HOUSE. YOU STAY THAT WAY UNTIL YOU DIE, OR HOLD X AT YOUR KEEP TO CHANGE BACK FOR ${M.arena.morph?.revertCost ?? 50} GOLD.`,
        tip: "FOR WHEN THE ARMY NEEDS A BABYSITTER MORE THAN THE FIGHT NEEDS YOU.",
        art: { kind: "scene", scene: "morph" },
      },
    ],
  };
  return [...heroes.map(heroEntry), herald, ...entries];
}
