// Default per-entity Status block. Every timed effect is stored as an absolute `...Until` sim time, so expiring
// an effect is just `w.time >= until`; the paired multipliers only apply while that time is in the future.
import type { Status } from "../types.ts";

export function newStatus(): Status {
  return {
    slowUntil: 0,
    slowMul: 1,
    stunUntil: 0,
    kvx: 0,
    kvz: 0,
    buffUntil: 0,
    buffDamageMul: 1,
    buffSpeedMul: 1,
    rallyUntil: 0,
    lastHitAt: -99,
    lastHitX: 0,
    lastHitZ: 0,
    invulnUntil: 0,
    lastAttackAt: -99,
    hidden: false,
    seenBy: 0,
    supportDamageMul: 1,
    auraDamageMul: 1,
    stealthUntil: 0,
    ambushMul: 1,
    guardUntil: 0,
    guardMul: 1,
    cowedUntil: 0,
    hexUntil: 0,
    hexOwner: 0,
    bleedStacks: 0,
    bleedDps: 0,
    bleedUntil: 0,
    bleedOwner: 0,
    shield: 0,
    shieldUntil: 0,
    shieldBurst: 0,
    armorMul: 1,
    armorUntil: 0,
    ccImmuneUntil: 0,
    markUntil: 0,
    markTeam: -1,
    markOwner: 0,
    markMul: 1,
    markAll: false,
    markWeaken: 1,
  };
}
