// Animation clip tables for hero/soldier views. Rigs share clip names (idle, run, attack_a/b/c, cast, slam,
// shoot, throw, block, dodge, hit, death...); heroSync maps an action to a clip with these tables.

/** Clips that play once and hold their last frame instead of looping. */
export const ONE_SHOT = new Set([
  "attack_a",
  "attack_b",
  "attack_c",
  "slam",
  "heave",
  "cast",
  "shoot",
  "hit",
  "death",
  "dodge",
  "attack",
  "throw",
  "volley",
  "heartseeker",
  "gust",
  "swing",
  "build",
  "headbutt",
  "crush",
  "pound",
]);
/** Substitute clip when a rig lacks one (followed up to 3 times). */
export const ANIM_FALLBACK: Record<string, string> = {
  throw: "attack_b",
  volley: "shoot",
  heartseeker: "shoot",
  shoot: "cast",
  gust: "dodge",
  swing: "dodge",
  whirl: "attack_c",
  build: "slam",
  headbutt: "attack_b",
  crush: "slam",
  pound: "slam",
};
/** Ability kind -> clip; unlisted kinds play "cast". */
export const KIND_ANIM: Record<string, string> = {
  pip: "cast",
  rake: "cast",
  heave: "heave",
  volley: "volley",
  heartseeker: "heartseeker",
  keg: "throw",
  harpoon: "shoot",
  reel: "throw",
  tonguelash: "cast",
  riptide: "slam",
  powderkeg: "throw",
  brewfest: "slam",
  fort: "build",
  lookout: "build",
  dome: "cast",
  squarethrow: "throw",
  kegrocket: "block",
  inkbolt: "shoot",
  swarm: "cast",
  erratum: "attack_c",
  manuscript: "slam",
  pagegust: "gust",
  slam: "slam",
  quake: "slam",
  leap: "slam",
  warcry: "cast",
  summon: "cast",
  gravewalk: "cast",
  hex: "cast",
  repair: "cast",
  turret: "cast",
  ramp: "cast",
  wall: "cast",
  zone: "cast",
  stealth: "cast",
  trap: "shoot",
  reach: "attack_b",
  shoot: "shoot",
  banner: "cast",
  rally: "cast",
  works: "cast",
  ballista: "cast",
  whirl: "attack_c",
  shove: "attack_a",
  throw: "attack_b",
  wrench: "attack_b",
  dash: "attack_b",
  flurry: "attack_b",
  parry: "block",
  dredge: "throw",
  bilge: "cast",
  davygrip: "slam",
  chainswing: "swing",
  none: "idle",
  headbutt: "headbutt",
  switcheroo: "cast",
  crush: "crush",
  pound: "pound",
};
