// Animation clip tables for hero/soldier views. Rigs share clip names (idle, run, attack_a/b/c, cast, slam,
// shoot, throw, block, dodge, hit, death...); heroSync maps an action to a clip with these tables.

/** Clips that play once and hold their last frame instead of looping. */
export const ONE_SHOT = new Set([
  "attack_a",
  "attack_b",
  "attack_c",
  "slam",
  "cast",
  "shoot",
  "hit",
  "death",
  "dodge",
  "attack",
  "throw",
  "volley",
  "heartseeker",
]);
/** Substitute clip when a rig lacks one (followed up to 3 times). */
export const ANIM_FALLBACK: Record<string, string> = {
  throw: "attack_b",
  volley: "shoot",
  heartseeker: "shoot",
  shoot: "cast",
};
/** Ability kind -> clip; unlisted kinds play "cast". */
export const KIND_ANIM: Record<string, string> = {
  pip: "cast",
  rake: "cast",
  volley: "volley",
  heartseeker: "heartseeker",
  keg: "throw",
  powderkeg: "throw",
  brewfest: "slam",
  kegrocket: "block",
  slam: "slam",
  quake: "slam",
  leap: "slam",
  warcry: "cast",
  summon: "cast",
  gravewalk: "cast",
  hex: "cast",
  repair: "cast",
  turret: "cast",
  ramp: "cast",
  wall: "cast",
  zone: "cast",
  stealth: "cast",
  trap: "shoot",
  reach: "attack_b",
  shoot: "shoot",
  banner: "cast",
  rally: "cast",
  works: "cast",
  ballista: "cast",
  whirl: "attack_c",
  shove: "attack_a",
  throw: "attack_b",
  wrench: "attack_b",
  dash: "attack_b",
  flurry: "attack_b",
  parry: "block",
  none: "idle",
};
