PACKAGE_NAME="hid-gamecube-adapter"
PACKAGE_VERSION="r11.25387ab.grudge1"
MAKE[0]="make KERNEL_SOURCE_DIR=$kernel_source_dir"
CLEAN="make KERNEL_SOURCE_DIR=$kernel_source_dir clean"
BUILT_MODULE_NAME[0]="hid-gamecube-adapter"
DEST_MODULE_LOCATION[0]="/kernel/drivers/misc"
AUTOINSTALL="yes"
