import json

SEED = "ec88083c7a43bda059eac222c12dd1f89f4788e50b940c8d07b29e7d64d8b081"

W = D = 72
C = W / 2
ops = []
props = []


def shape(kind, **kw):
    ops.append({"op": "shape", "shape": kind, **kw})


def cell(op, **kw):
    ops.append({"op": op, **kw})


def prop(t, x, z, **kw):
    props.append({"type": t, "x": x, "z": z, **kw})


# 72 x 72 (was 112): keep castle 15 x 18 (x 1-16, z 27-45), arm z 26-46 out to the summit plaza (r 12), corner
# cirque crossed by a rock-causeway trail from the castle's north gate to the next arm.
ops.append({"op": "noise", "amp": 0.35, "scale": 0.11, "seed": int(SEED[:6], 16) % 997})

shape("rect", x=-12, z=-12, w=W + 24, h=D + 24, y=-4.0, mode="set")
shape("rect", x=-12, z=19, w=14, h=9, y=2.2, edge=6, mode="max", wobble=1.2)
shape("rect", x=-12, z=26, w=40, h=20, y=4.4, edge=2.5, mode="set", wobble=1.2)
shape("rect", x=18, z=27, w=9, h=18, y=5.4, edge=4, mode="max", wobble=0.6)
shape("rect", x=23, z=27, w=6, h=18, y=6.4, edge=4, mode="max", wobble=0.6)
shape("circle", x=C, z=C, r=12, y=7.4, edge=2.5, mode="set", wobble=1.2)
shape("circle", x=C, z=C, r=4.2, y=8.3, edge=1.6, mode="set", wobble=0.3)
shape("circle", x=C, z=C, r=2.2, y=8.6, edge=0.8, mode="set")

shape("rect", x=1, z=27, w=15, h=18, y=3.9, edge=0, mode="set")
shape("rect", x=16, z=33, w=4, h=6, y=3.9, edge=2.5, mode="set")
shape("rect", x=6, z=23, w=4, h=4, y=3.9, edge=2.5, mode="set")

trail = [(8, 24), (8.5, 20.5), (10, 17), (12.5, 14), (16, 11.5), (19.5, 9.5), (22.5, 8.5)]
for i, (x, z) in enumerate(trail):
    t = i / (len(trail) - 1)
    y = 3.9 - 2.4 * (1 - abs(t * 2 - 1) ** 1.4)
    shape("circle", x=x, z=z, r=1.9, y=y, edge=2.4, mode="max", wobble=0.4)
shape("circle", x=14, z=14, r=2.6, y=1.5, edge=2.4, mode="max", wobble=0.4)

for (x, z, r, y) in [(19.5, 19.5, 2.5, -3.5), (4.5, 4.5, 3, -4.5), (15, 3.5, 2, -5), (3.5, 15, 2, -5)]:
    shape("circle", x=x, z=z, r=r, y=y, edge=3, mode="max", wobble=0.8)

shape("circle", x=20, z=27.5, r=1.6, y=5.6, edge=1.6, mode="max", wobble=0.4)
shape("circle", x=22, z=44.5, r=1.8, y=5.8, edge=1.5, mode="max", wobble=0.4)
shape("circle", x=28.5, z=28.5, r=1.7, y=8.6, edge=1.5, mode="max", wobble=0.4)

cell("wall", style="rim", x=0, z=0, w=W, h=1)
for (x, z, w, h) in [(1, 1, 4, 18), (1, 1, 25, 4), (8, 1, 9, 5), (17, 1, 9, 4), (13, 18, 13, 8), (18, 12, 8, 6), (7, 6, 2, 2)]:
    cell("wall", style="rim", x=x, z=z, w=w, h=h)

cell("paving", x=1, z=27, w=15, h=18)
cell("wall", style="castle", x=1, z=27, w=5, h=1)
cell("wall", style="castle", x=10, z=27, w=7, h=1)
cell("wall", style="castle", x=1, z=44, w=16, h=1)
cell("wall", style="castle", x=16, z=27, w=1, h=6)
cell("wall", style="castle", x=16, z=39, w=1, h=6)

for i, x in enumerate(range(17, 27, 2)):
    zz = 35 + [0, 1, 0, -1, 0][i]
    cell("dirt", x=x, z=zz, w=3, h=2 + (i % 2))
cell("dirt", x=7, z=22, w=2, h=5)
for z in range(31, 41):
    for x in range(31, 41):
        if (x + 0.5 - C) ** 2 + (z + 0.5 - C) ** 2 <= 4.2 ** 2:
            cell("paving", x=x, z=z, w=1, h=1)

prop("banner", 2.5, 28.5)
prop("banner", 15.5, 28.5)
prop("torch", 17.5, 32.5)
prop("torch", 17.5, 39.5)
prop("tower", 2.5, 28.5, solid=True)
prop("tower", 15.5, 43.5, solid=True)
prop("arch", 16.5, 36.0, rot=90)
prop("arch", 8.0, 27.5, rot=0)
prop("statue", 27, 36)
prop("torch", 32.5, 32.5)
prop("rock", 20.5, 27.5, scale=1.0, solid=True)
prop("rock", 22.5, 44.5, scale=1.1, solid=True)
prop("rock", 18, 46.5, scale=0.9)
prop("pine", 17, 27, scale=1.0)
prop("pine", 24.5, 26.8, scale=0.9)
prop("pine", 25, 45.5, scale=1.1)
prop("pine", 18.5, 45.5, scale=1.0)
prop("pine", 10.5, 21, scale=1.0)
prop("pine", 21, 10.5, scale=1.0)
prop("rock", 12, 15.5, scale=0.8)
prop("crate", 11.5, 42.5)
prop("crate", 3.5, 37.5)

pads = [
    {"zone": "home", "x": 5, "z": 31},
    {"zone": "home", "x": 12, "z": 31},
    {"zone": "home", "x": 12, "z": 41},
    {"zone": "neutral", "x": 21.5, "z": 31.5},
    {"zone": "neutral", "x": 21.5, "z": 40.5},
    {"zone": "neutral", "x": 29, "z": 29},
]

data = {
    "name": "Frostcross Summit",
    "blurb": "Four keeps at the feet of a frozen cross. Avalanches break off the summit and roll down one ridge at a time. Rock causeways cross the cirques between ridges.",
    "emblem": "peak",
    "width": W,
    "depth": D,
    "teams": 4,
    "mode": "ffa",
    "mirror": "quad",
    "surround": "alpine",
    "rimHeight": 4.5,
    "waterLevel": -12.0,
    "chasm": -2.2,
    "avalanche": {"firstSeconds": 50, "everySeconds": 38, "warnSeconds": 6, "sweepSeconds": 1.6, "driftSeconds": 14,
                  "lane": {"x": 16, "z": 26, "w": 10, "h": 20}, "from": "e",
                  "heroDamage": 140, "unitDamage": 0.75, "knock": 4.0},
    "notes": "Generated by tools/mapgen-frostcross.py. Four-fold rotation about the centre (mirror quad): author the west arm, its keep (team 0) and the north-west corner; every op, prop and pad is copied at 90 degree steps and teams advance by one per step. Ridge trails cross each mountain corner between neighbouring arms. The cross is a set of ridgelines: the summit plaza is the high point and each arm slopes down to its keep; the corners are deep cirques (blocked with rim walls) crossed by narrow rock causeways. Avalanches break off the summit and roll down one arm at a time toward its keep (lane rect in team 0's arm, rotated per arm; 'from' is the side the slide starts on).",
    "ops": ops,
    "props": props,
    "cores": [{"team": 0, "x": 6, "z": 36}],
    "pads": pads,
    "spawns": [{"team": 0, "x": 10, "z": 38}],
    "horns": [{"x": 14, "z": 14, "arms": [0, 1]}],
    "jumppads": [{"a": {"x": 30.5, "z": 33.5}, "b": {"x": 8.5, "z": 40}}, {"a": {"x": 3.5, "z": 41}, "b": {"x": 32, "z": 40}}, {"a": {"x": 25, "z": 43.5}, "b": {"x": 41, "z": 22}}],
    "patrols": [{"a": {"x": 8.5, "z": 20.5}, "b": {"x": 19.5, "z": 9.5}}],
    "dens": [{"x": 16, "z": 16}],
}

with open("data/maps/frostcross.json", "w") as f:
    json.dump(data, f, indent=1)
print("wrote data/maps/frostcross.json", len(ops), "ops")
